### PR TITLE
Change zabapgit download

### PR DESCRIPTION
**Pull request by mbtools**
Browsers will download source instead of displaying it

### CODE REVIEW

**Comment by flaiker** [comment]
Doesn't seem to change anything in edge, still displayed.

**Comment by mbtools** [comment]
hmm, that's odd:
https://css-tricks.com/building-good-download-button/ 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attributes

**Comment by flaiker** [comment]
Should work: https://caniuse.com/download

I tested here: https://github.com/abapGit/abapGit/blob/4f3fbd5c161360e49d2043a95185e6e4b91dd6ad/README.md

Seems like GitHub strips it?

image

**Comment by mbtools** [comment]
It's also not "same origin". So I don't think the change will work

**Comment by flaiker** [comment]
Yes that's probably it. Even GitHub doesn't do it when clicking their download button on https://github.com/abapGit/build/blob/main/zabapgit.abap

image

**Comment by flaiker** [comment]
Or wait, does `<a href="https://github.com/abapGit/build/blob/main/zabapgit.abap?raw=true" download></a>` work?

**Comment by mbtools** [comment]
probably striped by the markdown parser. maybe it need to be a button instead of ahref.

**Comment by larshp** [comment]
I changed this PR to draft mode, as it sounds like its not working yet?

**Comment by mbtools** [comment]
dr. google doesn't know an answer either. closing

**Pull request closed without merging**
