### PR TITLE
Ignore empty files when staging

### PR DESCRIPTION
**Pull request by mbtools**
Empty files should not be staged. Empty files can happen if objects exist but not in an active version (like a new table).

Related to #4569

### CODE REVIEW

**Comment by larshp** [comment]
something like a SMIM object is a container for a different file, these might be empty

I think TABLs in New status should be considered non existing

**Comment by mbtools** [comment]
If new TABL is "non-existing", it can't be uninstalled. It's in the system, so why hide it?

Empty mime-objects? Not sure if that's possible. I will check

**Comment by larshp** [comment]
hmm

**Comment by larshp** [comment]
a active ABAP include might be empty,
image

**Review by larshp — CHANGES_REQUESTED** [review]
wip

**Comment by mbtools** [comment]
Closing in favor of #4584

**Pull request closed without merging**
