### PR TITLE
Change default width of abapgit

### PR DESCRIPTION
**Pull request by FreHu**
adresses part of #4734 
This changes the abapgit layout to a centered 1280px fixed width instead of taking up 100%, with some exceptions:

### Repo list will use full width with detail enabled
image
image

### Side-by-side Diff
image
image

### CODE REVIEW

**Comment by mbtools** [comment]
i pulled the change and it looks good. my current screen is 1920px so it takes a bit to get used to. i will keep using it like this for a while before my final verdict.

**Comment by mbtools** [comment]
The change looks and feels good! Some follow-ups:
- location of classic popups (see above)
- some wrapping on repo overview (I have quite long URLs, see discussion #4734)

those can be handled separately. approved from my side

**Comment by mbtools** [comment]
yes, center. I think background settings is wider than the others. should all be same width.

**Comment by FreHu** [comment]
All centered now
image
image

**Pull request merged**
