### PR TITLE
Add hover hightlight to repo toolbar

### PR DESCRIPTION
**Pull request by mbtools**
Highlights links in repo toolbar on hover

image

image

image

### CODE REVIEW

**Review by schmelto — APPROVED** [review]

**Comment by sbcgua** [comment]
Hmmm, i'd look into changing default color. Hover is good, but the problem that these elements don't looks as active in the first place.

**Comment by mbtools** [comment]
But why isn't the URL blue or the commit id? The favorite star is gray, too, and I don't think anyone has a problem using it. 

I think it's nice that these screen elements are gray and not "active": Good to have (for us) but generally not important or rarely used.

**Comment by mbtools** [comment]
There's room for improvements (as always ;-). For PR, we should use the fork icon image. 

I do like to see the URL for the same reason you mentioned for the overview page.  But maybe we just mirror the GH design:
image
image

**Comment by larshp** [comment]
merging

**Comment by sbcgua** [comment]
good idea with fork/origin, just let's keep in mind the api request limit

**Pull request merged**
