### PR TITLE
Change icon for user settings

### PR DESCRIPTION
**Pull request by mbtools**
Reduce confusion because of same icon for different settings.

Closes https://github.com/abapGit/abapGit/issues/5088

Before: 

image

After:

image

### CODE REVIEW

**Comment by larshp** [comment]
add as screenshot as a comment in this PR?

**Comment by mbtools** [comment]
I could swear that I had the screenshots there yesterday 🤷 Well, I added them back 

maybe once a year on Jimi Hendrix birthday, we change it to a guitar @sbcgua

**Comment by larshp** [comment]
looking at the icon, I'd guess these are user settings, but there are also global settings?

**Comment by mbtools** [comment]
back to discussion in #5088

**Comment by mbtools** [comment]
Adjusted according to #5088

**Pull request merged**
