### PR TITLE
IAMU v2: Serialize MIMEs as separate file + fixes

### PR DESCRIPTION
**Pull request by mbtools**
- Introduce v2 of `IAMU` serializer
- MIME is now serialized as separate file (closes https://github.com/abapGit/abapGit/issues/6495)
- Fix serializing description of the object

image

- Fix errors when updating object

image

- Fix order of deserializing due to dependencies on `IASP` and `IARP`

Test repo: https://github.com/abapGit-tests/IARP_IASP_IATU_IAMU > `iamu_v2` branch

### CODE REVIEW

**Comment by larshp** [comment]
https://github.com/open-abap/open-abap-core/pull/790

**Comment by larshp** [comment]
suggest creating another test repo for the v2, its much more visible than a branch, plus CI logic works per repo(not per branch)?

**Comment by mbtools** [comment]
CI only works with the most recent version of a serializer (you can deserialize an older version but get flagged for diffs). I will just merge the v2 branch in the test repo.

**Comment by larshp** [comment]
oh, cool

**Review by larshp — APPROVED** [review]

**Pull request merged**
