### PR TITLE
Fix empty JSON file for AFF based objects

### PR DESCRIPTION
**Pull request by BeckerWdf**
Fixes: https://github.com/abapGit/abapGit/issues/6765

### CODE REVIEW

**Comment by larshp** [comment]
is it possible to add a unit test for this?

**Comment by BeckerWdf** [comment]
> is it possible to add a unit test for this?

Possible: Sure. But I am not familiar with the test in this class. And to be honest I might not find enough time for that.
Would be great if maybe @mbtools could contribute a unit test.

**Comment by BeckerWdf** [comment]
I just wanted to quickly fix this bug.

**Review by mbtools — APPROVED** [review]

**Comment by mbtools** [comment]
This could have been caught by CI but I'm still missing a system where [AFF is supported](https://ci.abapgit.org/src/0242ac1100021eebb1bbc829fae4fe35.smim.abapgit_ci_result.html#abap_file_format). 

Hopefully, next release of ABAP Dev Edition will work.

**Pull request merged**
