### PR TITLE
Retrieve transport and changed by for deletions

### LINKED ISSUE #2738: Get last changed by for deleted objects from transport requests
Currently retrieving the user who deleted an object is not supported. This leads to confusion on multi-user systems or people forgetting to commit deletions.

This can be improved by looking for the information in the transport request.

### PR DESCRIPTION
**Pull request by FreHu**
Resolves #2738

### CODE REVIEW

**Comment by mbtools** [comment]
Helpful. Should we use the same approach to find the user in case it is returned as "unknown" by the serializer class?

**Comment by FreHu** [comment]
Hmm, I don't see why not. There's also the object type missing for deleted objects, this can be easily added.

**Comment by mbtools** [comment]
If the object is locked in your transport (task) and I try to change it, then it will create a new task with my user. My task will have a newer date/time on it. That would be suitable if there's only one object in the transport. Conclusion looking up the transport won't work.

I think we remove this then:
https://github.com/abapGit/abapGit/blob/9672f5b030617a41b3879040ca11ba9f1d15cb76/src/objects/zcl_abapgit_objects.clas.abap#L256

**Comment by larshp** [comment]
It wont work in the general scenario

In my experience, a lot of times the object will be changed by a single user in a single transport, in this case we can determine the correct user, which is better than nothing IMHO

**Comment by FreHu** [comment]
I propose to merge this as is and then I can do the core logic and removal of delete button from stage as follow-ups.

**Comment by mbtools** [comment]
If we use the transport lookup, it should be central and also work on Diff page for example. Implement it in zcl_abapgit_objects.

**Comment by larshp** [comment]
I've opened https://github.com/abapGit/abapGit/issues/4129

merging

**Pull request merged**
