### PR TITLE
Fix for namespace check when there are multiple namespaces within a repo 

### PR DESCRIPTION
**Pull request by thomas-nor-neptune**
There was an error introduced with the new namespace check (https://github.com/abapGit/abapGit/pull/6212) when there are multiple namespaces within one repository. The check would always give an error.

image

After this small code change the check is changed to check if the root package is one of the collected namespaces, and the error is gone.

image

Hope that this fix will become part of the standard version of abapGit :)

### CODE REVIEW

**Comment by mbtools** [comment]
Hmm I thought it's not possible to have multiple namespaces in a repo. The root package is in one namespace and therefore all included objects must be in the same namespace. No?

Where's /nep/ coming from in your example?

**Comment by thomas-nor-neptune** [comment]
Hi Marc, thanks for quick reply! In this case package /neptune/nad is the root package with multiple subpackages. One of them is /nep/soft in namespace /nep/. Up until now the /nep/ namespace has only been used for authorization objects due to limitations for namespace with authorization objects. Generally speaking I guess there could be many namespaces for a repo with the use of subpackages, and it actually seems like it was already partially implemented like this with the looping over internal table lt_namespace. Up until the recent change we did not get this error message, but in all fairness it seems to be limited to slightly annoying error messages that can be ignored, at least in our case :)

**Comment by thorsten-wolf-neptune** [comment]
Hi,
No the namespace dosen't care about its parent package. Namespaces are just relevant for the artifacts themselves.
You can combine as many namespaces as you want in child packages.

**Comment by mbtools** [comment]
I had coded the previous logic collect/checking namespaces using a loop since it was easier to code. I assumed subpackages must follow naming of the parent but obviously learning ABAP quirks never ends. 😄 Thanks for the fix!

**Review by mbtools — APPROVED** [review]
lgtm

**Comment by larshp** [comment]
welcome to abapGit as a contributor 🎉

**Pull request merged**
