### PR TITLE
Unsupported object count in repo statistics

### PR DESCRIPTION
**Pull request by yellappam**
Added unsupported object count in repo statistics.  [issue#4597](https://github.com/abapGit/abapGit/issues/4597)

Unit testing:

Package:
image

2 unsupported objects(BOPF) ignored
image

Unsupported object count matching in Local:
image

It is very unlikely to get unsupported objects >0 under remote column unless the remote repository was pushed with higher AG version and PULL/view with lower AG version.

### CODE REVIEW

**Comment by larshp** [comment]
this specific feature is nice to have, so I'd probably like to keep changes out of the TADIR and DEFINITIONS which are very central objects

**Comment by mbtools** [comment]
Agree with Lars. Let's keep it all in 'zcl_abapgit_gui_page_sett_info`. At the end of `read_stats`, one `loop at lt_local_items` and one `loop at lt_remote_items` should ok to count the not-supported objects.

**Review by mbtools — CHANGES_REQUESTED** [review]
see comment

**Comment by yellappam** [comment]
lt_local_items will not have unsupported objects as they have been filtered before. I will remove changes to TADIR and DEFINITIONS. Will enhance method ZCL_ABAPGIT_REPO=>GET_UNSUPPORTED_OBJECTS_LOCAL to identify unsupported objects after TADIR read.

**Review by mbtools — APPROVED** [review]
Nice. LGTM 👍

**Pull request merged**
