### PR TITLE
Refactor user persistence

### PR DESCRIPTION
**Pull request by mbtools**
Instead of selecting the settings from the DB for each "get" (on unbuffered table), user settings are now kept in instance memory. Simplifies code, too.

Added unit tests.

### CODE REVIEW

**Comment by flaiker** [comment]
Why are you using `DB_COMMIT` instead of `COMMIT WORK` avoiding the SAP LUW ?

**Review by larshp — CHANGES_REQUESTED** [review]
see comment above

**Comment by mbtools** [comment]
I might have had several sessions open during my tests. seems to work now.

**Comment by larshp** [comment]
@flaiker any additional comments?

**Comment by flaiker** [comment]
Seems fine to me.

I guess the risk level of the unit test would be debatable as DB changes are made. https://help.sap.com/viewer/ba879a6e2ea04d9bb94c7ccd7cdac446/202009.000/en-US/4925667929ac16b7e10000000a42189d.html

**Comment by larshp** [comment]
yea, agree on the risk level

**Comment by larshp** [comment]
@mbtools if you change the risk level, I think this one can be merged

**Comment by sbcgua** [comment]
just a side idea: maybe refactor settings (repo, user, ...) to a string map ? setter/getter for each setting look a bit overwhelming imho. A simple param validation would work well instead.

**Comment by mbtools** [comment]
agree. or ajson. we could get the settings with paths and have arrays.

**Comment by sbcgua** [comment]
json in xml ? ufff ! on the other hand ... would be quite flexible. One of our products supposes customizing ... but the customizing shape is not obvious at this stage of development (tables, maintenance views ...). So we store the customizing in json in the way similar to abapgit (just that it is json, not xml) and respectively wrote a customzing transaction, which is able to put it to transports and such things ... not that bad so far ... very very flexible

**Comment by mbtools** [comment]
no, just json (no more xml). it would improve flexibility as you wrote, and make things easier to consume (no individual classes or get/set method). 

at the same time, we should put the checksums into a transparent table to improve efficiency esp if we want to store by branch or commit. 

anyway, there's always another refactor

**Comment by larshp** [comment]
thanks 👍

**Pull request merged**
