### PR TITLE
Check logon language during uninstall

### LINKED ISSUE #5730: attempt to uninstall leads to SE63
I had a [zapcommander](https://github.com/tricktresor/zapcommander) installation made when the original [language was German](https://github.com/tricktresor/zapcommander/issues/9).
Pulling the current version with English as main language wouldn't work so I tried uninstalling first, got prompted to fix the translations before being allowed to continue and then this happened:
immagine

Basically, the top menu and the status message at the bottom belong to SE63, which is complaining about untranslated strings.
Exiting the translation and trying to continue uninstalling means loads of prompts to switch language, so I gave up, removed everything via SE80 and reinstalled. No big deal, still the UI was a fun mix.

### PR DESCRIPTION
**Pull request by mbtools**
Uninstalling a repo should only be allowed in the original language of the repo (same as pulling).

Also adds write-protect check to sync behavior with deserializing repo.

Fixes #5730

### CODE REVIEW

**Comment by larshp** [comment]
@AndreaBorgia-Abo can you help testing this PR?

**Comment by AndreaBorgia-Abo** [comment]
Will do.

**Review by AndreaBorgia-Abo — COMMENTED** [review]
Testing setup:
* updated abapgit to current main
* completely uninstalled zapcommander from A4H
* reinstalled but pulled the [last commit](https://github.com/AndreaBorgia-Abo/zapcommander/commit/4b3666a5253695a73ea84b42337514521645f3b4) before the language change
* verified that the issue still appears as reported
* pulled this PR via settings menu
* tried again uninstalling zapcommander

Here is the sequence of screenshots: something is different but at the end I still get the same phantom SE63 menu as earlier.  Should I have done something else? I expected a language switch to happen automatically but, on second thought, I'm not sure that's even possible without mucking with SAP internals.

immagine
immagine
immagine
immagine
immagine

**Comment by mbtools** [comment]
Trying to uninstall (while logged on in the wrong language) should have immediately raised an exception.

**Comment by mbtools** [comment]
Try again with the updated check

**Review by AndreaBorgia-Abo — APPROVED** [review]
Once again, from scratch, installed last German version (from a German login), then tried to uninstall from an English login.
immagine
Got this warning:
immagine

LGTM

**Comment by mbtools** [comment]
Thanks for testing!

**Pull request merged**
