### PR TITLE
decouple http from login manager

### PR DESCRIPTION
**Pull request by larshp**

### CODE REVIEW

**Comment by larshp** [comment]
this change breaks abapGit/ADT_Backend, but it doesnt work anyhow

**Comment by mbtools** [comment]
nice. now you can add unit test `save` and initial user/pwd for 100% coverage :-)

**Comment by larshp** [comment]
https://coverage.abapgit.org/src/http/zcl_abapgit_login_manager.clas.abap.html

**Comment by larshp** [comment]
unit test for save() added

**Review by mbtools — APPROVED** [review]
👍

**Pull request merged**
