### PR TITLE
Add zif_abapgit_git_operations to zif_abapgit_repo

### PR DESCRIPTION
**Pull request by PeregrinTooc**
Added zif_abapgit_git_operations to zif_abapgit_repo_online to ease the change from references to zcl_abapgit_repo_online to zif_abapgit_repo_online

### CODE REVIEW

**Comment by larshp** [comment]
perhaps move a bit more in this PR, its just a one line change?

**Comment by jfilak** [comment]
Perhaps a code snippet explaining this change would help.

**Comment by larshp** [comment]
@PeregrinTooc

**Comment by PeregrinTooc** [comment]
@larshp, @jfilak abaplint seems to be f***** around with me. It tells me to implement a method which is actually implemented. ABAP syntax checker doesn't have a problem...

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint/issues/1561 opened

but, to me, its really difficult to figure out what is going on, there are multiple interfaces, all with ALIASes. 
It probably works, but seems more like a workaround than object oriented design?

**Comment by PeregrinTooc** [comment]
> [abaplint/abaplint#1561](https://github.com/abaplint/abaplint/issues/1561) opened
> 
> but, to me, its really difficult to figure out what is going on, there are multiple interfaces, all with ALIASes.
> It probably works, but seems more like a workaround than object oriented design? Perhaps I don't see the full picture which direction this is going?

Hi, yes, it is messy :( 
Unfortunately, refactoring will take me all over the place, making merge conflicts more and more probable. I want to get rid of all the aliases obviously, but that will probably mean implementing some kind of strategy pattern with multiple components, and it will take time.
For me, it is imperative that every refactoring I do is a small step towards the final pattern. So the next step for me would probably be analysing the users of the interfaces and find good ways to cut it.  

I can work on that on this branch and make more and more commits and convert the PR to draft for the time being, if that seems reasonable to you?

**Comment by larshp** [comment]
It feels too difficult for me, its just two kinds of repositories, this should be easier(see links to discussions in the previous PR)

I'm okay with removing features/impairing performance/introducing code duplication to have a simple design

**Comment by larshp** [comment]
@PeregrinTooc see comments in #2127

**Comment by larshp** [comment]
@PeregrinTooc I suggest abandoning this PR, and instead first do

* step B from https://github.com/abapGit/abapGit/issues/2127#issuecomment-732262897
* review https://github.com/abapGit/abapGit/pull/4233
* review https://github.com/abapGit/abapGit/pull/4231

**Comment by PeregrinTooc** [comment]
@larshp makes sense. Will tackle step 'B'

**Comment by PeregrinTooc** [comment]
abandoned. Changes will be done in another way.

**Pull request closed without merging**
