### PR TITLE
Fix master language only, duplicate entries for shi3 objects

### PR DESCRIPTION
**Pull request by jan-jezek**

### CODE REVIEW

**Review by FreHu — APPROVED** [review]
👍

**Comment by jan-jezek** [comment]
For "Fix duplicates in shi3":
abap_git

**Review by FreHu — APPROVED** [review]
We found the second problem on our internal system, not sure why the duplicates appear. It was not caused by the change to language serialization.

**Comment by larshp** [comment]
thanks,

welcome to abapGit as a contributor 🎉

**Pull request merged**
