### PR TITLE
SFPI: exists() also look for inactive objects

### LINKED ISSUE #6866: SFPI pull fails with deserialize error if inactive interface is present
I'm doing lots of back and forth testing where I repeatedly copy a template interface to a ZTESTINTERFACE without activating it.

In this scenario (inactive interface exists):
grafik

attempting to pull from a repo where ZTESTINTERFACE is present will result in a confusing error:
grafik

Am I reading it correctly that we only care about the existence here? Could we ignore the status when reading the table? PR coming up shortly.

edit: PR #6867

### PR DESCRIPTION
**Pull request by AndreaBorgia-Abo**
remove activation filter when checking for existence

fix #6866

### CODE REVIEW

**Review by larshp — APPROVED** [review]
thanks looks good to me

https://docs.abapgit.org/development-guide/serializers/serializers.html#interface

**Comment by AndreaBorgia-Abo** [comment]
I don't have write access (and for the moment rightly so), could you @larshp or @mbtools merge this?

**Comment by larshp** [comment]
@AndreaBorgia-Abo I actually granted you write access some time ago 😄 but anyhow, just leave the PRs open for a while to leave time for more possible reviews

**Comment by AndreaBorgia-Abo** [comment]
@larshp weird, the MERGE option was nowhere in sight and there was a warning about missing write access.
Anyhow, thanks @mbtools

**Pull request merged**
