### PR TITLE
Refactor I18N settings

### PR DESCRIPTION
**Pull request by mbtools**
- Consolidate I18N parameters into a structure and pass it to XML and serializer classes (#4415)
- Continue change of terminology "master" > "main" (#4043)

### CODE REVIEW

**Comment by larshp** [comment]
is the change backwards compatible?

**Comment by sbcgua** [comment]
if you ask me I'd say this main-master problem is a bit overemphasized ... though just imho, no blocking ... besides sap will not change their FMs interface so ... it kind of domain language from this perspective

**Comment by mbtools** [comment]
@larshp yes compatible. This PR doesn't change any of the serialization.

**Comment by mbtools** [comment]
"It's kind of domain language [now]" is the problem. It shouldn't be. Replacing master/slave terminology might seem superficial but it sends a signal that we care. If it makes just one person feel better working with abapGit or contributing, we all win.

**Pull request merged**
