### PR TITLE
Trigger main command when pressing enter in form

### PR DESCRIPTION
**Pull request by mbtools**
Adds hidden button that triggers main command when pressing the enter key

### CODE REVIEW

**Comment by flaiker** [comment]
I am a bit split on this. Feel free to ignore :)

In SAP GUI applications the ENTER button typically just triggers input validation and rarely (?) advances on to the next dialog step and even more rarely leaves the dialog entirely. These are often done with Ctrl+S (save / post document) or F8 (execute the thing). A notable exception to this are popups which do work with enter and also entry level dynpros where you just enter a document number to open it the corresponding object.

I guess this is more common in other applications. But let's say I am using an online shop and I am in my shopping cart. I wouldn't expect the shopping cart to be submitted by pressing enter. Or is that the case and I am just not used to it?

**Comment by mbtools** [comment]
It only triggers if you define a command button as "main" (rendered in blue). So if a form should not be submitted on Enter like your cart example, then it should have just regular buttons.

Also, the current behavior is quite confusing since enter will trigger the first button in the form, which is often a "side buttons" like the "package value help" in "New Online". 

PS: The SAP behavior you described is actually a reason why so many ppl hate "SAP". I could go on about this for a long time... ;-)

**Comment by sbcgua** [comment]
I have a bit controversial feelings about it. On the one hand control from keyboard is certainly good.
On the other hand I also would not expect "enter" to submit the form. I would expect enter to open "current" field search. And I'd expect to be able to move between fields with tab/shift+tab. Consequently "enter" on main button would trigger the submit. And maybe "Ctrl+enter" should submit the form from all places. This correlates with typical web app behavior.
Also hidden controls are ... not ideal. Probably JS solution would be more suitable.
All IMHO. Not a strong opinion.

**Comment by mbtools** [comment]
The default browser behavior is that pressing Enter submits the form (https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission). To be exact, the first "submit" button is triggered. This explains, why on "New Online" the Enter key will trigger the side-button for "Package" since all buttons in `zcl_abapgit_html_form` are rendered as `input type="submit"`. 

Also, anything in Windows and macOS behaves this way *in case a "main/default" button is defined* (I'm quite certain Linux UIs do the same). So, I'm not sure why you think this would be unexpected. 

The hidden control is not ideal but works seamlessly in plain HTML. This should avoid issues Java Gui or non-JS frontends. 

If we don't want the behavior, then we can simply create forms without a default button.

**Comment by larshp** [comment]
hmm, yea, this is difficult

**Comment by sbcgua** [comment]
> If we don't want the behavior, then we can simply create forms without a default button.

Semantically-wise, this sounds very strange :)))

Well, me personally, I would try finding another, less hacky, solution. But if this helps, I don't block.

**Comment by larshp** [comment]
should it only add the empty button if
https://github.com/abapGit/abapGit/blob/0f563904bd6955be1b1194359e692eb6054dc4f2/src/ui/zcl_abapgit_html_form.clas.abap#L355
does not add a submit

**Comment by mbtools** [comment]
all buttons are `type="submit"` (without it, there's no roundtrip to the SAP HTML control). the hidden button makes sure that on enter the main button is triggered and not any of the other ones.

**Comment by larshp** [comment]
lets try it

**Pull request merged**
