### PR TITLE
Diff: Add options to ignore indent, comments, case

### PR DESCRIPTION
**Pull request by mbtools**
Continuing on #2804

Enjoy!

image

### CODE REVIEW

**Review by larshp — APPROVED** [review]

**Comment by christianguenter2** [comment]
Really useful feature 👍 Thx

**Comment by christianguenter2** [comment]
Would be useful on patch page too?

**Comment by albertmink** [comment]
`Ignore Indentation` suggest that it does ignores only leading white-space. Indeed, it seams it ignores white space changes at all. This diff is `no diff` for `Ignore Indentation`.
image

Might align to git wording, e.g. `space change`
image

**Comment by mbtools** [comment]
You're right about the indentation/whitespace changes. We are reusing the standard SAP diff, which describes it incorrectly:

image

I was just using the same terminology 😀 .  

How about "Ignore Whitespace"?

**Comment by albertmink** [comment]
Ignore Whitespace is definitely better than the indentation 😅

**Pull request merged**
