### PR TITLE
Rename `zcl_abapgit_file_status`

### PR DESCRIPTION
**Pull request by mbtools**
Change name from  `zcl_abapgit_file_status=>status` to  `zcl_abapgit_repo_status=>calculate`.

Ref https://github.com/abapGit/abapGit/issues/6178

Todo: https://docs.abapgit.org/development-guide/api/api.html#status

### CODE REVIEW

**Comment by larshp** [comment]
looks like this breaks something in abapGit/background_modes

**Comment by larshp** [comment]
this is a step binding the code more towards repo instead of decoupling repo?

**Comment by larshp** [comment]
or can the input be replaced with `zif_abapgit_repo` ? or out of scope for this change?

**Comment by mbtools** [comment]
yes, small steps. next PR:
- Replace `calculate( io_repo )` with `calculate( ii_repo type ref to zif_abapgit_repo )` and
- Move `zcl_abapgit_repo->status/mt_status/reset_status` to `zcl_abapgit_repo_status`

**Pull request merged**
