### PR TITLE
Fix links for edge browser control

### PR DESCRIPTION
**Pull request by christianguenter2**
Latest edge browser control handles links and other url parameters quirky.  Slashes (/) are cut out when send back to ABAP and therefore the links are corrupt. To mitigate this issue this change introduces a new concept called ~short~ url parameter repository where we store ~shortened/ ~encoded ~urls~ parameters (shortening happens via hash function). Instead of the origin urls we send the ~shortened~ encoded ones to the GUI. If the GUI invokes a link the ~short url~ encoded parameter is translated back to the origin ~url and called~ and further processed.

An ~short~ encoded url looks like this: 
SAPEVENT://s_a_p_e_v_e_n_t/url?url=C715004CBA979C4877FD1959C48BF267838C32A9
instead of
sapevent://s_a_p_e_v_e_n_t/url?url=https://github.com/sbcgua/abap_w3mi_poller.git

Other example:
before
sapevent://s_a_p_e_v_e_n_t/go_fill_diff?KEY=000000000110&PATH=%2fsrc%2f&FILENAME=zcl_test_root_class.clas.abap
after
sapevent://s_a_p_e_v_e_n_t/go_fill_diff?6BB30ACCB81E6D4BE0CE40972DBF73916E27D7EC

#6339

### CODE REVIEW

**Comment by fabianlupa** [comment]
Is this behavior documented somewhere? I wonder if this is a workaround for a bug or some kind of misused feature.

**Comment by mbtools** [comment]
I had compiled this https://github.com/abapGit/abapGit/issues/4661 before for reference. 

Did you try escaping the `/` to `%2f` in the parameter part?

**Comment by christianguenter2** [comment]
> Is this behavior documented somewhere? I wonder if this is a workaround for a bug or some kind of misused feature.

Not that I'm aware of

**Comment by christianguenter2** [comment]
> Did you try escaping the `/` to `%2f` in the parameter part?
Yes. I tried several escaping mechanisms. Without success. But maybe I missed the obvious.

**Comment by christianguenter2** [comment]
@mbtools issue also occurs with escaped links. See third task in #6339

**Comment by mbtools** [comment]
Is this really what we want? I see this as a SAP bug and rather not support Edge control until it's fixed.

**Comment by mbtools** [comment]
The expectation is certainly that no backend changes are necessary (to_upper/to_lower are already hacks we should not have needed). It is probably causing problems with standard SAP solutions or other customers, too. If there's no movement (no comments in the SAP notes), I can create a new case next week.

**Comment by christianguenter2** [comment]
Thx. Yeah, expecation vs. reality.

**Comment by christianguenter2** [comment]
Closing. Should be fixed by SAP.

**Pull request closed without merging**
