### PR TITLE
DRUL: Fix compatibility with lower releases

### PR DESCRIPTION
**Pull request by uenal-akkaya**
Handle of Dependency Rule object type system compatibility fixed. Usage of CL_DRUL_WB_OBJECT_DATA as data model when this class is available, if not then CL_BLUE_SOURCE_OBJECT_DATA can be used. In new releases the CL_DRUL_WB_OBJECT_DATA does not exist anymore which was refactored and replaced by CL_BLUE_SOURCE_OBJECT_DATA.

### CODE REVIEW

**Comment by larshp** [comment]
#5932

**Comment by uenal-akkaya** [comment]
Review: @marcushoepfner

**Review by marcushoepfner — APPROVED** [review]
LGTM

**Comment by mbtools** [comment]
Closes https://github.com/abapGit/abapGit/issues/5932

**Pull request merged**
