### PR TITLE
Dialogs: HTML form enhancements

### PR DESCRIPTION
**Pull request by mbtools**
- Minor increase of contrast for background, input- and readonly fields
- Add read-only option for columns of table control
- Better handling of newlines in textarea fields
- Remove field-groups from string-map 
- Add method to check for empty form
- Add method to initialize form schema

https://github.com/abapGit/abapGit/issues/4171

### CODE REVIEW

**Comment by larshp** [comment]
@sbcgua any thoughts regarding the `is_empty` method?

**Comment by mbtools** [comment]
Is_empty will be used to figure out if the user clicked “back” to come to the form (see the related issue).

**Comment by sbcgua** [comment]
well ... just thoughts
- I would say the class became too large, I would certainly split it at this stage: view and processings at least and probably separate table out
- `cmd_type` and `iv_is_main` probably can be merged - they are not consistent currently
- `init` looks strange - why is it needed ? why not creating a new instance ? I have a "global variable feeling" :)
- `is_empty` - is it for checking emptyness or unchangedness ? also look like a lot of code duplication with normalize, maybe there is a room for improvement. Or maybe the better way is to memorize initial value_map and compare to the further states

But just imho

**Comment by mbtools** [comment]
Good feedback. I removed `init`. 

`is_empty` is indeed checking if all form fields contain initial values (for example '0' for number fields). I will do more research, why the form data gets to this state when doing a "back" navigation (F3). 

Checking for "unchanged" (`is_dirty`) is another case which I currently implement in the page, but should go into a separate form processing class. 

Can we merge this and I will create a new PR for 
- splitting form definition and form processing (incl. `is_empty` and `is_dirty` #4265)
- combining `is_main` and `cmd_type`
since these changes will impact existing forms?

**Comment by larshp** [comment]
@sbcgua any additional comments? Can I merge this?

**Review by sbcgua — APPROVED** [review]
Let's merge. There is always room for improvement

**Pull request merged**
