### PR TITLE
more ui core decoupling

### PR DESCRIPTION
**Pull request by larshp**
decouple `ui/core/zcl_abapgit_gui_event` from `ZCL_ABAPGIT_HTML_ACTION_UTILS`, all methods moved to private section

https://abaplint.app/stats/abapGit/abapGit/package_coupling?folder=/src/ui/core

### CODE REVIEW

**Comment by larshp** [comment]
ui core factory?

**Comment by sbcgua** [comment]
from this perspective ZCL_ABAPGIT_HTML_ACTION_UTILS might be not needed at all

**Comment by larshp** [comment]
> from this perspective ZCL_ABAPGIT_HTML_ACTION_UTILS might be not needed at all

after this PR it contains application specific stuff, eg. encoding of db keys for the db pages, encode jumping etc

**Comment by larshp** [comment]
merging

**Pull request merged**
