### PR TITLE
fix: exclude Translation Object Detective language for MSAG objects

### PR DESCRIPTION
**Pull request by gregorwolf**
Excludes Translation Object Detective language from serialization
Provides a solution for object type MSAG in issue #5595

### CODE REVIEW

**Comment by flaiker** [comment]
This is quite an interesting feature. I scanned to documentation you linked and noticed in note 2087655 another technical language `2Q` is also mentioned and also excluded from logging. Should abapGit also exclude that language? Note 1943470 explains `2Q` as a technical language for "pseudo translations" to test internationalization features before translation occurs.

**Comment by gregorwolf** [comment]
Hi @flaiker,

thank you for your feedback. I think this language should also be excluded. I've also made setting the language more robust.

**Comment by flaiker** [comment]
Looking ahead a bit these languages would have to be excluded in other places as well, like mentioned here https://github.com/abapGit/abapGit/issues/5595#issuecomment-1139339620 . Some of these are not directly inside of the object handler but for example in `zcl_abapgit_longtexts` and `zcl_abapgit_lxe_texts` will likely want to exclude them as well.

Therefore I suggest moving the logic from the constructor of the object base class to `zcl_abapgit_environment`, maybe method `get_system_language_filter` which returns a range table of spras with `sign = 'E' option = 'EQ' low = '1Q' / '2Q'` depending on if they are installed using the conversion exit, possibly cached after first call. Then all the implementations could easily filter by

```abap
DATA(language_filter) = zcl_abapgit_factory=>get_environment( )->get_system_language_filter( ).
SELECT ...
  WHERE spras IN @language_filter
```

without requiring access to the object_super member variables or additional parameters.

**Comment by gregorwolf** [comment]
I've followed your suggestions. Looking forward for your feedback.

**Comment by flaiker** [comment]
Looks good to me. I checked if the range table should be cached because it is build on every call but since the underlying tables are buffered there's no noteworthy performance impact.

I don't have 1Q or 2Q installed either. So I cloned abapGit-tests/MSAG, translated it to German and excluded that for the test in get_system_language_filter. The diff then disappeared.

:+1:

**Review by flaiker — APPROVED** [review]

**Pull request merged**
