### PR TITLE
more TABL DDL serialization work

### PR DESCRIPTION
**Pull request by larshp**

### CODE REVIEW

**Comment by larshp** [comment]
small test program for testing custom serialization

```abap
DATA(lo_ddl) = NEW zcl_abapgit_object_tabl_ddl( ).
SELECT obj_name FROM tadir WHERE pgmid = 'R3TR' AND object = 'TABL' INTO TABLE @DATA(lt_tadir).
LOOP AT lt_tadir INTO DATA(ls_tadir).
  DATA(lv_custom) = lo_ddl->serialize( lo_ddl->read_data( ls_tadir-obj_name ) ).
  DATA(lv_adt) = lo_ddl->serialize_adt( ls_tadir-obj_name ).

  IF lv_custom = lv_adt.
    WRITE: / ls_tadir-obj_name, 'OK'.
  ELSE.
    WRITE: / ls_tadir-obj_name, 'ERROR'.
  ENDIF.
ENDLOOP.
```

**Comment by larshp** [comment]
thats it for now, still more work, but bored of it today

**Comment by mbtools** [comment]
Still works 👍 

image

**Review by mbtools — APPROVED** [review]

**Comment by larshp** [comment]
its not activated for now, just separate code

**Pull request merged**
