### PR TITLE
PROG: Store flow logic as separate ABAP files

### PR DESCRIPTION
**Pull request by mbtools**
Before, the screen flow logic was stored in encoded format as part of the XML file ([example](https://github.com/abapGit-tests/PROG_splitter/blob/b41889d35c8fb3c3c6bca2326a772da35dbaaa8a/src/zdemo_dynpro_splitter_control.prog.xml#L24-L62)).

abapGit can still deserialize the old format but serializes the flow logic of each screen in a separate ABAP file.

Test repo: https://github.com/abapGit-tests/PROG_dynp_flow

Example:

image

[image](https://github.com/abapGit-tests/PROG_dynp_flow/blob/main/src/zdemo_dynpro_splitter_control.prog.screen_0100.abap)

PS: It looks like GH is missing some of the syntax highlighting. I will get it fixed.

### CODE REVIEW

**Comment by pokrakam** [comment]
That was a desperately needed un-hack, thank you!

**Comment by sbcgua** [comment]
:+1:

**Comment by larshp** [comment]
before merging/at the time of merging suggest tagging a version/adding changelog

**Comment by mbtools** [comment]
sure. i will prep a version

**Comment by mbtools** [comment]
Syntax highlighting: https://github.com/pvl/abap.tmbundle/pull/105

**Comment by mbtools** [comment]
Closes #7049

**Pull request merged**
