### PR TITLE
Commit Page: Repo Header and Summary

### LINKED ISSUE #5079: Commit Page Update follow up [repo header missing]
After #5048 (which is a really nice and clear redesign, thanks Marc!) the repo header disappeared from the commit page. Which is a regression imho, because it is very inconvenient not to see which repo and page you are committing too. And it is easy to make a mistake after a short distraction. I'd propose to get the header back. Maybe with clickable branch like in stage page (to adjust the target branch). @mbtools 

image

P.S. Also, I'd say the summary leaves some room for improvement. The coloring is very similar to the main form and so it is not immediately visible where to enter commit comment, which also may change it's place. I think it should be redesigned a bit. I'll probably come with some suggestions separately. I think it should be closer to how it's done in diff page

image

### PR DESCRIPTION
**Pull request by mbtools**
- Added repo header back
- Changed summary as suggested by @sbcgua

Closes #5079

SAPgui_531

### CODE REVIEW

**Comment by sbcgua** [comment]
Looks nice :) A couple of comments:
1) That would be great to have clickable branch here. To be able to create a new branch. OR (better, though it is probably a separate PR) a new field at the bottom of the main form to create a branch and commit to it. The latter is in fact better because clickable branch can also result in switching to a wrong branch
2) The action (2nd col) at the bottom table looks ambiguous for me. It should be either this or that (and I'd say the first column is clear enough and consistent with the other pages)

**Comment by mbtools** [comment]
I see the commit as the final step, where you confirm what will actually happen. Switching things will confuse and the file statuses will be incorrect (we would have to refresh from remote and calc diff again).  Switching or creating branches should happen on the staging page. 

I will revert the color change on the details tab

**Review by sbcgua — APPROVED** [review]
Looks good for me. Much better with the top info bar :) Thanks

P.S. I separated change-branch discussion into an issue

**Comment by flaiker** [comment]
It took me a while to realize what the "Summary" and "Details" link do on the commit page.

image

They don't do when there's no scrollbar on the page so it took me a while to figure out what they are for. I have no idea for adjustment just wanted to mention it. I first thought something was supposed to expand.

**Comment by mbtools** [comment]
Yes, it depends on screen size. How about removing the link and replacing it with "(see details below)".

**Comment by flaiker** [comment]
I assume the link is quite useful when there are lots of files staged. I'm fine with it either way. It just took a moment to realize what is was for.

**Comment by sbcgua** [comment]
The layout is indeed imperfect. I had the same feeling when i saw it the first time as well. It should probably be collapsible block (so 1 step from the existing solution) ... however it would be java script ... so rather important block will become completely unavailable in java client. Which is a thing to consider.

**Pull request merged**
