### PR TITLE
Object type PDWS - Workflow Template

### PR DESCRIPTION
**Pull request by pokrakam**

### CODE REVIEW

**Comment by mbtools** [comment]
The code here is just a shell. I'm sure you can submit the full class when done. Can we close?

**Comment by pokrakam** [comment]
> The code here is just a shell. I'm sure you can submit the full class when done. Can we close?

Using a draft PR is intentional for purposes of visibility, at least that was the idea when discussed with @larshp. 

I know there's been little progress, had an unusually busy December and now we're in full lockdown so haven't had time to work on it further. But do plan to pick it up again in February. If there's a preference we can close the PR and reopen a new one when I resume.

**Comment by larshp** [comment]
well, I dont think we should have PRs open that are very old, but right now we have a PR that is older than this one 😁

**Comment by pokrakam** [comment]
Closing until I (or someone) picks this up again, we still have the branch for visibility.

**Pull request closed without merging**
