### PR TITLE
Remove obsolete screens on PROG deserialize

### PR DESCRIPTION
**Pull request by sbcgua**
Problem: a screen is removed in the original system. On deserialize to the target system this screen is not removed (even on force pull) and remains a diff
2021-10-29_22h01_29

Solution: force remove all found dynpros which are not deserialized.

**Needs review !**
- I have little understanding in deserialization, the solution is very straight forward, maybe I missed something
- ~~do I need to specify transport request param ? (commented now)~~ see [comment below](https://github.com/abapGit/abapGit/pull/5075#issuecomment-955028121)
- selection screens are removed on serialization. My code deletes them anyway ( = always). Is it OK? They seem to recreate automatically though ...
- ~~I didn't check it on new progs and inactive screens (will do tomorrow)~~ inactive screen successfully deleted
- ~~selection screen variants~~ successfully stay in place (thanks @mbtools for a good point)

### CODE REVIEW

**Comment by mbtools** [comment]
AG set a default transport. No need to add objects individually (unless the parameter is mandatory). 

Selection-screens are indeed auto-generated. However, we should check if the new logic drops associated variants which can been screen-specific.

**Comment by sbcgua** [comment]
All good points. Thanks !
So, did some extra testing with sel screens (works fine) and inactive screens.
Removed the commented stuff.
I think it is ready for review.

**Comment by sbcgua** [comment]
Yey, yey, what about merging this one ? :))) (it works on my systems :)
:dancer::dancer::dancer:

**Comment by mbtools** [comment]
just do a PP on `CALL FUNCTION 'RS_SCRP_DELETE'` 😋

**Comment by sbcgua** [comment]
> just do a PP on `CALL FUNCTION 'RS_SCRP_DELETE'` 😋

PP ?

**Comment by larshp** [comment]
pretty print, guessing regarding the indentation of the parameters in the function module call

**Comment by sbcgua** [comment]
Ah. meaning the `=` ? Ok, will do.

P.S. by the way, indenting assignments (`=`) is quite controversial subject. On the one hand, it is easier to read, no doubts. But on the other hand, it enforces you to readjust unchanged lines of code which pollute diffs. Which make code review more difficult. So very arguable topic in fact.

**Comment by sbcgua** [comment]
done

**Comment by larshp** [comment]
for a new issue: https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#align-parameters just need the rule in abaplint, and then refactor the code that triggers issues, https://github.com/abaplint/abaplint/issues/929

**Comment by mbtools** [comment]
> P.S. by the way, indenting assignments (`=`) is quite controversial subject. On the one hand, the result is easier to read, no doubts. But on the other hand, it enforces you to re-adjust unchanged lines of code which pollute diffs. Which make code review more difficult. So very arguable topic in fact.

Agree. Why does ABAP always have to be special? ;-)

**Review by mbtools — APPROVED** [review]
👍

**Pull request merged**
