### PR TITLE
Improvements in html engine

### PR DESCRIPTION
**Pull request by sbcgua**
to #5781

Just some by-the-way improvement. Refactoring the repo-over (next PR) I stumbled upon the `column` method - a wrapper for `td`. And I thought it was actually a good idea, and universal enough to be moved to the core engine, especially since there are a lot of tables in AG. So:

1. Added `td` and `th` methods as wrapper over text content or zif_html content (!). The latter allows skipping `render` in construction like `ri_html->add( zcl_chunks=>do_smth( )->render( ) )` - which is unreadable, sorry, and also produced unaligned htmls.

2022-10-01_19h42_45

So:

```abap
ri_html->td( '<span>Hello</span>' )
ri_html->td( ii_content = zcl_chunks=>do_smth( ) ) " No render() needed
ri_html->td( 
  iv_content = '<span>Hello</span>'
  iv_id    = 'id'
  iv_class = 'some_style' 
  iv_hint  = 'press this to ...' ) " For extra control

```

2. A universal `wrap` method (as the basis of td/th) which can do the same for any tag (just in case ... I'd not overuse it ....... maybe even make it private ........ because it's readability actually suck compared to dedicated `td` and `th`)
3. Chaining for `add`, and some others.
4. `new` - static constructor. I know it was there before and then removed for some reason. Please leave it, it is so convenient ! (having that there is no `new` operator)

### CODE REVIEW

**Comment by sbcgua** [comment]
... not sure what's wrong with the unit tests part ...

**Comment by mbtools** [comment]
Looks like the transpiler misinterprets your c_lf constant. Try using the abap class constant instead

**Comment by mbtools** [comment]
Good improvements. TD,th will be useful

**Comment by sbcgua** [comment]
> Looks like the transpiler misinterprets your c_lf constant. Try using the abap class constant instead

Hmm, that was the point of `c_lf` ... to make it more readable ... maybe this is a bug of transpiler ?

**Comment by mbtools** [comment]
Now act is almost the same as exp:

```html
  actual: String {
    value: '<td></td>\n' +
      '<td>\n' +
      '  Hello\n' +
      '</td>\n' +
      '<td id="id" class="class" title="hint">\n' +
      'Hello\n' +
      '</td>',
    qualifiedName: 'STRING'
  },
  expected: String {
    value: '<td></td>\n' +
      '<td>\n' +
      '  Hello\n' +
      '</td>\n' +
      '<td id="id" class="class" title="hint">\n' +
      '  Hello\n' +
      '</td>',
    qualifiedName: 'STRING'
  },
`

the second `hello` is not indented properly.

**Comment by mbtools** [comment]
It used to be `create` instead of `new` (and that's what we also use in other classes). Do you mind changing it?

@larshp The unit tests run fine in the https://transpiler.abaplint.org/ playground (with correct indent):
[testcase.txt](https://github.com/abapGit/abapGit/files/9699002/testcase.txt)

Might be related to one of the magic transpiler kernel calls

**Comment by mbtools** [comment]
`new` makes sense for 7.4 or higher, but AG is 7.02. For me, it's about consistency so I can use my brain less:

`ZCL_ABAPGIT_HTML_FORM_UTILS=>CREATE`
`ZCL_ABAPGIT_HTML_FORM=>CREATE`
`ZCL_ABAPGIT_HTML=>?`  😉

**Comment by mbtools** [comment]
Regarding unit test: https://github.com/abaplint/transpiler/issues/891

**Comment by sbcgua** [comment]
> `ZCL_ABAPGIT_HTML_FORM_UTILS=>CREATE`  
`ZCL_ABAPGIT_HTML_FORM=>CREATE`  
`ZCL_ABAPGIT_HTML=>?` 😉

Hmmm, :innocent:, change forms and form utils to `new` ? It's code readability improvement !

OK, not that principal standpoint, I'll change to `create`, no worries

**Review by mbtools — APPROVED** [review]
👍

**Pull request merged**
