### PR TITLE
Adjust name prefix for types

### PR DESCRIPTION
**Pull request by mbtools**
https://github.com/abapGit/abapGit/issues/3398

### CODE REVIEW

**Comment by mbtools** [comment]
Done! New rule will be active with this PR

**Comment by flaiker** [comment]
Some of these types are public making them relevant for possible external usages. Do we need to check other repositories or inform about a change in the API?

**Comment by larshp** [comment]
merging, and then when https://abaplint.app/stats updates its possible to look through those with "custom config"

**Comment by larshp** [comment]
tested ok, no syntax errors

**Comment by sbcgua** [comment]
a minor concern about table type prefixes. It was quite convenient to see `tt` or `tty` to identify a table type. Of course, it also depends on plural names. `tt_thing` -> `ty_things`. But ... if prefix does not add anything then why it is needed at all ? Just imho. Though the work done for unification is very good :+1:.

**Comment by larshp** [comment]
it adds to static analysis via abaplint, having a convention then it knows if to issue an error,
 
image

**Comment by mbtools** [comment]
@flaiker I had tested abaplint-sci and abapGit-ci repos but none of the changed types were used there. of course, we don't control how other tools might use parts of abapGit.

@sbcgua I wasn't sure what's better, plural or some suffix for the table types. I tried to stick with the kind already used by the class/interface. Also didn't want to change existing types unless there was a conflict. 

Anyway, chapter closed. :-)

**Pull request merged**
