### PR TITLE
Refactor status calculation

### LINKED ISSUE #4620: Missing nice error on similar (duplicate ?) packages
1. AbapGit won't open the repository (repo management screen)
2. Dump on the following line https://github.com/abapGit/abapGit/blob/17eac7b6c37eb583544f494ed23a4e750ebd7a5d/src/objects/core/zcl_abapgit_file_status.clas.abap#L296
3. Debugging showed that package.devc.xml was present twice in local (on the same path)
4. Error occurred after sha1 was found for first package.dev.xml it is cleared (next line), then couldn't lookup sha1 for second package.devc.xml (which seems correct)
5. Root cause was two packages with similar name only difference was a single underscore in the name. After removing one of the package problem went away.

I'm not in the situation to further analyze this bug. Might have been related to a messy situation with transport requests.

### PR DESCRIPTION
**Pull request by mbtools**
Split `zcl_abapgit_file_status->calculate_status` into smaller methods

### CODE REVIEW

**Comment by mbtools** [comment]
adding 1 if made the method too long... had to split `calculate_status` into smaller parts

**Comment by larshp** [comment]
plus this PR refactors the code

I'm not really sure what the exact problem in #4620 is, so I'm not sure how/if this PR solves it

**Comment by mbtools** [comment]
I change this one to be refactor only. No functional changes.

**Comment by larshp** [comment]
👍 merging

**Pull request merged**
