### PR TITLE
APACK manifest not refreshed after class update

### LINKED ISSUE #5284: new APACK version considered only by restarting abapGit
Steps to reproduce:
- Start abapGit, open your repository having an existing APACK class
- Using your favorite ABAP editor, edit the APACK class and change the version
- In abapGit, in your repository, click "Refresh"
- You can see that `.apack-manifest.xml` has not been recalculated, it doesn't contain the new version defined in the APACK class

Workaround: restart abapGit before clicking "Refresh".

Request: is it possible to not restart abapGit, by executing the APACK class in an RFC session so that to always consider the latest APACK class?

### PR DESCRIPTION
**Pull request by sandraros**
Fix #5284

### CODE REVIEW

**Comment by mbtools** [comment]
Hi @sandraros, function modules don't work with the standalone version (since #4814). Closing

**Comment by mbtools** [comment]
Hi @sandraros, function modules don't work with the standalone version (since #4814). 

PS: APACK is a dying feature... I'm getting serious replacing it with the real deal.

**Comment by sandraros** [comment]
So, I guess we won't have the possibility anymore to show the latest modifications of any repository in `ZABAPGIT` (except the ones of abapGit itself), Is there a workaround that is used by other abapGit projects? (like users can simply display the diff of `changelog.txt`)

**Comment by mbtools** [comment]
APACK is there and can be used. Any replacement will allow for the same features (and more).

**Comment by sandraros** [comment]
Issue closed and PR abandoned.

**Pull request closed without merging**
