### PR TITLE
Add exposure to workflow class attributes

### LINKED ISSUE #5449: CLAS: Deserialize fails for workflow attributes
Test https://github.com/abapGit-tests/CLAS_wf fails

image

image

Attributes are save first in `zcl_abapgit_oo_class->create`. However, it looks like they are overwritten by `deserialize_source`.

### PR DESCRIPTION
**Pull request by flaiker**
Fixes #5449

@mbtools Can you check with https://github.com/abapGit-tests/CLAS_wf/pull/1 ? (After uninstall / deletion of the class)

### CODE REVIEW

**Comment by mbtools** [comment]
the attributes are still missing after pull:

image

i think `deserialize_source` is still overwriting these wf attributes (since they are not part of the source)

**Comment by flaiker** [comment]
Works on my machine.

**Comment by flaiker** [comment]
Maybe there is some caching involved that causes this to work for me? That would also explain how the initial implementation got merged in the first place (though the move to deserialize to active might have very well broken it too).

**Comment by flaiker** [comment]
I'll try a different approach that works for both update and create.

**Comment by flaiker** [comment]
Huh, how bizarre. Here also is the 754 docker image:

https://user-images.githubusercontent.com/5270359/171159801-89e720d9-7ee5-4fcc-a5ad-ee52d953c37b.mp4

**Comment by mbtools** [comment]
sorry, user error. i update dev version but ran the test on the standalone 👎 

it did work on 754

**Comment by flaiker** [comment]
Ah no problem, at least I have some sanity back then.

I also tried the update scenario (deleted `MV_PRIVATE_WF_KEY` and restored using pull) which seems to somehow magically work as well. There is a lot of buffering involved so I am not sure every case is covered. Until then I'll just reopen.

**Review by mbtools — APPROVED** [review]
👍

**Pull request merged**
