### PR TITLE
basic FUGS serialization

### PR DESCRIPTION
**Pull request by larshp**
https://github.com/abapGit/abapGit/issues/2851

deserialization not supported, got no way to test it

### CODE REVIEW

**Comment by mbtools** [comment]
Do FUGS still exist?

**Comment by mbtools** [comment]
Oh, I see, you mean the SAP FUGS from the 1990s that someone wants to archive in git 😀

**Review by mbtools — APPROVED** [review]

**Comment by larshp** [comment]
> Oh, I see, you mean the SAP FUGS from the 1990s that someone wants to archive in git 😀

yea, those 😁

**Comment by mbtools** [comment]
I modified my system to create a FUGS: https://github.com/abapGit-tests/FUGS

It's the same as FUGR but the includes need a bit of special handling since inactive version is not allowed. 

Looks like deserialize and delete work fine now.

**Pull request merged**
