### PR TITLE
INTF: Refactor to fix "permission error"

### LINKED ISSUE #4672: INTF: Permission error during deserialize
When deserializing namespaced interfaces in lower releases (at least 7.02, 7.30, 7.31), you get "permission error":

image

The issue was fixed in https://github.com/abapGit/abapGit/pull/969 (https://github.com/abapGit/abapGit/issues/900, https://github.com/abapGit/abapGit/issues/968). However, the fix is limited to newer releases that contain the `modification_mode_enabled` option for settings. There is no workaround for this setting using the current INTF deserializer (I tried hard). 

Other issue with INTF deserializer:
- implemented in `zcl_abapgit_oo_base` instead of `zcl_abapgit_oo_interface`
- uses two variants `deserialize_abap_source_new` and `deserialize_abap_source_old` (neither work for above)
- since `modification_mode_enabled` isn't available in 731, it falls back to the old variant although the new variant would work (except for the issue mentioned above)
https://github.com/abapGit/abapGit/blob/main/src/objects/oo/zcl_abapgit_oo_base.clas.abap#L173
- in case of syntax errors, the inactive code is not accessible (similar to the PROG issue that was fixed recently)

Solution: 

Change implementation to mirror approach for CLAS

### PR DESCRIPTION
**Pull request by mbtools**
Implements interface deserializer the same way as the class deserializer.

- Works with all releases (7.02 or higher)
- Fixes "permission error" 
- Removes "new", "old" deserializer code

Closes #4672

### CODE REVIEW

**Comment by larshp** [comment]
did you test this on 702?

**Comment by mbtools** [comment]
yes. works with 702. 

while testing, i discovered an unrelated issue with `exists` check for INTF which I will fix in separate PR

**Comment by larshp** [comment]
ZCL_ABAPGIT_OO_BASE is starting to look more and more suspicious, but lets keep it as is this time around, one change at a time, this code is important

**Comment by larshp** [comment]
I installed code-pal without problems using this branch

**Comment by larshp** [comment]
I'll do a release at the same time as merging this one

**Comment by larshp** [comment]
👍 planning to merge this tomorrow

**Comment by larshp** [comment]
waiting until ~sunday, #dontShipOnFriday

**Pull request merged**
