### PR TITLE
Integrate repo interface into online repo interface

### PR DESCRIPTION
**Pull request by ConjuringCoffee**
Fixes https://github.com/abapGit/abapGit/issues/6893

### CODE REVIEW

**Comment by larshp** [comment]
since this doesnt have syntax errors, it means the code already implements the interface, which means the interface is now declared in two places in the hierarchy?

**Comment by larshp** [comment]
we would like to refactor the repo classes, and this might be the correct place for the interface

however, I think this PR adds to the amount of work required when refactoring the repo classes

can the classes and/or interfaces be refactored to have less hierarchy?

**Comment by ConjuringCoffee** [comment]
To be honest, I currently don't have the deep knowledge about these classes to perform such a refactoring. If my suggestion adds to the amount of work of the planned refactoring, then feel free to close the pull request for now. 😉

**Comment by larshp** [comment]
Lets see what Marc's opinion is

theres a lot of code in the repos, too much, and it needs a plan overall

**Review by mbtools — APPROVED** [review]

**Comment by larshp** [comment]
https://github.com/abaplint/deps/pull/237 merged

**Pull request merged**
