### PR TITLE
Serialization binary files in WAPA object

### PR DESCRIPTION
**Pull request by jrodriguez-rc**
Fix for issue #5681

### CODE REVIEW

**Comment by mbtools** [comment]
We replaced all of `cl_bcs_convert` before (https://github.com/abapGit/abapGit/pull/4605, https://github.com/abapGit/abapGit/pull/4693, This would bring it back...

Maybe add a `bintab_to_xstring` method to `zcl_abapgit_convert` without using bcs.

**Review by larshp — CHANGES_REQUESTED** [review]
try removing use of `cl_bcs_convert`

**Comment by jrodriguez-rc** [comment]
I'm still working on it, the bcs classes are replaced but the serialized file generated is not valid.
I can't open it downloading from GitHub and the size is 10x

**Comment by jrodriguez-rc** [comment]
I avoid using BCS classes and SOLI[X] types.

The serialization seems to work, but I need help to test the deserialization, I cannot uninstall the application which I tested the serialization because it is under development by a colleage

**Comment by mbtools** [comment]
This needs BAS to reproduce and test but my BAS isn't working 😦

**Pull request closed without merging**
