### PR TITLE
Update unit tests to use CI

### PR DESCRIPTION
**Pull request by pokrakam**

### CODE REVIEW

**Comment by mbtools** [comment]
the call is just 
```abap
  METHOD run_ci.
    zcl_abapgit_objects_ci_tests=>run( 'PDTS' ).
  ENDMETHOD.
```

and your exits should be
```abap
  METHOD zif_abapgit_exit~get_ci_tests.

    CLEAR ct_ci_repos. " if you don't want to run https://github.com/abapGit-tests/PDTS

    CASE iv_object.
      WHEN 'PDTS'.
        INSERT VALUE #(
          name      = 'PDTS'
          clone_url = 'http://vhcalnplci:8000/sap/zabapgitserver/git/PDTS.git' )
          INTO TABLE ct_ci_repos.
    ENDCASE.

  ENDMETHOD.
```

**Comment by pokrakam** [comment]
I understood the exit is to specify additional tests. Let me look at this more closely, if this is the case then the CI change is not needed.

**Comment by mbtools** [comment]
Just a minor change: `assert_true` does not exist in 702
https://github.com/abapGit/abapGit/blob/0562ce5683d188d4d8a4fc81756a3fbb707a2658/src/objects/zcl_abapgit_object_pdts.clas.testclasses.abap#L68
Please replace with `assert_equal`

**Comment by pokrakam** [comment]
Was not aware of assert_true in 7.02, neither was the linter by the looks of it :)
Updated tests, all good to go.

**Review by mbtools — APPROVED** [review]
👍

**Comment by mbtools** [comment]
checking dependencies outside the repo is not in scope for abaplint. you would need a list of all class and function signatures for all releases to catch something list this ;-). I'm planning to setup CI in my 702 to run regularly but I'm not sure when I will find the time for it.

**Comment by larshp** [comment]
thanks 👍

**Pull request merged**
