### PR TITLE
DEVC: Remove obsolete TADIR entries during uninstall

### PR DESCRIPTION
**Pull request by mbtools**
In case a package is local (ie no transports), abapGit will now check if objects still exist in the package. In case an object does not exist anymore, the corresponding TADIR entry will be removed. This allows empty local packages to be uninstalled automatically.

### CODE REVIEW

**Comment by larshp** [comment]
hmm, this seems like a workaround?

it is the responsibility of the object handler to clean up properly

**Comment by mbtools** [comment]
hmm is it? because several defer cleaning up `tadir` to the framework by setting `delete_tadir`. So we might as well move this to the framework for all object types (and get rid of the `delete_tadir` flag). 

PS: Similarly, I think 'zcl_abapgit_objects' should take care of `insert_tadir` when objects are deserialized.

**Comment by larshp** [comment]
yea, I guess there will always be some cases, where the object handler does not clean it up properly, eg via dumps or exceptions

**Comment by larshp** [comment]
note that some of the APIs handle TADIR and some does not, so if its moved it should check if things are okay first

**Pull request merged**
