### PR TITLE
fixing short dump

### PR DESCRIPTION
**Pull request by lucasborin**
image

image

### CODE REVIEW

**Comment by larshp** [comment]
hmm, where exactly does the dump occur?

we have spent quite a lot of time removing the aliases, https://github.com/abapGit/abapGit/pulls?q=is%3Apr+remove+alias+is%3Aclosed

**Comment by lucasborin** [comment]
> hmm, where exactly does the dump occur?

image

**Comment by larshp** [comment]
heh, did not think it was in use, anyhow, thats a fix to https://github.com/abapGit/abapGit-Plugins

**Review by larshp — CHANGES_REQUESTED** [review]
see above ^

**Comment by lucasborin** [comment]
Oh, I see. It is deprecated. Let me remove it from the system.

**Pull request closed without merging**
