### PR TITLE
SSFO: Fix order of T_CAPTION data

### LINKED ISSUE #6530: SSFO: BG Job commits unchanged objects randomly
Hi. 
I'm having this situation where my nighly job commits strange things that haven't been touched since years. 
it only happens to (some, but the same) SSFO objects and it looks like that:
image

first analysis looks like the language selection is unsorted.
it starts in FB: ```SSF_READ_FORM``` line 45 /59 where all texts are read into ```t_objt```. 
image

and follows in FB ```SSF_READ_OBJ_TEXT``` where it is returned to whoever wants the available texts.

It seems to be only occurring on big forms combined with lots of supported languages, our ```t_objt``` has more than 10.000 entries, so I assume it is natural that the order of all those is not identically when not explicitly requested ). 

I remember that we had to do some work back when we migrated to HANA and manually added the sort command to all DB selects that were not sorted yet, as HANA does not sort by default. I assume SAP should have done that as well. 

Now.. what would you recommend..
Is that a fix that would implemented in your ```ZCL_ABAPGIT_OBJECT_SSFO``` 
or 
should we try SAP changing the FBs, adding a sort
or
do you have another approach to this?

Thanks
PhiL

### PR DESCRIPTION
**Pull request by mbtools**
There's probably a more elegant way but this does the trick

Closes #6530

### CODE REVIEW

**Comment by mbtools** [comment]
can be tested with https://github.com/abapGit-tests/SSFO, branch `issue_6530` which has the incorrect order

**Comment by openPhiL** [comment]
Thank you very much. I am currently sick and will not be able to make proper test for at least 2 weeks, maybe a coworker will help.

**Comment by mbtools** [comment]
get welll, soon!

**Review by larshp — APPROVED** [review]
lets just try merging this

**Pull request merged**
