### PR TITLE
Extend logic to detect BCP47 languages

### PR DESCRIPTION
**Pull request by albertmink**
Now, the logic can understand BCP47 languages.

After: #6978 
Ref #6980

### CODE REVIEW

**Comment by larshp** [comment]
in https://github.com/abapGit/abapGit/blob/main/src/objects/core/zcl_abapgit_objects_files.clas.testclasses.abap#L57 the language "cz" is not valid, try changing it to "cs"

**Comment by larshp** [comment]
also fails in system, 
image

**Comment by albertmink** [comment]
Need help.
From my understanding the error is in `zcl_abapgit_convert=>language_bcp47_to_sap1`. However, afaik the unit test in the PR calls the METH with 'en' and 'de'. Both are already covered by unit tests of the `zcl_abapgit_convert`, so why does it fail here? What am I missing?
Screenshot 2024-07-16 at 09 59 17

**Comment by larshp** [comment]
is all unit tests running okay in a real system? then I'll have a look at open-abap

**Comment by albertmink** [comment]
Yes indeed.

**Comment by larshp** [comment]
I still get these errors when running on https://hub.docker.com/r/sapse/abap-cloud-developer-trial, 

image

**Comment by larshp** [comment]
try changing "cz" to "cs", https://github.com/abapGit/abapGit/pull/6986#issuecomment-2227297986

image

**Review by larshp — APPROVED** [review]
lets go

**Comment by albertmink** [comment]
Wait, I'd like to add a meaningful UT. Maybe this works also ABAP standalone ;)

**Pull request merged**
