### PR TITLE
parsing git branch list, throw errors

### LINKED ISSUE #4523: Bitbucket connection issue
Hello,

I am using an enterprise Bitbucket account to manage my repos.
Today when trying to connect to Bitbucket from abapGit, user credentials are prompted, but..

image

What?? OK..let's switch branches:

image

Humm..OK, let's deep dive (using callstack from the error message, an amazing feature!!)

image

Breakpoint at ZIF_ABAPGIT_POPUPS~BRANCH_LIST_POPUP from class ZCL_ABAPGIT_POPUPS, let's see what are the branches for my repo after the following line is exectuded:

`lo_branches    = zcl_abapgit_git_transport=>branches( iv_url ).`

And the result is:

image

Oh, something went wrong with the authentication...let me connect to bitbucket via the web client:

image

and ensure _I am not a Robot.... OK. Done! I'm in. 
Let's try again abapGit:

image

Success!
So it seems like abapGit is not managing well this specific case. 
Does anyone had this case already?

Thanks
S

### PR DESCRIPTION
**Pull request by larshp**
closes #4523

### CODE REVIEW

**Comment by larshp** [comment]
@Sdfraga can you help testing this change?

**Comment by Sdfraga** [comment]
NOK.

image

**Comment by larshp** [comment]
@Sdfraga thanks, try again

**Comment by Sdfraga** [comment]
Success!

image

Should't the message clearly state to login in the git provider platform or you do you think CAPTCHA it's self-explanatory..?

**Comment by larshp** [comment]
I'd like to avoid showing the very long message, currently this is the ERR sent by the git server, think its enough to figure out what is wrong

**Pull request merged**
