### PR TITLE
UI: Clear progress bar

### LINKED ISSUE #3505: Leftover messages in progress bar
After pull, it's possible that some message stays in progress bar (for example from mass activation process):

image

> Clear progress bar or replace with proper status (success/error) msg

### PR DESCRIPTION
**Pull request by mbtools**
Clears status/progress bar at end of longer processes and removes leftover messages. 

Closes #3505

### CODE REVIEW

**Comment by larshp** [comment]
Is this neede? I think normally also MESSAGEs remain visible until the next message is issued?

**Review by larshp — CHANGES_REQUESTED** [review]
comments above

**Comment by mbtools** [comment]
the messages are pretty random depending on what happens during a process like deserializing. Often there's no way of telling which object they belong to or understand why the message was put out. just confusing. any relevant message/issues will/should be in the log.

**Comment by larshp** [comment]
I think its expected behavior, anyhow...

**Review by larshp — APPROVED** [review]

**Pull request merged**
