### PR TITLE
Improve package / sub-package check

### LINKED ISSUE #5623: Exception when package is in repo but not a subpackage in system
@Zeatynis "I have a situation when I decided I want to unjoin one subpackage of a central repository package. I don't want to serialize it anymore. So I changed this subpackage assignment and now I am stuck. I cannot stage to repo.

I have this error:
Package ZREPO_XML_WS already exists but is not a subpackage of ZREPO. Check your package and folder logic or assign ZREPO_XML_WS to package hierarchy of ZREPO to match the...

But when I jumped for this package to clear ls_item-devclass abpagit reacted correctly. It recognized every object from this package as removed and when I stage I have an option to remove these objects from my repo.
obraz

_Originally posted by @Zeatynis in https://github.com/abapGit/abapGit/issues/4904#issuecomment-1147780623_

### PR DESCRIPTION
**Pull request by mbtools**
If a sub-package is removed from the package hierarchy, instead of an exception, abapGit now shows a detailed warning message in the log.

This allows to remedy the situation either by adding the sub-package to the package hierarchy or by removing the sub-package from the repository (via push).

Closes #5623

Before:

image

After:

image

### CODE REVIEW

**Comment by larshp** [comment]
is it possible to add a unit test for this scenario?

**Comment by CiozZ** [comment]
Happy to see that there is a solution! Can't wait for the merge 👍 
Thanks!

**Comment by CiozZ** [comment]
Looks good for me now. Thanks you! 

image

**Comment by larshp** [comment]
@CiozZ thanks, merging

**Pull request merged**
