### PR TITLE
User specific abapGit settings

### PR DESCRIPTION
**Pull request by christianguenter2**
#1316 

Rearrange the settings page. There are now two separated sections "Global settings" and "User specific settings"

image

User specific settings are stored in the user specific config.
image

And removed from gloabl storage.
image

There's also a migration mechanism, migrating existing list size and ADT jump settings to personnel settings of all abapGit users.

### CODE REVIEW

**Comment by larshp** [comment]
code looks good, I'll test it sometime during the weekend

**Comment by larshp** [comment]
sorry, I have not had much time, does anyone else have time to do a short test?

**Comment by larshp** [comment]
Hi,
In case there are no global settings, ie. the default are always used, abapGit cannot be started after applying the change,
image
image

**Comment by christianguenter2** [comment]
fixed

**Pull request merged**
