### PR TITLE
Add exit for integration of unit test with CI

### PR DESCRIPTION
**Pull request by mbtools**
Goal:

Run CI tests within the unit test of an object type class. The setup of a test class should be minimal. As a default, the unit test should not perform tests. However, it shall be possible to enable CI tests locally. It shall also be possible for a developer to specify which test repos should be included in the test (from https://github.com/abapGit-tests or from their own repos).

Solution:

This PR provides a new global test class that can be called from a unit test in an object serializer. The global test class will use the abapGit test repos for the corresponding object type (https://github.com/abapGit-tests/{type}) and run the abapGit CI test process (https://github.com/abapGit/CI).

There's also an exit to define additional test repos. 

Requirements:

- Installation of https://github.com/abapGit/CI
- Enable critical unit tests in settings

Instructions:

Add the following to the test class of your object type - for example, zcl_abapgit_object_tabl. Side note: This should be mandatory for all object serializers since we require a test repo anyway.

```abap
CLASS ltcl_ci DEFINITION FOR TESTING RISK LEVEL CRITICAL DURATION MEDIUM.
  PUBLIC SECTION.
    METHODS run FOR TESTING.
ENDCLASS.

CLASS ltcl_ci IMPLEMENTATION.
  METHOD run.
    zcl_abapgit_objects_ci_tests=>run( 'TABL' ).
  ENDMETHOD.
ENDCLASS.
```

Example Exit (optional):

```abap
  METHOD zif_abapgit_exit~get_ci_tests.

    " Return the name of repos and their clone URL
    " The name is used to define the package "$___<name>" linked to the abapGit repo

    " If you don't want to use the default https://github.com/abapGit-tests/{type} repo, clear the list
*    CLEAR ct_ci_repos.

    " Other Examples:
    CASE iv_object.
      WHEN 'TABL'.
         " Add some other repo from https://github.com/abapGit-tests
        INSERT VALUE #(
          name      = 'TABL_foreign_key'
          clone_url = 'https://github.com/abapGit-tests/TABL_foreign_key' )
          INTO TABLE ct_ci_repos.

        " Add your own repo works as well
*        INSERT VALUE #(
*          name      = 'MYTEST'
*          clone_url = 'https://github.com/mbtools/abapGit-test-del' )
*          INTO TABLE ct_ci_repos.
    ENDCASE.

  ENDMETHOD.
```

Closes https://github.com/abapGit/abapGit/issues/3776

### CODE REVIEW

**Comment by larshp** [comment]
hmm, I'm not really sure about this

To me it seems like more work to implement the exit than running the report

**Comment by mbtools** [comment]
running the complete end-2-end process with ctrl+shift+f10 is very helpful when implementing or changing the serializer class. 

the exit is optional and only necessary if you want to run other or different test than the default abapGit-test/{type}

**Comment by larshp** [comment]
yea

before @pokrakam 's PR, we had one way of testing, its my impression that Mike will not be using the approach in this PR because its too slow, I'll also not be using the approach in this PR, so that ends up with three different approaches

**Comment by larshp** [comment]
@pokrakam does this help you? will you be refactoring to use this approach?

**Comment by pokrakam** [comment]
My first thought is that having a way to integrate CI tests into Unit Testing is definitely a good step forward, but it would be nice to have a locally cached repo (which is why my dodgy hack was to paste it into the mock class). However I need to have a little play with it to see how it performs, it might be good enough or it might be a good start. It'll be good either way if it works :-)

**Comment by pokrakam** [comment]
OK, so I had a go and in some ways it performed better than expected, but in other ways I think the experience is not how I would like to work. It took between 3-7 seconds to run the test. Repeated executions tended to be in 3-4s. Not brilliant, but tolerable. OK for when I'm diving in to do a 10 minute patch, but wouldn't want to spend hours working like that. 

I realised one other thing while trying this out: What I found useful while I was doing the development of a new Object Type was to edit the XML along with the code. For me it was very much an iterative process: changing the XML to get the desired object configuration, then changing the serialisation to get the desired XML and so on. This worked very well. I can edit the XML on GitHub, but it's a bit cumbersome. This is obviously only relevant when doing major work on object serialisers.

One more point to consider, is that the GitHub Test Repos are likely to contain a real object created and serialised by a developer, whereas my Unit Test would create an object with an name chosen to ensure it can't conflict with anything on the system, and it also failed if the object existed (e.g. previous test didn't teardown). The CI run however will overwrite an existing object. This has a small potential for conflict on a customer system. I have duly gone and changed my test-PDTS repo to use a more fictitious ID.

**Comment by mbtools** [comment]
It's the nature of the deserializer that it will create and persist new objects. Even in your test class with hardcoded XML, there's a chance that things go wrong when updating the DB or when testing the deletion of an object (even with fictitious ids). Therefore, we should not ship such test classes and keep these things in abapGit/CI. 

The proposed solution would do nothing at customers since they do not have CI installed and probably won't even have the dev version anyway. I think it's a nice way to prove that we have a working e2e test case. 

No worry, I don't want to add unnecessary code to AG. I will keep `zcl_abapgit_objects_ci_tests` on my own machine for dev/ut purposes. No need to put it into AG.

**Comment by pokrakam** [comment]
No, I think it would be a useful addition to AG, I would integrate it into the PD* objects.

I understand that any deserialisation tests will create objects. If the test objects are named things like Z*ABAPGIT_TEST then there's little chance of breaking any productive customer objects. But in some cases, such as HR Objects, the names are assigned by SAP. 

In the case of PDTS I have a 1% chance of overwriting a customer object, so I made provision for that in my test. But CI will happily overwrite existing objects (which I've now catered for too). I don't know if there are such scenarios among the other 150+ abapGit_test repos, hence I thought it's a point worth discussing as perhaps others may have experience to add.

**Comment by larshp** [comment]
@sbcgua any thoughts?

**Comment by sbcgua** [comment]
I'm a bit far from the subject and serializer development (so I don't feel those pains ... ). I think that having a possibility run e2e tests **easily** it good. 

But personally I think this solution is too hacky. Hardcoding ci repo urls. installing and deinstalling something from web within a unit test ... I think there may be some undiscovered issues. Also, trying to remember how e2e tests are organized in other projects I've seen, I remember they are often separated and run by a separate command/context. I personally would also keep them separate.

Just imho. I'm not too much in the subject as I told.

**Comment by larshp** [comment]
I'm also much in doubt, earlier we had manual testing and CI testing. Now we also have the PDTS approach, plus possibly this one

**Comment by mbtools** [comment]
Agree. How about we ship the global test class with ababGit/CI and have it take a repo URL as input? If a developer wants to run the UT, they can add the local test class to the object serializer as described above. It would be only temporary during development and local testing and should not be committed to abapGit itself.

**Comment by larshp** [comment]
yea, we can put anything into `ababGit/CI`

**Comment by pokrakam** [comment]
I definitely value the idea of having something runnable inside my code without having to jump to another tool/report to do so. I also agree that e2e tests are normally outside, but there is a lot of grey area between unit and integration testing. Some things in ABAP are not easily mockable, one is often dependent on the mockability (I think this is a made-up word) of dependent objects. For example, Gateway's `/IWBEP/CL_MGW_REQUEST` is highly resistant to mocking. De/serialization falls into this category too and is not otherwise unit-testable.

**Comment by pokrakam** [comment]
Thinking about it, I see a danger in moving a possible dependency into `abapGit-CI` that someone may use it and forget to remove it from their abapGit code. I don't trust myself to always remove something "temporary during development". @mbtools has gone to some length to make this this dependency conditional through dynamic calls, so it's IMO less dangerous to leave in abapGit as long as it doesn't crash if AG-CI is not installed.

**Comment by larshp** [comment]
lets try it 🤷‍♂️

**Pull request merged**
