### PR TITLE
Issue #4027: Resolve possible crash of AG and add option to be able to suppress showing commit hash on Code Inspector result page

### LINKED ISSUE #4027: abapGit asks for authentication to perform a check
Hello,

when you are on the repository overview page (main page) and click on action 'Check', abapGit asks you for your authentication data for your Git repository/server. You can type in any information and it will still do the ATC check. Afterwards you can press the 'Stage' button and it will ask you for your credentials again. Providing wrong or no information by cancelling the dialog does crash abapGit with an error regarding that dynpro `ZABAPGIT 1001` wasn't called via `CALL SELECTION-SCREEN`.

My suggestion:

1. Remove the authentication check before the ATC check as it's not needed for that task and
2. Make sure that abapGit won't crash in both cases.

Happens with abapGit v1.100.0.

Best Regards,

### PR DESCRIPTION
**Pull request by mariusraht2**
Resolves #4027 

**Change Log:**
- `ZABAPGIT_FORMS`: Replace `LEAVE TO SCREEN` with `CALL SELECTION-SCREEN` to suppress crash if cancel was clicked in login dialog
- `ZCL_ABAPGIT_GUI_CHUNK_LIB`: Added option `iv_show_commit` to `render_repo_top` to be able to suppress getting commit hash from remote and therefore asking for credentials if we just want to see Code Inspector check results

### CODE REVIEW

**Comment by mbtools** [comment]
let's add `iv_show_commit = abap_false` to `ZCL_ABAPGIT_GUI_PAGE_REPO_SETT` and `ZCL_ABAPGIT_GUI_PAGE_SYNTAX`. The other pages will require a login anyway.

**Comment by mariusraht2** [comment]
@mbtools Done. Thanks :)

**Review by mbtools — APPROVED** [review]
I have been running it with `call selection-screen` and it works fine. LGTM

**Comment by larshp** [comment]
thanks 👍

**Pull request merged**
