### PR TITLE
Background logic change:  Log exception and continue further processing

### PR DESCRIPTION
**Pull request by yellappam**
Currently, when executing the background logic if a repo processing fails, it raises an exception and aborts the further processing. 
This change will log the error, in case of an exception, and continue processing with next repository. It fixes [issue_4527](https://github.com/abapGit/abapGit/issues/4527)

### CODE REVIEW

**Comment by yellappam** [comment]
Unit testing output
image

**Review by mbtools — APPROVED** [review]
lgtm

**Comment by larshp** [comment]
thanks 👍 

welcome to abapGit as a contributor 🎉

**Comment by yellappam** [comment]
Thank you.

**Pull request merged**
