### PR TITLE
Refactor: Remove dynamic instantiation of ZCL_ABAPGIT_MESSAGE_HELPER

### PR DESCRIPTION
**Pull request by mbtools**
Consolidate `ZCL_ABAPGIT_MESSAGE_HELPER` features into `ZCX_ABAPGIT_EXCEPTION` and removes helper.

https://github.com/abapGit/abapGit/issues/2811

### CODE REVIEW

**Comment by larshp** [comment]
hmm, I remember this was causing some problems earlier

**Comment by mbtools** [comment]
the problem was the dependency between exception and helper and the order of them in the standalone version. this gets rid of the helper completely. but it's core so needs to be tested well indeed

**Comment by g-back** [comment]
I tested this: checkout out this PR, used abapmerge to create the standalone report, imported it into SAP.
No syntax errors, no runtime errors doing basic stuff (navigation repos).
Anything specific you want me to test?

**Comment by g-back** [comment]
Also: these lines can be removed https://github.com/abapGit/abapGit/blob/6675c8fb8b36d9412bdf8d06c82267aa291ded07/src/zcx_abapgit_exception.clas.abap#L201-L206

**Comment by larshp** [comment]
@g-back thanks for testing

@mbtools can you help removing the above comments from the code?

**Comment by larshp** [comment]
anyhow, merging

**Pull request merged**
