### PR TITLE
Repo View: Jump to object type implementation

### PR DESCRIPTION
**Pull request by mbtools**
If _experimental features_ are enabled, the "Type" column in the repo view is turned into a link displaying the corresponding class `zcl_abapgit_object_<type>`. This way you can quickly see how the object type is implemented.

image

### CODE REVIEW

**Comment by flaiker** [comment]
Binding this to the experimental features toggle seems a bit misleading, as the feature itself isn't experimental. Rather a "developer mode"? Though that term also seems quite close to the "developer version" in as opposed to the standalone version.

Normally I would suggest to not put it behind a setting and just remove the link and make it Ctrl/Alt+Click or middle mouse button on the label (without hover cursor change) but that might be impossible with the html control.

**Comment by mbtools** [comment]
the experimental features are only available in the dev version (https://docs.abapgit.org/guide-settings-global.html#development-internal-settings). it's kind of similar. maybe we should change the description to "Debug Mode" or "Developer Mode". Then it would apply to "Utilities > Open in IE Dev Tools" too.

**Comment by flaiker** [comment]
What actually is included currently by experimental features? By that name I would expect things only to be in there for a limited amount of time until they are stable / tested enough.

**Comment by mbtools** [comment]
currently only used by PDTS object type. there were plans to get rid of it... i didn't want to go to JS for a simple link. but we can use something else than the switch

**Comment by flaiker** [comment]
Oh I don't mind. Could also bind it to being the developer version or add a new toggle "Developer Mode" (that only shows up when using the developer version) and move IE dev tools to there as well and leave the actual experimental stuff with the existing toggle.

**Comment by mbtools** [comment]
we call it "developer version" but it's used more widely since it can be update in batch (some trusting folks run the update nightly).

**Comment by larshp** [comment]
I'd challenge if this feature is needed? Will it be used, I think it will just be left there for years, increasing codebase and complexity

**Comment by mbtools** [comment]
It was just for myself since I'm going back and forth between testing in AG and debugging the object classes. I will keep it to my fork

**Pull request closed without merging**
