### PR TITLE
Reset sort order to ascending in repo overview

### PR DESCRIPTION
**Pull request by kjetil-kilhavn**
Reset mv_order_by_descending to abap_false for action change-order-by in event handler
Solves issue #5839

### CODE REVIEW

**Review by mbtools — APPROVED** [review]
Lgtm 

We might want to persist the order setting like we do for repo view. But that's another pr

**Comment by sbcgua** [comment]
I'd actually move `set_order_direction` call inside `set_order_by`. The latter is kind of a higher level. So resetting the direction on changing of field makes sense.

**Review by sbcgua — APPROVED** [review]
Let's merge it, I'll re-check again within #5814

**Comment by mbtools** [comment]
@kjetil-kilhavn, please sync your branch with main. we can merge it then.

**Comment by larshp** [comment]
@kjetil-kilhavn see comment above^

or make sure https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork is checked

**Comment by kjetil-kilhavn** [comment]
Branch has been synchronized with upstream main @mbtools - and thanks for the tip on that setting @larshp

**Review by mbtools — APPROVED** [review]
👍

**Comment by mbtools** [comment]
@kjetil-kilhavn sorry, you have to do it one more time since something else got merged in the meantime

**Comment by kjetil-kilhavn** [comment]
Synchronized again - abaplint/cross check still executing. 
I could not find that setting to allow upstream maintainers to do it. Perhaps that is not possible since this repository is under the Equinor organization, despite it being a public repository.

**Comment by mbtools** [comment]
It's a checkbox when you create the PR:

image

It certainly requires permission. Not sure if there's a way to change it for an existing PR. Anyway, you can look for it next time and see if you can set it. 😃

**Pull request merged**
