### PR TITLE
Enhancement for Object Selector

### PR DESCRIPTION
**Pull request by mbtools**
The object selector popup, for example when pulling, supports only "Select All" and "Select None". This enhancement adds another button with a popup giving a few options:

image

image

### CODE REVIEW

**Comment by larshp** [comment]
hmm, guess its not possible to add another button?

**Comment by mbtools** [comment]
It has to be an existing PFSTATUS and you can't add buttons.

**Comment by larshp** [comment]
hmm, I'd get annoyed with the extra step, I typically check everything

**Comment by mbtools** [comment]
yeah, another button would be nicer. or a keyboard shortcut. i will keep looking for a better pfstatus

**Comment by larshp** [comment]
I'd refactor it to HTML, but its more work 😅

**Comment by mbtools** [comment]
I found something. It reorders the buttons but works well.

**Review by larshp — APPROVED** [review]

**Pull request merged**
