### PR TITLE
SRVB: Service Binding object changes

### PR DESCRIPTION
**Pull request by shyambalachandran**
Service Binding(SRVB) object changes

### CODE REVIEW

**Comment by larshp** [comment]
#3443

**Comment by mbtools** [comment]
Nice. Could you please check that the test repo works with the changes?
https://github.com/abapGit-tests/SRVB

If it needs an update, please create a PR for it. Thanks!

**Comment by mbtools** [comment]
Hi Shyam

I did some testing and there were a few issues. As I mentioned above, we always have to serialize the active version. Also, when deserializing, we create/update the inactive version and add the object to the activation queue. This will ensure that dependent objects can be activated together. 

My changes are at https://gist.github.com/mbtools/dac02e5b5582c7d099f6d65db70311cb. 

When testing with https://github.com/abapGit-tests/SRVB, the service binding deserializes properly. However, there are errors related to SUSH:

image

Could you please check if there's something missing in the test repo? Or is it an issue with the SUSH deserializer?

**Comment by larshp** [comment]
@shyambalachandran see above comment

**Comment by shyambalachandran** [comment]
@larshp and @mbtools. The de-serialization is not the issue. Post de-serialization the Service Binding object is in an inconsistent state and hence cannot be edited or opened. The inactive object thus created cannot be activated and will cause problems.

**Comment by ThomasPloski** [comment]
Is there any possibility to mark those generated objects as "generated" by SRVB? This attribute can be used to ignore such objects during pull run. The result should be a successful activation, right?

**Comment by mbtools** [comment]
There's no "marking of objects" to skip them. You can use code (see https://github.com/abapGit/abapGit/pull/4976#issuecomment-953819396). 

However, did you test the GIST I mentioned above? There's no skipping necessary. It works well for the test SRVB... except for the SUSH, which I think is not correct in the repo (or the SUSH deserializer).

**Comment by shyambalachandran** [comment]
Hi @mbtools .
I have created several PRs to correct the Test Repo https://github.com/abapGit-tests/SRVB. I want to delete all the objects except the Service Binding.
Skipping is necessary because the de-serialized object is in an inconsistent state. User cannot perform any CRUD operations on such an inconsistent object. We have to address that issue.
For now, I will take your changes and incorporate them into mine and make another submit. Please accept the PRs for the test repo so that I can use it again to test.

**Comment by mbtools** [comment]
Test repo is cleared.

**Comment by mbtools** [comment]
1. Dump on 7.54. -> Use the READ method for the existence check 

```
Runtime Errors         DYN_CALL_METH_NOT_FOUND
Except.                CX_SY_DYN_CALL_ILLEGAL_METHOD
ABAP Program           ZCL_ABAPGIT_OBJECT_SRVB=======CP

 An attempt was made to call method "IF_WB_OBJECT_OPERATOR~CHECK_EXISTENCE" of
  class "CL_WB_OBJECT_OPERATOR". Method "IF_WB_OBJECT_OPERATOR~CHECK_EXISTENCE"
  could
 not be found in class "CL_WB_OBJECT_OPERATOR" however.
```

2. SRVB is not a DDIC object that is supported by mass activation (see include `RADMASUTC form ma_tab_check`). -> Here's what it needs to be

```abap
  METHOD zif_abapgit_object~get_deserialize_steps.
    APPEND zif_abapgit_object=>gc_step_id-abap TO rt_steps.
  ENDMETHOD.


  METHOD zif_abapgit_object~get_metadata.
    rs_metadata = get_metadata( ).
    rs_metadata-delete_tadir = abap_true.
  ENDMETHOD.
```

3. Test case -> Please update https://github.com/abapGit-tests/SRVB with a working example

**Review by mbtools — APPROVED** [review]

**Comment by shyambalachandran** [comment]
@mbtools , thanks for the approval.
As for the third point, this REPO is consistent. The REPO should contain ONLY the Service Binding( and possibly Service Defintions ) but NOT the generated SUSH or Gateway Artifacts.

**Comment by larshp** [comment]
welcome to abapGit as a contributor 🎉

**Pull request merged**
