### PR TITLE
CLAS/INTF: Fix `seocompotx` during deserialization

### LINKED ISSUE #6442: [CLAS/INTF] DB inconsistency in `seocompotx`
Creating objects of type CLAS/INTF via **pulling in abapgit** or **ADT** can result in different `seocompotx` entries. Background: Class component (meth, attri, ..) without description is expected to have seocompotx entry (with description = space).

Reproduce:
Pulling repository https://github.com/abapGit-tests/CLAS will create class `zcl_ag_unit_test` without entries in `seocompotx`, which is wrong.
vs
Creating the same class via ADT/SAPgui will result in entries `seocompotx`.

👋 We plan to provide a fix in abapGit

Further reading or how-you-break-things:
The logic in function module `seo_attribute_existence_check` (and others) is based on joins on `seocompotx`.

### PR DESCRIPTION
**Pull request by albertmink**
Closes #6442

### CODE REVIEW

**Comment by larshp** [comment]
`seoc_version_deleted`, add this to https://github.com/abapGit/abapGit/blob/issue-6442/abaplint.json#L23

**Comment by larshp** [comment]
actually, in https://github.com/abapGit/abapGit/blob/issue-6442/deps/seoc.type.abap instead

**Comment by larshp** [comment]
plus in https://github.com/abapGit/abapGit/blob/issue-6442/ci/abaplint.json#L45

**Comment by mbtools** [comment]
Tool to fix the inconsistencies caused by abapGit:
https://gist.github.com/mbtools/3bf797eed1161bd64c0d6610f804582a

**Pull request merged**
