### PR TITLE
DSFD: CDS Scalar Function Definition

### PR DESCRIPTION
**Pull request by fvalves**
Added the DSFD Object Handler as specified in abapGit#6948

### CODE REVIEW

**Comment by larshp** [comment]
please open a PR with test objects => https://github.com/abapGit-tests/DSFD

**Comment by albertmink** [comment]
@fvalves: Is there an AFF specified for `DSFD`, see https://github.com/SAP/abap-file-formats? Can you provide an example of a serialized object?

**Comment by mbtools** [comment]
Example available at https://github.com/abapGit-tests/DSFD

**Comment by larshp** [comment]
@albertmink any comments? it looks good to me

**Review by albertmink — APPROVED** [review]
Couldn't pull the test repository due to some expired certificate issues (I guess). AFAIK, the source LGTM.

**Comment by larshp** [comment]
welcome to abapGit as a contributor 🎉

**Pull request merged**
