### PR TITLE
flow page: add user exit

### PR DESCRIPTION
**Pull request by larshp**
as separate user exit, because

1. dont want to couple the backend user exit to UI
2. expecting this exit to be unstable for a while

allows adding more actions to the toolbar

### CODE REVIEW

**Comment by mbtools** [comment]
wondering if we should make these more generic for any UI (`zif_abapgit_ui_exit`) and move the existing `enhance_repo_toolbar`, `on_event`, and `wall...` over to that one.

**Comment by larshp** [comment]
yea, tho not sure how

**Comment by larshp** [comment]
merge?

**Review by mbtools — APPROVED** [review]
go for it 👍

**Pull request merged**
