### PR TITLE
Introduce ABAP Language Version (ALV) to .abapgit.xml

### PR DESCRIPTION
**Pull request by ThomasPloski**
fixes issue #6334

### CODE REVIEW

**Comment by mbtools** [comment]
Code is part of the solution and looks good to me. However, I don't think we should add this as is. Every newly created repo will get diffs when used in older abapGit versions (not sure what happens if you try to pull). 

We should mark the feature to be experimental so we can merge without impacting the community. 

```abap
IF zcl_abapgit_persist_factory=>get_settings( )->read( )->get_experimental_features( ) = abap_true.
...
ENDIF.
```

**Comment by ThomasPloski** [comment]
I will surround the affected coding parts with the mentioned if statement and update the PR.

**Comment by ThomasPloski** [comment]
One step back: I have decided to not touch the current logic in .abapgit.xml handling, so that surrounding with experimental feature is not required, since there is no defaulting while object creation.

**Comment by mbtools** [comment]
looks like these changes are included in #6346

**Review by schneidermic0 — APPROVED** [review]
Thanks, @ThomasPloski. LGTM

**Comment by ThomasPloski** [comment]
This PR can be closed since the PR #6346 contains of those changes

**Pull request closed without merging**
