### PR TITLE
#6416 new tab deserialize objs

### PR DESCRIPTION
**Pull request by fmabap**
new table deserialize objects as start of the refactoring

### CODE REVIEW

**Review by larshp — CHANGES_REQUESTED** [review]
whats the story behind the new public method?

and one part of the change is extracting logic to a new private method, to keep the original small?

**Comment by fmabap** [comment]
> whats the story behind the new public method?
> 
> and one part of the change is extracting logic to a new private method, to keep the original small?

As discussed with @mbtools we want to decouple the repo from the deserialization, so that it will be possible to deserialize objects without a repo (later also with a parallelization). In this step I introduced the new table lt_deserialized_objects as basis of the deserialization. I made get_deserialized_objects private now.
The new method reg_obj_in_deserialize_steps was required in this step, because of the abaplint limit to have max. 115 statements in a method.
I want to change so less as possible in one step (PR), so that you can review the changes in github easier.
Next step (PR) will be to move the big LOOP AT lt_deserialized_objects into a new method. After this, I will remove the dependencies of the repo in this method with a new PR.

**Comment by larshp** [comment]
* extracted logic to method `reg_obj_in_deserialize_steps`

**Comment by fmabap** [comment]
> so,
> 
> * extracted logic to method `reg_obj_in_deserialize_steps`
> * new table `lt_deserialized_objects` for decoupling repo
> * method `get_deserialized_objects` changed to private
> 
> ?
> 
> however, method `get_deserialized_objects` is new? it calls `lo_files->get_files( )`, which is not currently called? To me, this looks like a high impact change?
> 
> The comment `" Packages have the same filename across different folders. The path needs to be supplied` occurs twice in the new code, so it looks like a duplication of code?
> 
> What's the desired final state, and how does this change help getting to the final state?

The method get_deserialized_objects takes the it_results and it_remotes and brings them together into rt_deserialized_objects. For this “come together” is the method lo_files->set_files used. It filters from it_remotes the files that belongs to the current object and stores them in the lo_files instance. Lo_files->get_files just returns the files of the instance. There is no special logic for it.
Yes, the one IF for the path of the packages is now two times in coding. Do you have an idea how to have it only one time? I don’t want to save lo_files in rt_deserialized_objects. I think it is so moreflexible for future requirements.
The final state of this class at the first big step will look nearly like this:
https://github.com/fmabap/abapGit/blob/c69dd5b6f8895ac8870982ceed1f0f549ec8d421/src/objects/zcl_abapgit_objects.clas.abap#L581
We will have then the existing public method deserialize that calls the new public method deserialize_objs to deserialize the objects of the repo.
Deserialize_objs can then be used also from a new functionality to deserialize only objects.
The reaming called methods of the deserialize method will then be also decupled from the repo, so that the future functionality can also use these methods.

**Comment by larshp** [comment]
okay, I suggest choosing _one_ method in `zcl_abapgit_objects`, and then we can design how it should look in the future

method `serialize` is okay? so lets look into `deserialize` and `deserialize_checks`, as they are connected?

**Comment by fmabap** [comment]
> okay, I suggest choosing one method in `zcl_abapgit_objects`, and then we can design how it should look in the future
> 
> method `serialize` is okay? so lets look into `deserialize` and `deserialize_checks`, as they are connected? For these, the change I expect is `zcl_abapgit_repo` being replaced with `zif_abapgit_repo`

@larshp 
I'm sorry, but I don't understand what I shall do / change now. Will you first merge the current changes and then we will go a head with the next small changes, or do you want one PR with all changes?

zcl_abapgit_objects can get at the end one method deserialize. It will deserialize then only objects (without a repo). The repo method can be moved to another class. But these are bigger changes. I would prefer todo them step by step...

**Comment by larshp** [comment]
closing, no progress

**Pull request closed without merging**
