### PR TITLE
Remove test data container variants on pull that do not exist on the remote

### LINKED ISSUE #6491: ECTD deleted variants on the remote are not deleted locally on pull
From https://github.com/abapGit/abapGit/issues/6489#issuecomment-1717954996

> Somewhere down these gigantic classes in their inheritance forests was a call to update the variants in the test data container. Only the import parameter for new and changed variants was supplied, not for removed ones. I removed a variant from the TDC and committed to a new branch. Then switched back und pulled to get the variant back. After now switching to the new branch again and pulling I am unable to remove the variant using abapGit.

Found it again in CL_APL_ECATT_UPLOAD->GET_VARIANTS_FROM_DOM_NEW, the call to CL_APL_ECATT_PARAMS->SET_VARIANTS( ).

This is SAP standard code. The GUI application appears unaffected by this though as it asks if all variants should be deleted on upload:

image

In CL_GUI_ECATT_DATA_EDITOR->UC_UPLOAD_VARIANTS a replace mode for CL_APL_ECATT_EXT_DATA=>UPLOAD_VARIANTS is determined using the user decision. UPL_SET_TEST_DATA in the same class accounts for this by calling CL_APL_ECATT_PARAMS->DELETE_VARIANTS( '*' ) before CL_APL_ECATT_PARAMS->SET_VARIANTS( ). We can probably do the same somewhere. 

Edit: I may have mixed up the feature to download and upload just the variants or the whole test data container. I cannot find a way to update the whole test data container including its variants using the GUI, the object needs to be deleted first. However, the call to delete all variants should still work as both upload/download features appear to use the same classes.

### PR DESCRIPTION
**Pull request by fabianlupa**
Fixes #6491

Not all too proud of this _solution_ but it works without copying over the base class code or deleting the whole object before pull. I am open to any better ideas.

The test repository fails with diffs:

image

But that is due to #6489.

image

### CODE REVIEW

**Comment by fabianlupa** [comment]
I added the branch https://github.com/abapGit-tests/ECATT/tree/remove-variant to test the PR. The test repo also uses multiple versions which does seem to work correctly as far as I can see.

**Comment by larshp** [comment]
deps fixed with https://github.com/abaplint/deps/pull/210 and https://github.com/abaplint/deps/pull/211

**Comment by mbtools** [comment]
In your test branch, version 2 is before version 1. Looks like another issue:
https://github.com/abapGit-tests/ECATT/compare/remove-variant

**Comment by fabianlupa** [comment]
I wonder if these sorting issues are just missing order-bys in standard coding that now runs on HANA.

**Pull request merged**
