### PR TITLE
Dialogs: HTML forms - follow-up

### PR DESCRIPTION
**Pull request by mbtools**
Follow-up to #4264:

1. Split `zcl_abapgit_html_form` class
  - Processing form data moved to `zcl_abapgit_html_form_utils`
  - Types and constants move to `zif_abapgit_html_form`
2. `iv_is_main` refactored to `iv_cmd_type`
3. In case of unsaved data, form exit will now prompt for confirmation (`zcl_abapgit_html_form_utils`)

### CODE REVIEW

**Comment by sbcgua** [comment]
ufff, a lot of code ... will check it these days

**Comment by sbcgua** [comment]
Hi All. I went to a vacation and forgot laptop charger :( so all opensource plans failed. And i cannot review this practically. From what i can see in code only: it is ok in general. I'm a bit suspicious about "exit" method - it couples different kinds of ui. I would also probably separate validation from things like exit. But not critical for the moment.

**Comment by larshp** [comment]
@sbcgua forgetting charger is a good thing :) have fun, relax 🍹 🌴

**Comment by larshp** [comment]
merging, before I mess up too much 😄

**Pull request merged**
