### PR TITLE
Decouple last direct usage of `CL_GUI_FRONTEND_SERVICES`

### LINKED ISSUE #2510: isolate use of cl_gui_frontend_services to the /ui/ package
isolate use of cl_gui_frontend_services to the /ui/ package

@ThomasPloski

### PR DESCRIPTION
**Pull request by g-back**
- methods `directory_exist` and `directory_create` added to interface
- changes/cleanup in `zcl_abapgit_transport_mass` local types:
  - replace direct `cl_gui_frontend_services` usage with interface
  - normalize comments
  - normalize method signature formatting
  - replace concat with string templates
 
closes #2510

### CODE REVIEW

**Review by mbtools — APPROVED** [review]
👍

**Comment by mbtools** [comment]
We can merge this but there's one more: 

image

**Comment by g-back** [comment]
That's true. Later in the same method multiple constants of `cl_gui_frontend_services` are used as well. However, all of these are already behind an interface called `gui_functions`.

I don't mind either way, but if we replace this method we should also put the constants in the frontend_services interface as well?

**Comment by mbtools** [comment]
I will do a separate PR to move all of `ZCL_ABAPGIT_GUI_FUNCTIONS` to `ZCL_ABAPGIT_FRONTEND_SERVICES`. Then all the FE calls are nicely together. No need for two "front-end classes".

**Pull request merged**
