### PR TITLE
Focus HTML control on abapGit startup

### PR DESCRIPTION
**Pull request by mbtools**
#4816

`cl_gui_control=>set_focus` must be called during PBO. Maybe there's a nicer way to pass the HTML control to the PBO or the other way around: expose a method in the viewer that can be called from the PBO.

### CODE REVIEW

**Comment by jfilak** [comment]
FYI: @FreHu pulled it to one of our decentralized systems and I tested it with JavaGU. The result: there is no widget with focus (all keyboard events are completely ignored). Without this PR, the focus is in the command/transaction field of JavaGUI.

**Comment by FreHu** [comment]
In js, focus can be set on document load, for example `document.querySelector("a[href='sapevent:repo_newonline']").focus()`.
In javagui this has no effect either.

**Comment by mbtools** [comment]
I tested also with Web GUI and it works well. Good to merge from my pov.

**Comment by mbtools** [comment]
For WebGUI and Chromium Control, I think js is a feasible solution to move the initial focus (see @FreHu above).

**Comment by christianguenter2** [comment]
We already have a logic in place which tries to focus the filter input field on startup. But it doesn't work either.
https://github.com/abapGit/abapGit/blob/0344f7e360a66ff16920f00b95d7ac31c0c6bace/src/ui/zcl_abapgit_gui_page_repo_over.clas.abap#L270
https://github.com/abapGit/abapGit/blob/a92059d059aec3637443fb8aad559d6f81ef5fd5/src/ui/zabapgit_js_common.w3mi.data.js#L141-L143

**Comment by FreHu** [comment]
@christianguenter2 based on my testing the js should work now

**Comment by christianguenter2** [comment]
Hm, no. Not for me with chromium based browser control.
I have to press tab once then 'New online' is focussed and I can use hotkeys.
abapGit

**Comment by FreHu** [comment]
On IE control:
https://user-images.githubusercontent.com/5097067/121029208-b4ff5e80-c7a8-11eb-91ef-856134457c6d.MP4

**Comment by christianguenter2** [comment]
Yes, it works for me on IE control too.

**Comment by christianguenter2** [comment]
Can be merged from my point of view. Just want to let you know that there's different behaviour with Chromium.

**Comment by mbtools** [comment]
Here are my tests to check if cursor is in "Filter" field after startup. 

GUI | Test
-----|-----
SAP GUI 7.60 patch 11 (IE control) | Works consistently
SAP GUI 7.70 patch 1 + IE control | Works consistently 1)
SAP GUI 7.70 patch 1 + Chrome control | Works sporadically 2)
SAP GUI 7.70 rev 1 (Java) | Does not work 3)
Web GUI (SAP Kernel 7.53 patch 819) + Chrome | Works consistently

1) Cursor is in filter field but strangely not blinking
2) Often is does not work. But sometimes it does: Put cursor into filter field, then exit, the start again. If you repeat it, the cursor will sometimes be in the field as expected. Imho, that's an SAP or Microsoft (WebView2) bug.
3) It seems, the HTML control does not gets the focus at all and isn't even part of the tab-sequence. AG only works properly, if you click into the control.

PS: I added a line of JS right after the focus statement to turn the field red to be sure it actually executed and the JS runs in all cases.

image

**Comment by christianguenter2** [comment]
Good news. With SAPGUI 7.70 for Windows SP Patch 2 and Chromium Browser Control 'New Online' is focused on startup. It works consistently for me.
image

**Comment by mbtools** [comment]
That's better but JS should have moved the focus to the filter field.

**Pull request merged**
