### PR TITLE
Exception handling small improvement

### PR DESCRIPTION
**Pull request by wurzka**
Exception handling of class zcl_abapgit_object_common_aff is improved

### CODE REVIEW

**Comment by larshp** [comment]
I'll have a look at the error from the unit test

**Comment by wurzka** [comment]
Thanks!

**Comment by larshp** [comment]
fixed with https://github.com/open-abap/open-abap/pull/379, I've retriggered the unit test rerun manually

**Review by larshp — APPROVED** [review]
LGTM, thanks

**Pull request merged**
