### PR TITLE
Fix Issue With New Files

### PR DESCRIPTION
**Pull request by PeregrinTooc**
fix bug that new local files lead to a short dump in diff determination

### CODE REVIEW

**Comment by larshp** [comment]
thanks, we already have this in https://github.com/abapGit/abapGit/pull/4162, I'll go ahead and merge 4162

**Comment by larshp** [comment]
@PeregrinTooc try again, latest master

**Review by larshp — CHANGES_REQUESTED** [review]
no changes, merged via #4162

**Comment by larshp** [comment]
@PeregrinTooc closing this PR, feel free to open an issue if the fix to master did not work

**Comment by PeregrinTooc** [comment]
Thanks, it worked 😊

Lars Hvam <notifications@github.com> schrieb am Sa. 14. Nov. 2020 um 11:25:

**Pull request closed without merging**
