### PR TITLE
Refresh repository to reduce memory usage in background mode

### LINKED ISSUE #6727: Runtime error `SYSTEM_NO_ROLL` in background mode
Hello abapGit community, 

I am encountering runtime error `SYSTEM_NO_ROLL` when executing the background mode. The memory is getting too full.

The background mode is initiated from method `RUN` of `ZCL_ABAPGIT_BACKGROUND`. It seems like each individual repository can be processed just fine. However, every instance of `ZCL_ABAPGIT_REPO_ONLINE` still remains in the session with a lot of data.  

Here's an excerpt from the dominator tree after a few repositories have been processed:
image

Each instance still needs memory because the tables `MT_LOCAL`, `MT_REMOTE` and `MT_OBJECTS` remain filled. I think it would be a good idea to somehow "reset" / "clear" a repository instance after it has been processed. 

Another cheap alternative could be to process each repository in a separate session using destination `NONE`.

What are your thoughts on this?

### PR DESCRIPTION
**Pull request by ConjuringCoffee**
Fixes #6727

### CODE REVIEW

**Comment by ConjuringCoffee** [comment]
This has fixed the error for me, but there are currently no open changes. I'd like to keep this pull request open for a few days and monitor the system's behavior.

**Comment by ConjuringCoffee** [comment]
Is it okay to use the default value `abap_true` for `iv_drop_log`? I'm not sure regarding possible side effects.

**Comment by larshp** [comment]
> Is it okay to use the default value `abap_true` for `iv_drop_log`? I'm not sure regarding possible side effects.

yea, I think so

**Comment by larshp** [comment]
@ConjuringCoffee is the change ready for review?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#marking-a-pull-request-as-ready-for-review

**Comment by ConjuringCoffee** [comment]
I kept the merge request as a draft because I wanted to monitor the fix a bit. Our nightly job was successful again, so that looks good to me.

**Review by larshp — APPROVED** [review]
looks good to me, thanks 👍

**Pull request merged**
