### PR TITLE
Use git credential helper on the frontend for authentication

### PR DESCRIPTION
**Pull request by flaiker**
Not sure if we actually want to merge this into abapGit but I wanted to show that this does indeed work. Could also link a gist in the docs and provide an exit instead.

This PR adds an option to redirect the git authentication to the frontend (read as frontend server) by calling git.exe over there and retrieving the username and password. Which means you don't have to enter any logon information at all if git on your PC already has the login details for the git host. I use [git credential manager core](https://github.com/microsoft/Git-Credential-Manager-Core) which stores the login data in the secure credential storage of the OS and also supports OAuth for multiple hosts (I think it also comes preinstalled if you check the box in the git for windows installer).

Regarding the implementation to get this to work. It's _shamefully_ hacky. Git provides a command line API to access its [credential helper framework](https://git-scm.com/docs/gitcredentials) with [`git credential fill`](https://git-scm.com/docs/git-credential). It looks like this:

```
> echo "url=https://github.com/flaiker/secret-repo" | git credential fill
protocol=https
host=github.com
username=flaiker
password=mysecretpasswordortoken
```

If there is no authentication data stored you get a popup or even a whole OAuth flow with token generation etc.

Now to call this from the application server....

You cannot use cl_gui_frontend_services=>execute for this as there is no way to get return values back. You would have to write a file and read it again which seems non optimal. I instead went for the only other way I could think of to do something on the frontend which unfortunately means using OLE to spawn some kind of VBScript environment, load VBA code which open a shell to execute powershell to execute the call, retrieve the stdout output and parse it for the information we need. Which is the reason this might not be a good idea to have in abapGit :)

For new login details it looks like this. Note the OLE warning popup. For existing login details there's no browser window / user interaction.

```
New:
https://user-images.githubusercontent.com/5270359/103440648-a041fc00-4c47-11eb-858c-f8bc4cead35b.mp4
Existing:
https://user-images.githubusercontent.com/5270359/103440895-d54f4e00-4c49-11eb-943b-d79c0e73e901.mp4
```

(I couldn't get the new markdown mp4 support to work without displaying a black screen in the embedded player for the first few seconds)

Note there also is `git credential approve` and `git credential reject` to tell the credential helper if the credentials should be stored (if new) or deleted if they don't work anymore which would also have to be implemented to not generate new tokens every time for hosts that have not been used with git locally yet.

### CODE REVIEW

**Comment by larshp** [comment]
nice mashup 👍 

undo the TYPES pretty printing? https://github.com/abaplint/abaplint/issues/870

**Comment by flaiker** [comment]
I tried but I seem to have hit Shift F1 again before activating :shrug:

Do you think this could be included in some form in abapGit or rather not?

**Comment by mbtools** [comment]
1) imho, there's some bug in the indent for types/data after include (see below). but even with this fix, it's not clear how abap intents to indent such cases.

```abap
LSPPRP00:

      "skip processing for TYPES/DATA with INCLUDE structure
*{   REPLACE        M0PK900071                                        1
*\      if ( <f_okey>-code > ettrycatch or <f_okey>-code <= etdecl_w_incl ) and <f_okey>-trow > l_srcline_idx.
      if ( <f_okey>-code > ettrycatch and <f_okey>-code <= etdecl_w_incl ) and <f_okey>-trow > l_srcline_idx.
*}   REPLACE
`

2) I like the idea of keeping the credentials on the front-end. Bonus points for the creative implementation :-)

How about passing stdout to an environment variable and getting it into AG using `CL_GUI_FRONTEND_SERVICES=>ENVIRONMENT_GET_VARIABLE`? After the get, you could clear the environment variable again using `ENVIRONMENT_SET_VARIABLE` so nothing is left behind.

**Comment by flaiker** [comment]
Is there any benefit to the environment variable approach? You will get two additional SAP GUI security popups and to me it feels like it is stored in a "public memory space" while `CALL METHOD OF ...` seems more isolated (though I don't actually know how it works in detail, I also was a bit surprised that any process running with user level permissions in Windows has access to all stored login data in git for that user). If the goal is to get rid of OLE and use the environment variable as the return value for frontend_services=>execute I see the benefit, but the mentioned negatives are still there. Haven't tried if execute can actually execute the command and store the result in an environment variable.

**Comment by mbtools** [comment]
Forget the env. variable. Also Scripting (vb/ole/powershell) might not be available or allowed in some environments. 

I would prefer the file-based solution saving the output to file (`execute` with `parameter = `> out.txt`), the `gui_upload` and `file_delete` of the `out.txt` is the best option. Writing temp files is pretty common and the file would exist only for a fraction of a second anyway. We could use a random filename as well. For added security, someone could change the permissions for this folder to allow access only for themselves (seems recommended anyway given how the helper works). In the SAPGUI settings, you can allow these frontend actions permanently for example for the folder containing the git helper so there won't be any security popups.

**Comment by flaiker** [comment]
So you are thinking of the scenario where powershell script execution is prohibited by group policy but for some reason the user is allowed to adjust the SAP GUI security settings himself? Is that a common combination?

Without changing the settings the temporary file will exist for quite some time (seconds) because the program execution must wait for the user to accept reading the temp file in the security popup and also accept deleting the file in another popup (unless the GUI temp path is somehow exempt from that popup?) .

2FA should work fine, you get redirected to generate a token (by logging in including 2FA) which is then used.

Might also help with #3113 .

I still have to test if execute works with the command and pipes.

**Comment by mbtools** [comment]
there's every possible combination of front-end security out there, from "none" to "total lockdown". it's already an assumption that users can install the helper on their machines. there won't be a perfect solution and we can just provide options. I have my own box with credentials in an RFC destination so I'm ok with any solution here. 

One more thing to consider: GCM works with macOS and Linux. The file solution has a chance to work there, too.  If "something" would have access to the temp-file, then that would most likely also have access to GCM directly.  

In any case, what you have is better than entering the token every time and a nice addition to abapGit 👍

**Comment by flaiker** [comment]
I did some more testing. If OLE can be avoided I am all for it :)

Interestingly I ran into the same problem I had within VBScript. I seem to be unable to get a pipe into the cmd.exe /c command. With powershell it works fine. This causes git credentials to not get any input. I tried putting the command in quotes and escaping the inner quotes but so far that didn't work. I will use powershell for now to implement the file based approach then we can compare them.

Accessing files in GET_TEMP_DIRECTORY (C:\Users\User\AppData\Local\SAP\SAP GUI\tmp) does not seem to cause any security popups by the way and also gets cleared automatically on GUI shutdown :)

**Comment by mbtools** [comment]
Try cmd.exe /k

**Comment by flaiker** [comment]
I do not have time to finish this currently unfortunately. I don't want to leave a PR open for long so closing for now. If someone wants to pick this up feel free to do so.

**Pull request closed without merging**
