### PR TITLE
remove 200% icon scaling

### PR DESCRIPTION
**Pull request by larshp**
see #2490, I think this was an issue only back in 2019 when using octicons? @bigld @sbcgua 

removed for cloud + standalone web + open abap compatibility

### CODE REVIEW

**Comment by sbcgua** [comment]
I guess it can be removed

**Comment by larshp** [comment]
could also be changed to a user setting, if someone likes... PRs welcome after this is merged

**Comment by mbtools** [comment]
It's the default [user setting](https://docs.abapgit.org/user-guide/setup/settings-personal.html) currently called "Automatic" (discussion in #5737). If we remove this code, the option should be renamed to "None" or "No scaling".

**Comment by larshp** [comment]
> It's the default [user setting](https://docs.abapgit.org/user-guide/setup/settings-personal.html) currently called "Automatic" (discussion in #5737). If we remove this code, the option should be renamed to "None" or "No scaling".

hmm, how does it work? nothing in the code removed was reading settings

**Review by mbtools — APPROVED** [review]
👍

**Pull request merged**
