### PR TITLE
UI: Add help buttons to "New Online/Offline"

### PR DESCRIPTION
**Pull request by mbtools**
- Add help button to both dialogs linking to docs.abapgit.org
- Clicking the button brings up the documentation inside the GUI HTML viewer

image

- Enhancement to `zcl_abapgit_gui` and `zcl_abapgit_html_viewer_gui` to properly handle 'Back' when navigating through Internet pages

### CODE REVIEW

**Comment by flaiker** [comment]
> Clicking the button brings up the documentation inside the GUI HTML viewer

I would kind of expect the link to open in an external browser (like Help -> Documentation). So you can have the documentation and the page that it documents open at the same time. Also does this use the network stack of the backend or the frontend?

**Comment by larshp** [comment]
yea, I would also like it to open an external browser window, so the documentation and actual screen can be open at the same time

**Comment by mbtools** [comment]
It was using the frontend network (like other browsers). I agree. External browser is better.

**Comment by sbcgua** [comment]
cool feature is this help button :+1:

**Pull request merged**
