### PR TITLE
ZABAPGIT_FORMS: Remove obsolete form package_popup and related callback handler

### PR DESCRIPTION
**Pull request by mariusraht2**
Form package_popup in ZABAPGIT_FORMS and its related callback handler aren't being used anymore and can thus be removed.

### CODE REVIEW

**Comment by mariusraht2** [comment]
Oo..Any suggestion how to find that within SE80 or Eclipse? Seems like Eclipse wasn't able to find it and Code Scanner can't search within temporary packages :(

**Comment by mariusraht2** [comment]
> Well, that's why there was a comment in the code ;-)

Ok, right..^^ Well, package_popup isn't being used anymore, so one at last to remove.. :)

**Comment by mbtools** [comment]
Yes. You can remove `ZCL_ABAPGIT_POPUPS/ZIF_ABAPGIT_POPUPS~PACKAGE_POPUP_CALLBACK` and reference in `ZCL_ABAPGIT_UI_INJECTOR` too.

**Review by mbtools — APPROVED** [review]
LGTM

**Comment by larshp** [comment]
thanks 👍

**Pull request merged**
