### PR TITLE
BRF+ System Application

### LINKED ISSUE #33: BRF+ serialization
FDT0	FDT/BRFplus: System Application
FDT1	FDT/BRFplus: Customizing Application

### PR DESCRIPTION
**Pull request by mbtools**
Follow-up of #4797

- Clear user/time/system-specific fields
- Fix deletion of object
- Remove unnecessary "exists check"
- Updated test case https://github.com/abapGit-tests/FDT0

Closes #33

### CODE REVIEW

**Comment by larshp** [comment]
I'll fix the `namespace` error in `deps`

**Comment by larshp** [comment]
try pushing another commit, `deps` updated

**Comment by mbtools** [comment]
Thanks. At least the test case works e2e. Needs a bit of testing with other scenarios like updating an BRF+ app and using transportable package.

**Comment by mbtools** [comment]
that was not the right one...

**Comment by mbtools** [comment]
All good now. Happy testing!

**Comment by larshp** [comment]
@SaschaWaechter can you help testing this change?

**Comment by SaschaWaechter** [comment]
Yes can help testing on the weekend... week is full of work.

**Comment by SaschaWaechter** [comment]
Started to test the new changes. 
Deletion now works way better and the Brf+ specific fields like time, system, etc. now filtered. 
If I add some elements to the Application the diff handling don't work correctly anymore. Don't know if its system/language, etc dependent (Looks a bit strange) but if I remove elements diff-handling works as expected). 
Transport handling seems to work but I will test on another Dev-system with some real projects because get some messages from BRF+-API for transport handling which don't seem to come from the Abapgit integration. 
(I have seen many big BRF+-projects out there so if someone just has one like to test it as well. Real test cases are always better)

Remove unnecessary "exists check" is 👍

**Comment by mbtools** [comment]
Thanks for testing. 

I suggest to merge this and create an issue with new findings (maybe add screenshot of diffs)

**Comment by larshp** [comment]
merging, thanks 👍

**Pull request merged**
