### PR TITLE
FUGR: Fix performance issue

### LINKED ISSUE #5016: Performance issue in method ZCL_ABAPGIT_OBJECT_FUGR->ZIF_ABAPGIT_OBJECT~CHANGED_BY
We identified a performance issue in the method ZCL_ABAPGIT_OBJECT_FUGR->ZIF_ABAPGIT_OBJECT~CHANGED_BY.
In our special case we have a function group for enhancing material master and there are 521 includes (from Standard) within. The method is called for every include line in the "repo list". So we have 521x521 single selects which lasts on our S/4 System 600+ seconds. 
The SELECT within a LOOP should be replaced with a SELECT ... FOR ALL ENTRIES:

```
    IF lt_includes IS NOT INITIAL.
      SELECT unam AS user udat AS date utime AS time FROM reposrc
        APPENDING CORRESPONDING FIELDS OF TABLE lt_stamps
        FOR ALL ENTRIES IN lt_includes
        WHERE progname = lt_includes-table_line
        AND   r3state = 'A'.                              "#EC CI_SUBRC
    ENDIF. 
```

Next step should be avoiding calling the method for every single include of the same function group again. So you can minimize the count of selects in our case from 271.441 first to 521 and then to 1. Sounds good, or not? ;-)

### PR DESCRIPTION
**Pull request by mbtools**
Optimize selection of function group includes.

Closes #5016

### CODE REVIEW

**Review by larshp — APPROVED** [review]

**Comment by JoergNaundorf** [comment]
Thanks for the quick fix, but the new instance variable does not take effect in our case. The method is called several times with always new instances for the same function group.

**Comment by larshp** [comment]
yea, it creates a new instance each time the object is serialized

**Comment by JoergNaundorf** [comment]
So the new instance variable does not have any effect in ZCL_ABAPGIT_OBJECT_FUGR->ZIF_ABAPGIT_OBJECT~CHANGED_BY. Perhaps it could be a solution to buffer the instances in ZCL_ABAPGIT_OBJECTS=>CREATE_OBJECT for every IS_ITEM instead of creating always a new instance. Clearing this buffer at the right time could be a challenge.
In our case we have several lines (521) in lt_status in method BUILD_REPO_ITEMS_WITH_REMOTE which are belonging to the same function group, and everytime there is a new select just to get the "changed by user".

**Comment by larshp** [comment]
no, the objects are serialized in parallel, so the instance buffer will not be shared anyhow

**Comment by JoergNaundorf** [comment]
ok, I understand - but you found another way of "buffering" in #5019. thumbs up!

**Pull request merged**
