### PR TITLE
Improve folder logic popup

### PR DESCRIPTION
**Pull request by christianguenter2**
Replaces this popup
grafik

with this
grafik

Makes it a bit less error prone.

### CODE REVIEW

**Comment by mbtools** [comment]
there's also `MIXED` ;-)

**Review by larshp — DISMISSED** [review]
see comment by @mbtools

**Comment by christianguenter2** [comment]
Good catch. Never used that one. Fixed.
grafik

**Review by mbtools — APPROVED** [review]
👍

**Pull request merged**
