### PR TITLE
DOMA: Fix serialize for missing translations

### LINKED ISSUE #4278: Diffs for dd07_texts in doma
After abapGit update: Two added items added without content?

image

DD07T looks like this (partial translation):

image

For some other domains I only have one added empty item. DD07T then looks like this:

image

Note these domains have the empty value as part of their fixed values:

image

The translation seems to be only partial in my case but it still doesn't seem to be correctly serialized right?

### PR DESCRIPTION
**Pull request by mbtools**
Closes #4278

### CODE REVIEW

**Comment by flaiker** [comment]
I haven't really worked with translated objects yet and was surprised to find some in my repos. Does this allow for differentiation between empty translations and non existing translations? For example if I have a missing translation (no entry in table) in my system I guess it would show up in the worklist the translation environment generates. But if there were an entry and it just has an empty text it might not? Which may happen if we serialize missing texts as empty texts?

**Comment by mbtools** [comment]
As far as I can tell, for DOMA, there's no choice since DDIF_DOMA_PUT needs all values for each language or the missing values will be deleted. 

Also not a translation expert, but I believe empty translations will show up in the translation tool as "missing" or "incomplete".

**Review by flaiker — APPROVED** [review]
Looks way better now! Haven't tested the null versus empty handling as I cannot pull on this system. Can add a test repo later but probably doesn't block this PR.

image

image

**Comment by larshp** [comment]
thanks both 👍

**Pull request merged**
