### PR TITLE
refactor, extract git definitions to git

### PR DESCRIPTION
**Pull request by larshp**
this is a start for extracting the git definitions to a new git definitions intf, `zif_abapgit_git_definitions`

`zif_abapgit_definitions` is getting too large, and its worth separating the responsibilities of the packages

this is just a start, trying to keep the amount of changes small, but its difficult

### CODE REVIEW

**Comment by larshp** [comment]
breaking lots of things, see cross check

**Comment by mbtools** [comment]
You removed types completely and changed all the usage. That was a lot of work...  Why not keep the types in the defs interface but point them to the git defs?

Keeping the following would reduce the impact to almost nothing:

```abap
INTERFACE zif_abapgit_definitions.

TYPES: 
  ty_sha1               TYPE zif_abapgit_git_definitions=>ty_sha1,              
  ty_file               TYPE zif_abapgit_git_definitions=>ty_file,               
  ty_files              TYPE zif_abapgit_git_definitions=>ty_files,
  ty_files_tt           TYPE zif_abapgit_git_definitions=>ty_files_tt,
  ty_file_signatures_tt TYPE zif_abapgit_git_definitions=>ty_file_signatures_tt,
  ty_comment            TYPE zif_abapgit_git_definitions=>ty_comment,
  ty_item_state         TYPE zif_abapgit_git_definitions=>ty_item_state,
```

There are a few more I would move or you might need in /git:

```
ty_chmod
ty_create
ty_commit
ty_commit_tt
ty_expanded
ty_expanded_tt
ty_ancestor

c_git_branch_type
c_head_name
c_git_branch
c_type
c_state
c_chmod
c_author_regex
```

**Comment by larshp** [comment]
well, having the same definitions multiple times, then it should be changed sometime anyhow?

yea, there is always more to move

> this is just a start

**Review by mbtools — APPROVED** [review]
moving on :-)

**Comment by larshp** [comment]
will see how much extra breakage there is 😁

**Comment by mbtools** [comment]
https://github.com/abapGit/abapGit/pull/6029#issuecomment-1413810169 somehow missed abapGit/CI (https://github.com/abapGit/CI/pull/211) 😉

**Comment by larshp** [comment]
rule `"unknown_types": false,` is disabled in CI

**Pull request merged**
