### PR TITLE
UI repo over tweaks

### PR DESCRIPTION
**Pull request by sbcgua**
to #5781, after #5788, #5789

- fix bug accessing Remove command on toolbar
- fix bug accessing D (diff) hotkey
- improve table navigation hotkeys (added numpad up and down)
- improve table footer html structure
- proper (minimal) size for the go-to button
- rework go-to button a bit, a more visible icon ... but mainly larger click area around
- dedicated css styles (`repo-overview` class, before it was `db_tab` for some unknown reason)
- some, a bit arguable, cleanups in js/css interaction - js used `repo` class to identify table rows, the class didn't have any styles in fact, and was used for selection only. I changed it to `repo-overview tbody tr`. Which is more direct (though a bit less readable :( )

image

### CODE REVIEW

**Comment by sbcgua** [comment]
OK, this one is ready for review and comments.

abaplint - seems to be a false positive ? It is kind of one line ... just the string segmentation ... otherwise it will be longer than 120 which will trigger another rule ?
image

**Comment by larshp** [comment]
it should take that into account, https://github.com/abaplint/abaplint/blob/main/packages/core/src/rules/keep_single_parameter_on_one_line.ts#L53

**Comment by mbtools** [comment]
these oddly wrapped string templates should be avoided.

Use: 

'''abap
s = |...| 
  && |...|.
'''

**Comment by sbcgua** [comment]
fixed

**Comment by mbtools** [comment]
Functionality is all good and we could merge it.

My concern is the consistency of the UI. It wasn't great before, but it still could be better. The look and feel of the HTML tables on "Repo Overview" and "Repo View" are quite different:

image

image

Diffs:
- Background behind the nav bar
- Background of the table
- Table border 
- Table header font and colors
- Hover color

I think the "Repo View" design is more aligned with the rest. The blue/light blue hover is better in "Repo Overview" but would not work with a blue table header.

We standardized all other controls, can we work towards some standard for HTML tables?

**Comment by sbcgua** [comment]
Hmmm. These are all good points. Yet I didn't target to align the design in all pages honestly. To the better or worse. In general, fixing CSS for this PR, and also not for the first time, I though that current CSS structure leave a lot of room for unification and simplification. Many sections are just duplicated. 

However, I don't think we should focus unification (too much) in this PR ... it will just take forever ... I'd suggest fixing easy things and go on. And separate the remaining comment into an issue.

Now quickly to what can be fixed here.
1) nav bar bg - I'll check, but I'm almost sure it is a visual illusion
2) table bg - yeah, it was white. I changed it to `--theme-container-background-color` (which is f2f2f2) to align with dark theme at the very end. But. Side by side I like repo view (white) better. So I'll change it back. Somehow ...
3) table border - you mean that overview does not have it ?
4) tab header color is probably the same ... and style - do you prefer bold or normal like in repo view ? (I'm tentative)
5) Hover color vs COLORED tab header. Hmm ... yes, they will conflict. But that may mean that tab header should not be colored. Because we have hover and then selected row and then tab header. So using the same tint will not work anyway. Will do some small experiments. And also open for constructive ideas. But it is not a simple issue I'm afraid.

Anyway. Let's fix some small thing. But I'd not dive into "conceptual redesign" - it may be a separate and big subject.

Yet thank for good points :+1:

**Comment by mbtools** [comment]
css refactor is a separate issue, indeed. we have https://github.com/abapGit/abapGit/issues/3530. Fabian had started on it in https://github.com/abapGit/abapGit/pull/3956. 

doing small steps is fine 👍 

1. +2. background colors +

  - body: #E8E8E8
  - main area: #F2F2F2 (between the double horizontal lines)
  - table: #FFFFFF

    for the overview, the main area behind the nav.bar is #E8E8E8 but should be #F2F2F2 (and table should be white as you said)

3. yes, add a light border (if the contrast between backgrounds is high enough then I'm ok without borders but we have just light shades of gray so a little border is helpful)

4. +5. i prefer regular font, darker font and background colors compared to the table body (i like to use a gray tone since i associate things colored with interactive elements. so actually, the blue header on the repo view should be gray).

**Comment by sbcgua** [comment]
image

- `--theme-table-border-color`
- `--theme-table-cell-border-color`
- generally aligned with repo table style (+-)
- also added header shade. Better than I thought ... yet ... well ... will do. Gray tone - not sure, there are too many light gray shades on the page already. If choose gray, then maybe darker gray with light text color. But then repo styles will need to be changed as well ... I'd suggest doing it separately, maybe. 

Imho not bad. Thanks for the comments. Pretends to be final for my taste. :) 

BTW I removed `font-size smaller` ... although it made sense because of lots of data on the page. So condensed font made sense. On the other hand it was not in-line with all other pages. So I tentatively removed it.

Also I'd reconsider overflows (together with pkg/branch/user icons in cells). But honestly a bit lazy to do it now. 
image

Maybe if no major objections, let's merge soon. I'd like to finish the label feature which was the main goal of this all ;).

**Comment by mbtools** [comment]
this looks awesome. i see you used more CSS variables. nice. 

we'll tackle the view with details separately. maybe we go for a two-line approach (like "object/files" in repo view). 

will give it a try tomorrow

**Comment by mbtools** [comment]
`font-size:12pt` (16px) feels quite big and causes wrapping (depends on content, of course):

image

`font-size:smaller` is 13.33px, i tried `font-size:14px` which is a bit closer to the rest and works well:

image

**Review by mbtools — APPROVED** [review]
LGTM 👍

**Pull request merged**
