### PR TITLE
WIP theme refactoring

### LINKED ISSUE #3530: Refactoring: CSS for Themes
The theme css files are full of different color codes. Surprising that the default look of abapGit is relatively consistent. However, it's really not especially in dark mode. Creating a new theme - for example high contrast for accessibility - would be a major undertaking. 

Goal: All theme colors should be defined by variables. 

Todo: Map all individual color codes to theme variables:

Scope:

ZABAPGIT_CSS_THEME_BELIZE_BLUE
1 color

ZABAPGIT_CSS_THEME_DARK
7 background-colors, 2 border-colors, 16 colors 

ZABAPGIT_CSS_THEME_DEFAULT 
33 background-colors, 31 border-colors, 29 colors

### PR DESCRIPTION
**Pull request by flaiker**
Draft pull request mainly to indicate work being done. Not ready for review. Feel free to change UI related stuff while this is open. Some ideas I am trying out:

- Make the default theme CSS not the base CSS but rather independent like the other themes
- Merge colors etc back into the common css file using the variables from the theme specific css files
- Add lots of more variable usages to get Quartz Dark to work without redefining lots of stuff like the current dark theme does
- Use color values by using a color picker on screenshots from SAP GUI instead of using the values from experience.sap.com as for some reason they are not exactly identical
- Clean up the CSS files in general (remove commented code and unused styles)

I added a theme test page to make things easier to see and debug (not finished).

image

Hopefully fixes #3530

### CODE REVIEW

**Comment by flaiker** [comment]
I strongly disagree with [line_break_multiple_parameters](https://rules.abaplint.org/line_break_multiple_parameters) by the way. This is not a problem at all when using prefixes! :)

**Comment by mbtools** [comment]
Nice. I was looking for such test page. The input section should use the new HTML form class. Or maybe we should have a separate test page for forms that also can be used to validate form actions. 

Discuss line_break_multiple_parameters here https://github.com/abaplint/abaplint/issues/1400

**Comment by pokrakam** [comment]
> I strongly disagree with [line_break_multiple_parameters](https://rules.abaplint.org/line_break_multiple_parameters) by the way. This is not a problem at all when using prefixes! :)

I don't really get that. Prefixes make it worse IMHO:

`data(foo) = calculate( start_val = minimum increment = step_size ).`

`data(lv_foo) = calculate( iv_start_val = lv_minimum iv_increment = lv_step_size ).`
Urgh.
```
data(foo) = calculate( 
                start_val = minimum 
                increment = step_size ).
```
Much better :-)

**Comment by mbtools** [comment]
I really love quartz **dark**

**Comment by mbtools** [comment]
Something to consider https://github.com/abapGit/abapGit/issues/4018

**Comment by flaiker** [comment]
I currently don't have time to follow through with this unfortunately. Closing for now.

**Pull request closed without merging**
