### PR TITLE
Package Structure - Part 4

### PR DESCRIPTION
**Pull request by mbtools**
$ABAPGIT_OBJECTS_CORE:

ZCL_ABAPGIT_DEPENDENCIES
ZCL_ABAPGIT_FILE_STATUS
ZCL_ABAPGIT_FOLDER_LOGIC
ZCL_ABAPGIT_OBJECTS_ACTIVATION
ZCL_ABAPGIT_OBJECTS_FILES
ZCL_ABAPGIT_SERIALIZE
ZCL_ABAPGIT_TADIR
ZIF_ABAPGIT_TADIR
ZCL_ABAPGIT_SKIP_OBJECTS

$ABAPGIT_OBJECTS_TEXTS:

ZIF_ABAPGIT_LANG_DEFINITIONS

#4253

### CODE REVIEW

**Comment by larshp** [comment]
ZCL_ABAPGIT_OBJECTS is the entry to object serialization, its now in /objects/core/

object specific serialization logic is in /objects/

I see the object serialization entry to be "super" to the object specific serialization logic

**Comment by larshp** [comment]
build failing: looks like a bug in [abapmerge](https://github.com/larshp/abapmerge)

**Comment by mbtools** [comment]
Suggest moving `zcl_abapgit_objects=>ty_serialization` to `zif_abapgit_objects`.

**Comment by larshp** [comment]
yea, try moving zcl_abapgit_objects=>ty_serialization to zif_abapgit_objects

**Comment by mbtools** [comment]
Yay, that worked. I will remove `ty_serialization` from `zcl_abapgit_objects` in a separate PR.

**Comment by larshp** [comment]
ZCL_ABAPGIT_OBJECTS is the entry to object serialization, its now in /objects/core/

object specific serialization logic is in /objects/

I see the object serialization entry to be "super" to the object specific serialization logic

**Comment by mbtools** [comment]
I had moved `zcl_abapgit_objects` back already (not part of this PR anymore)

**Comment by larshp** [comment]
oh, okay 👍

**Comment by larshp** [comment]
the DEVC file is missing in the /objects/core/ folder?

image

**Comment by mbtools** [comment]
ooops. added it.

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint/issues/1608 opened to avoid the DEVC issue in the future

**Pull request merged**
