### PR TITLE
VIEW: Fix deserialize of maintenance views

### LINKED ISSUE #4306: unable to pull views via abapgit
Hi everyone,

we have a problem that we cannot pull (or reset for that matter) views over abapgit.
For testing i created a new package and repository and commited a maintenance view including table maintenance and tried pulling that on another system:

vt1CCPRfOr

is this a genereal problem or are we doing something wrong?

### PR DESCRIPTION
**Pull request by mbtools**
Maintenance views can have dependencies on tables with foreign keys. Such cases can lead to errors during deserialize since the foreign key relationships between tables are processed only in the "late" step.

This fix moves the processing of maintenance views (viewclass = c) to the "late" step.

Closes #4306

### CODE REVIEW

**Comment by larshp** [comment]
@schealex can you help testing this change?

**Comment by schealex** [comment]
@larshp will test tomorrow. Thanks for the quick help with this!

**Comment by schealex** [comment]
i switched to the mbtools/view_maint branch but still was unable to pull the view:

prhIaND7hX

can i provide any additional information?

**Comment by schealex** [comment]
tested after your merge, seems like it's working now. I've asked a collegue to verify will come back to you shortly!

**Comment by larshp** [comment]
thanks @mbtools & @schealex, merging 👍

**Pull request merged**
