### PR TITLE
Improve confusing progress message (seemingly always 200 objects)

### PR DESCRIPTION
**Pull request by ConjuringCoffee**
### The problem and its cause
When committing large packages using the background mode, I always found the progress message confusing. It seemed like the progress message always said it always had processed only 200 objects, like this:

`Encoding objects ( 200 of 347 )`

Sometimes, the message would be on the screen for a very long time.

The root cause: The message is shown after 200 objects each. If the repository contains 347 objects like in the example, then the message is shown a single time. 

The message is not shown if there are fewer than 200 objects because the first `MOD 200 = 0` occurs at index 200. This means that if the next batches all contain fewer than 200 objects, then the message from the bigger batch will stay on screen the entire time.

### First failed attempt

My first implementation was to display a range of objects currently processed. This would have displayed the following messages for my example:
* `Encoding objects (0 to 200 of 347)`
* `Encoding objects (201 to 347 of 347)`

This was confusing too because if the encoding was fast, then the second message wouldn't be displayed. That's because `ZCL_ABAPGIT_PROGRESS` only shows messages after two seconds have passed.

### Proposed result

I ended up with a simpler result: 
* Do not display the number of objects already encoded (the percentage displayed already gives a good idea about that)
* Show the message at index 1 too 

I find this to be a good balance of user experience, performance and complexity. I hope you like it 😊

### CODE REVIEW

**Comment by ConjuringCoffee** [comment]
Can anyone tell why the unit test is failing? The tests of `ZCL_ABAPGIT_GIT_PACK` are all successful on my system 😟

**Comment by ConjuringCoffee** [comment]
Hmm, actually I think the better solution would be to simply rely on the timer within `ZCL_ABAPGIT_PROGRESS`. The timer was introduced half a year after the check for the 200 objects was introduced. That should make the check for the 200 objects obsolete. I'll change my implementation accordingly...

**Comment by mbtools** [comment]
Looks like the previous UT didn't reach 200 objects and therefore no progress message was raised. Try injecting a mock for the progress message.

**Comment by ConjuringCoffee** [comment]
(Interesting, I didn't expect the naming convention of `LTCL_` to apply to all `FOR TESTING` classes. So far I've only seen this convention for actual test classes (classes containing tests), not all `FOR TESTING` classes.)

**Comment by fabianlupa** [comment]
ltd_my_double and lth_my_test_helper are somewhat common and should also be allowed by the config.

**Review by mbtools — APPROVED** [review]
lgtm 👍

**Comment by larshp** [comment]
side note: in the beginning `IF sy-tabix MOD 200 = 0.` was a performance optimization to avoid showing the progress too often, now-a-days theres a check inside the progress to only show it every 2 seconds

**Pull request merged**
