### PR TITLE
Add icon link for changing remote repo on the list

### PR DESCRIPTION
**Pull request by wozjac**
Proposition for #4737

### CODE REVIEW

**Comment by wozjac** [comment]
@larshp It is set to "Allow all actions".

**Comment by larshp** [comment]
hmm

**Comment by FreHu** [comment]
Tested the button, it works. Thanks for the contribution!
as for the build issue, is it perhaps the "allow edits from maintainers" checkbox that people sometimes don't check when submitting the PR?

**Comment by larshp** [comment]
looks like https://github.com/abapGit/abapGit/pull/4920 worked as expected

**Pull request merged**
