### PR TITLE
Create an interface for online repo functions

### PR DESCRIPTION
**Pull request by PeregrinTooc**
To make my own code calling online repo functions testable, I need some functions behind an interface. Using aliases, this is a safe refactoring. Please pull :)

### CODE REVIEW

**Comment by larshp** [comment]
Please avoid using ALIASes if at all possible, IMHO there is something wrong in the OO design if aliases are required, we've put in a lot of work removing some of these, see https://github.com/abapGit/abapGit/issues/3531 and https://github.com/abapGit/abapGit/issues/3460

That being said, the REPO classes needs refactoring, see #3799 #2127 #1757

**Comment by PeregrinTooc** [comment]
> Please avoid using ALIASes if at all possible, IMHO there is something wrong in the OO design if aliases are required, we've put in a lot of work removing some of these, see #3531 and #3460
> 
> That being said, the REPO classes needs refactoring, see #3799 #2127 #1757

It is good engineering practice to make small refactorings. It is entirely possible to go through every user of each method and make them call the interface instead of the class, but that is another small refactoring. This solves the immediate problem with minimal changes.

**Comment by PeregrinTooc** [comment]
@larshp What do you think, can we merge this PR, or should I get rid of at least some of the aliases?

**Comment by larshp** [comment]
I'll merge it, just typically leaving it for a bit to allow more people to review

**Pull request merged**
