### PR TITLE
Allow html viewer to be hidden

### PR DESCRIPTION
**Pull request by flaiker**
Currently we mostly use popups or new external modes for the JUMP methods. One reason is you can work with them in parallel but the other is that using the same mode abapGit uses doesn't work because we are using cl_gui_container=>screen0 for the html viewer. When calling CALL SCREEN the container still exists and even is in the foreground hiding the dynpro behind it. You can only see the screen change by looking at the status.

The approach of using another mode works fine as long as there are APIs that you can call to do this. Sometimes there are none available and you also cannot use BDC with ABAP4_CALL_TRANSACTION as the maintenance transaction is not BDC compatible. This is the case for SHI3 type GHIER using transaction SBACH04.

Directly calling `STREE_EXTERNAL_EDIT` results in this (only status changes):

image

With hiding and showing the HTML viewer:

image

```abap
  METHOD jump.
    (...)

    zcl_abapgit_ui_factory=>get_html_viewer( )->set_visiblity( abap_false ).

    CALL FUNCTION 'STREE_EXTERNAL_EDIT'
      EXPORTING
        structure_id   = lv_structure_id
        language       = mv_language
        edit_structure = abap_false
        no_commit_work = abap_false
        activity       = 'D'
      IMPORTING
        message        = ls_message.
    IF ls_message IS NOT INITIAL.
      MESSAGE ID ls_message-msgid
        TYPE 'S'
        NUMBER ls_message-msgno
        WITH ls_message-msgv1 ls_message-msgv2 ls_message-msgv3 ls_message-msgv4
        DISPLAY LIKE ls_message-msgty.
    ENDIF.

    zcl_abapgit_ui_factory=>get_html_viewer( )->set_visiblity( abap_true ).
```

This unfortunately couples _OBJECTS to _UI (and even to the concrete implementation instead of GUI). Which seems kind of unavoidable when JUMP is located in OBJECT.

I also refactored get_html_viewer in the factory as it for some reason was not really using a singleton pattern. Not sure if that was intentional.

### CODE REVIEW

**Comment by mbtools** [comment]
Interesting. Now I understand the screen logic much better. Thx.

I'm trying hard to separate the object layer ($abapgit_objects) from the rest (repo & UI) in order to build a standalone installer. Changing the visibility should be done in `zcl_abapgit_gui_router->sap_gui_actions` (before and after the jump call).
https://github.com/abapGit/abapGit/blob/master/src/ui/zcl_abapgit_gui_router.clas.abap#L586

The gui_action needs to query the object as to what behavior is necessary (ie. does the viewer need to be hidden or not). It's another case of object-specific logic. Coud be an if type = ... (bad but we have done it in other places), or new interface, or a metadata flag... not sure. Maybe an "if" until we solve https://github.com/abapGit/abapGit/issues/4187?

**Comment by flaiker** [comment]
That makes sense. We can also just always hide and show it around this method:

https://github.com/abapGit/abapGit/blob/cac7cd42fb6aeecc5320a6fde2b646e37893fe6e/src/ui/zcl_abapgit_gui_router.clas.abap#L586

If it's in the same mode it will work as stated in the example. If it uses a popup the screen behind it will be blank (not a big problem). If it uses a new window the viewer will be visible again. Then we don't need the distinction I think (haven't tested yet).

**Comment by flaiker** [comment]
I moved the call to the router. Is the call to the UI factory okay or should the access happen through ii_event->mi_gui_services for example?

Tested fine. For asynchronous jumps the screen flickers for a moment which should be fine for now.

**Review by mbtools — APPROVED** [review]
LGTM. Nicely keeps the UI logic away from objects.

**Pull request merged**
