### PR TITLE
update ajson with writer

### PR DESCRIPTION
**Pull request by larshp**
testing update with code from https://github.com/abapGit/ajson_mirror

#3441

### CODE REVIEW

**Comment by larshp** [comment]
Pending https://github.com/sbcgua/ajson/pull/33

**Comment by larshp** [comment]
Pending https://github.com/sbcgua/ajson/pull/34

**Comment by larshp** [comment]
some bugs with exceptions,
image

**Comment by larshp** [comment]
two warnings, but I think this is expected,

image

**Comment by mbtools** [comment]
The warning is because of the different super class. 

In abapGit it's this:

image

in the mirror:
```abap
class zcx_abapgit_ajson_error definition
  public
  inheriting from CX_STATIC_CHECK
  final
  create public .
```

**Comment by larshp** [comment]
the two warnings can now be found by abaplint, which will help in the future

there are also some false positives, which I will look into,

image

**Comment by larshp** [comment]
pending https://github.com/abapGit/abapGit/pull/4312, after its merged the exception warnings should appear in the CI

**Comment by larshp** [comment]
here we go,
image

**Comment by mbtools** [comment]
nice linting. I don't think there's a generic replacement to fix the issue though (ie. change the super class). might be better to keep the mirror as is and adjust the ajson usage in abapGit to catch `zcx_abapgit_ajson_error` (instead of relying on inheritance).

**Comment by larshp** [comment]
yes, the plan is to change abapgit to catch the ajson exception and change it into an abapgit exception

**Comment by larshp** [comment]
ready for review

note that the AJSON code is mirrored from https://github.com/abapGit/ajson_mirror, ie. errors for ajson should be reported to https://github.com/sbcgua/ajson

**Comment by mbtools** [comment]
looks good. it would be a bit nicer if we send the mirror through a pretty print with AG rules. 

/json/ might need a protection against PRs from abapGit repo since it's now mirrored.

**Review by mbtools — APPROVED** [review]
👍

**Comment by larshp** [comment]
exception classes are ignored just like the other abapGit code

the other classes are upper cased to follow abapgit conventions where possible

**Comment by mbtools** [comment]
oh, i forgot that i hacked my system to edit and pp exception classes, too

**Pull request merged**
