### PR TITLE
Add support for BMFR (Application Component)

### LINKED ISSUE #2108: BMFR: Application Component
Transactions SBAC, SBACH02 - SBACH05
Package SDFM
Report SBMCV000 to generate a prefix number range

### PR DESCRIPTION
**Pull request by flaiker**
Fixes #2108
Test repo https://github.com/abapGit-tests/BMFR/pull/1

Also see comments in the issue.

Before importing any BMFR objects you need to run `SBMCV000` to set up a system + client specific prefix and number range which is used as the identifier in TADIR. Since you apparently cannot create objects with external number assignment using the API I mapped the application component id to tadir as the key for the filename. Changing the application component id works as expected (new object shows up, the old one is marked as deleted).

The error message if you try to pull without setting up the prefix number range is quite good though you have to navigate to the longtext using the log.
image

To create application components you need to run the report beforehand anyways. The only time where the prefix number range could be missing but you already have objects is after a system / client copy I think.

Things left to do:
- [ ] Check what happens if you pull a subpackage that uses an application component that was just pulled (may need two step activation)
- [ ] Check how partner namespaces work with this (currently the import parameters in the API are not supplied)
  - In TADIR they show up as /ABC/Z ... 001
  - SBMCV000 shows additional options if they are namespaces registered in the system to generate prefix number ranges using partner namespaces
  - Solution: Use namespace of the package the object is in (if applicable -> non-local)
- [X] Check for other BM** objects if they also have some attribute that can be used as an external key and which other BM** objects are even used nowadays.
  - Couldn't get any relevant objects to work / show up / not shortdump, see https://github.com/abapGit/abapGit/issues/2108#issuecomment-728230712
- [ ] Test error handling when already having the application component id to pull in a different package
- [ ] Check how this works with non local packages and CTS.
- [ ] Edit other objects types that reference the system specific component ids to instead use the general component ids (SHI3, DEVC, ...)

### CODE REVIEW

**Comment by mbtools** [comment]
I think you will also need to implement logic for BMFR in `zif_abapgit_tadir~read_single`.

After SICF, this will be another object type with keys different from TADIR. It works but the implementation in `zcl_abapgit_tadir` should be generic instead. How about we add an *optional* interface `zif_abapgit_object_ext` that can be used by serializer classes?

The following methods should be included to extend the serializer classes so we can make object-specific logic generic (without impacting all serializer classes). BMFR would implement the first two. So I suggest starting with just those two.

Method | Object Type | Comment
------- | ----------------| --------------
TADIR_TO_ITEM | SICF, BMFR | https://github.com/abapGit/abapGit/issues/3453
ITEM_TO_TADIR | SICF, BMFR | https://github.com/abapGit/abapGit/issues/3453
SKIP | DDLS | zcl_abapgit_skip_objects 
FILE_CHANGED_BY | FUGR, CLAS | https://github.com/abapGit/abapGit/issues/1428
FILE_JUMP | FUGR, CLAS | https://github.com/abapGit/abapGit/issues/1428

**Comment by flaiker** [comment]
DEVC also has different tadir handling by design.

I agree this should be refactored. When using a new interface I would suggest not naming it _EXT but actually grouping by functionality so you don't end up with lots more optional methods that most users don't implement (since we can't use DEFAULT IGNORE). Also it would be difficult to decide what belongs in _EXT and what belongs just in the default one in my opinion.

Should this be part of this PR though or rather before or afterwards?

**Comment by mbtools** [comment]
we can do after. i will create a new issue as reminder

**Comment by flaiker** [comment]
This also causes some dependency issues. I enhanced the component structure using an extension (which is represented by SHI5). I assigned an application component to a subpackage. To uninstall I think the following needs to happen in this order:
- Remove application components from packages (?)
- Remove SHI3 structure
- Remove SHI5 structure
- Remove BMFR
- Remove packages

Also we currently serialize both the technical application component id (uffctr), which is system dependent regarding the generated number range, and the user facing component id (ufps_posid) with the dashes in DEVC. The technical id would have to be removed for this logic to work.

**Comment by flaiker** [comment]
The uninstall issue with dependencies seems to be reproducible without having any BMFR objects in the repo, probably because of SHI3 not being tested with GHIER yet (related #4197). Should be solved outside of this PR first.

After checking the other BM** object types I don't see any others that are relevant to us. Or rather I couldn't even find out the tcode to edit the subset of objects types that are delivered by SAP, see https://github.com/abapGit/abapGit/issues/2108#issuecomment-728230712 . Therefore I'll remove the super/sub-class structure since I don't think it will ever get used.

If we go along with using the dash-based external component id as our identifier in the file name and map it to tadir then we also have to adjust the usages in DEVC, SHI3 and maybe others.

**Pull request closed without merging**
