### PR TITLE
UI: Adjustments to Repo Palette

### PR DESCRIPTION
**Pull request by mbtools**
- Sort alphabetically
- Pad offline icon (using CSS)

Before:

image

After:

image

### CODE REVIEW

**Review by sbcgua — DISMISSED** [review]
Looks good, but I'd suggest another change to CSS. I didn't like the fix, because it is focused on a specific icon and so I was going to suggest another one, with fixed width ... but it didn't work ! So after some minutes of confusion I found the below code at the very end of this file.

```css
.icon-cloud-upload-alt {
    padding-right: 5px;
}
```

Removing it completely solve the alignment issue. And this is what I suggest. Even if that code was used for something it must be more specific. So I'd propose removing it.

The rest looks fine :)

**Comment by mbtools** [comment]
The CSS was added to align the icons on the top:

image

Without it, "New Online" was very close to the icon:

image

Maybe it should be

```css
#toolbar-main .icon-cloud-upload-alt {
    padding-right: 5px;
}
```

Not perfect either.

**Comment by sbcgua** [comment]
Yeap, good catch, I didn't notice. This will do. Not perfect but a lot more specific, so will not interfere.

P.S. Hmm are these spaces hardcoded ?
image

**Comment by sbcgua** [comment]
option 2 ... probably to do in parallel is to adjust that icon - it really is larger
image

**Comment by sbcgua** [comment]
image

Hmm ?

**Comment by sbcgua** [comment]
May take some more time ... :(
image

**Comment by sbcgua** [comment]
Or use other source. svgrepo seems to give icons under public domain
image

**Comment by mbtools** [comment]
smaller icon alt2 looks good

**Comment by mbtools** [comment]
I'm not sure why our cloud icon has an arrow in it? Why not just
https://fontawesome.com/icons/cloud?style=solid

PS: If you don't mind, please add an icon for "user" to the font:
https://fontawesome.com/icons/user?style=solid

**Comment by sbcgua** [comment]
@mbtools have a look at #4112 - submitted some icon and css changes
Also consider cloud-commit icon. solid cloud looks too bulky and heavy on a real page

image

**Comment by mbtools** [comment]
I removed the CSS here since it's addressed in #4112 now. I think this is good to go now

**Review by sbcgua — APPROVED** [review]
works. Thanks !

**Pull request merged**
