### PR TITLE
testing: transpiled abapGit running on web via express js

### PR DESCRIPTION
**Pull request by larshp**
this PR makes the transpiled abapGit run on express js

note that the only changed file in `src` is `src/ui/zcl_abapgit_frontend_services.clas.abap`, all other changes are outside of what users install

next step/PR: add a playwright test that runs against gitea while recording video

### CODE REVIEW

**Comment by larshp** [comment]
so close, 
image

**Comment by larshp** [comment]
image

**Review by mbtools — APPROVED** [review]
One of those things only you could do. Impressive. 

Where is the persistence for the express app?

**Comment by larshp** [comment]
> Where is the persistence for the express app?

sqlite, for testing purposes it starts with initial/empty state. But there is nothing stopping it from persisting to a sqlite file, on backend or in browser

**Pull request merged**
