### PR TITLE
Fix use of sy-langu in object serializers

### LINKED ISSUE #2080: Use of sy-langu in object serializers
Lots of object serializers use SY-LANGU. Is that correct? Or shouldn't they use mv_language?
https://github.com/larshp/abapGit/search?q=sy-langu&unscoped_q=sy-langu

E.g. CUS0:
https://github.com/larshp/abapGit/blob/cf052951703467922b7ec015132a961e13a749f9/src/objects/zcl_abapgit_object_cus0.clas.abap#L76-L103

### PR DESCRIPTION
**Pull request by mbtools**
- Replace `sy-langu` variable with `mv_language`
- Replace `sy-langu` type with `langu` (makes it easier to spot `sy-langu`)
- Enhance generic serializer to use `mv_language`
- Add unit tests to generic serializer 
- Adjust and simplify serializers that are based on generic class

Closes #2080

### CODE REVIEW

**Review by larshp — CHANGES_REQUESTED** [review]
`LANGU` is deprecated, use `SY-LANGU` everyone knows what it is

image

**Comment by larshp** [comment]
and yea, SAP is stupid in this area, and we cannot decide, so we should move in the direction of using approved API stuff

**Comment by larshp** [comment]
we can add LANGU in https://github.com/abapGit/abapGit/blob/main/abaplint.json#L112

**Comment by mbtools** [comment]
LANGU is used in ~20 other places. Will do separate PR with adding it to abaplint

**Comment by larshp** [comment]
ok 👍

**Review by larshp — APPROVED** [review]

**Pull request merged**
