### PR TITLE
UIAD:  Add support for Launchpad App Descriptor Item

### PR DESCRIPTION
**Pull request by ViktoriaFreidel**
This request is a continue the integration of UIAD Object Type and refer to https://github.com/abapGit/abapGit/issues/5958
UIAD is  are added to https://github.com/SAP/abap-file-formats.
As well, UIAD support ABAP Language Version

### CODE REVIEW

**Comment by larshp** [comment]
thanks, can you help adding an example to https://github.com/abapGit-tests/UIAD ?

**Comment by ViktoriaFreidel** [comment]
Example added to https://github.com/abapGit-tests/UIAD

**Review by larshp — APPROVED** [review]
lgtm

**Comment by mbtools** [comment]
Please add `UIAD` to https://docs.abapgit.org/user-guide/reference/supported.html 👍 

Will you do `UIAC` (https://github.com/abapGit/abapGit/issues/5958) as well?

**Pull request merged**
