### PR TITLE
Add ignore option to all objects in stage screen

### PR DESCRIPTION
**Pull request by FreHu**
After #4056 

Adds ignore option everywhere. This allows to ignore an unsupported object without going to the repo settings.

### CODE REVIEW

**Comment by FreHu** [comment]
Alternatively, as my point was consistency in the columns - we could remove the ignore option from stage as it's kinda marginal and only allow to maintain the ignore list from settings.

**Comment by mbtools** [comment]
I didn't know that "ignore" on the stage page adds to the ignore list. it would be indeed a rare thing. +1 for removing it.

**Comment by FreHu** [comment]
@sbcgua @larshp @christianguenter2 any strong feelings about this?

**Comment by larshp** [comment]
no strong feelings, but suggest to dont have the ignore option, would rather have users move towards supporting additional object types

this pull request also contains the code from https://github.com/abapGit/abapGit/pull/4056/files ?

**Comment by FreHu** [comment]
I will open another PR as we decided on the opposite anyway.

**Comment by sbcgua** [comment]
sorry for late response, very busy these days :(
- I think all files have to be equal in this respect. So all should be ignorable - it is a right idea
- I even have one object to ignore ... a BAPI ... it would take lots of effort to implement the support :(((
- I also agree that it is a rare function, so from UX perspective probably should be removed from the main path

**Pull request closed without merging**
