### PR TITLE
SKTD - Knowledge Transfer Document

### PR DESCRIPTION
**Pull request by larshp**
https://github.com/abapGit-tests/SKTD

https://help.sap.com/docs/SAP_S4HANA_CLOUD/25cf71e63940453397a32dc2b7676947/fb51cd65f7f047b7b65b9a08f4e202c0.html

https://github.com/abapGit/docs.abapgit.org/pull/158

nothing fancy, just something that works(?)

Note: the actual text is in hex, I guess it wont matter much, if using git then users will write real markdown documents? Plus AFF will sometime get a real definition for SKTD, so no need to invent a format now?

### CODE REVIEW

**Comment by mbtools** [comment]
I tried it in 754 but `CL_KTD_OBJECT_DATA=>TY_KTD_DATA` does not exist (all the classes are there):

image

Is this supposed to work on 754?

**Comment by larshp** [comment]
I dont know tested ok on 757, anyhow, lemme open another PR

**Comment by xtough** [comment]
What about https://github.com/SAP/abap-file-formats/pull/270 ?
@larshp I fear that we now will have to deal with 2 incompatible formats, right?

**Comment by larshp** [comment]
no, we got 3 incompatible formats now 😁 I didnt put much effort into this implementation, as it will eventually move to AFF, as https://github.com/SAP/abap-file-formats/pull/270 is not merged

**Pull request merged**
