### PR TITLE
SAPGUI 770 patch 2 chromium control - several fixes

### PR DESCRIPTION
**Pull request by christianguenter2**
Fixes several issues from #4841 which occur with SAPGUI 770 patch 2 and chromium browser control

- convert actions always to lower case
- back navigation fixed as URL in SAPGUI browser control has changed
- JS logic for determining SapEvent-prefix matching new SAPGUI browser control logic
- Diff view: Convert path and filename always to lower case. As chromium control sends them newly in uppercase.

Tested with SAPGUI 770 patch 2 chromium and IE. Needs thorough testing with different SAPGUI versions and configurations.

### CODE REVIEW

**Comment by jrodriguez-rc** [comment]
There is the same problem with `getdata`, it is always uppercase
image

I think that the best solution is to report an incident to SAP, I was testing report `saphtml_events_demo`.

With IE control:
image

With Edge control:
image

**Comment by mbtools** [comment]
Agree. These are bugs that SAP must fix:
- Changing the prefix from `saphtml:` to `http:`
- Uppercase of action and getdata responses

**Comment by christianguenter2** [comment]
@jrodriguez-rc already any news from SAP?

**Comment by jrodriguez-rc** [comment]
No news, still in "Sent to SAP" status

**Comment by jrodriguez-rc** [comment]
Changed to "In processing by SAP"

**Comment by jrodriguez-rc** [comment]
Update: SAP sent me a patched version of GUI, the event and getdata are now with the correct case, but I reported more issues that I haven't reported initially:
- URL changes
Internet Explorer (and Edge 7.70 PL1):
saphtmlp://htmlviewer.sap.com/0b3WPqjo7jkqrVigXcMsk0/HTML000002.htm
Edge 7.70 PL2
https://saphtmlp//htmlviewer.sap.com/0b3WPqjo7jkqrWTp6%7BmskW/HTML000002.htm
- Delay in each event

**Comment by jrodriguez-rc** [comment]
Update: A temporary fix will be provided (if I understood correctly), and they are working with Microsoft for a permanent fix.

Note: Correction is not provided in PL02 hotfix 1

**Comment by jrodriguez-rc** [comment]
Update: I tested a binary with the fix for actions/navigation and it seems to work.

The problem with the delay is still pending (I just tested a binary for Edge HTML control).

It is registered in note [2901278 - SAP GUI HTML Control based on Chromium Edge: Legacy HTML does not work (correctly) / present limitations](https://launchpad.support.sap.com/#/notes/2901278), under "Performance when invoking the HTML Control" section.

**Comment by larshp** [comment]
guess we are waiting for feedback regarding the note?

**Comment by jrodriguez-rc** [comment]
The problem is not from abapGit, so I think that this PR will be closed and continue with issue #4841

**Comment by christianguenter2** [comment]
Closing. Patchlevel 3 is expected to ship on August 19. Let's see whether there is any progress.

**Pull request closed without merging**
