### PR TITLE
Repo view - show paths below object name

### LINKED ISSUE #5322: Repo page - paths under object name
I randomly tried this change and I think it's just straight up better. Any good reasons why we would not want the paths under the object name?
image
image
image

### PR DESCRIPTION
**Pull request by FreHu**
resolves #5322 

- Move path column to below the object name
- If package has transports, request column will be shown (before it was just an icon)
- Vertically aligned columns to the top in case there are a lot of files in your object
- the column order more resembles staging

image
image
image
image

### CODE REVIEW

**Comment by FreHu** [comment]
@larshp something unrelated is wrong with the build, the last commit in main also has these failures
```
Error: check_syntax, Method parameter type not compatible, zcl_abapgit_ajson.clas.testclasses.abap:3044
check_syntax, Method parameter type not compatible, zcl_abapgit_ajson.clas.testclasses.abap:3049
check_syntax, Method parameter type not compatible, zcl_abapgit_ajson.clas.testclasses.abap:3051
check_syntax, Method parameter type not compatible, zcl_abapgit_ajson.clas.testclasses.abap:3053
check_syntax, Method parameter type not compatible, zcl_abapgit_ajson.clas.testclasses.abap:3058
check_syntax, Method parameter type not compatible, zcl_abapgit_repo.clas.testclasses.abap:122
check_syntax, Method parameter type not compatible, zcl_abapgit_repo.clas.testclasses.abap:1[27](https://github.com/abapGit/abapGit/runs/5053354049?check_suite_focus=true#step:4:27)
check_syntax, Method parameter type not compatible, zcl_abapgit_repo.clas.testclasses.abap:1[32](https://github.com/abapGit/abapGit/runs/5053354049?check_suite_focus=true#step:4:32)
check_syntax, Method parameter type not compatible, zcl_abapgit_services_basis.clas.testclasses.abap:203
check_syntax, Method parameter type not compatible, zcl_abapgit_services_basis.clas.testclasses.abap:210
check_syntax, Method parameter type not compatible, zcl_abapgit_log.clas.testclasses.abap:186
```

**Comment by larshp** [comment]
correct finding by abaplint, fixed in https://github.com/open-abap/open-abap/pull/250/commits/a51571c140ed6cf7fb6a7ef39b456b5042f46e18

**Comment by mbtools** [comment]
Nicely done ✅

**Review by sbcgua — CHANGES_REQUESTED** [review]
I'd probably render filenames in a lighter color: now they are kind of emphasized more than the object name ... imho ... I don't use file display option so honestly just a stylistic opinion

Speaking about "don't use file display" - it doesn't work propely - extra space is displayed
2022-02-06_14h53_05

Otherwise a very nice improvement imho, much cleaner than a separate column with files :+1:

**Comment by sbcgua** [comment]
Also maybe use of `'<br>'` can be avoided, as there is no good controls from CSS over it

**Comment by FreHu** [comment]
I will rearrange how the lines currently are - the whole object is a `<tr>`, but now each file can be its own line. This should remove the need for `<br>`  and it will also improve the selected line highlight.

**Comment by FreHu** [comment]
image

**Comment by FreHu** [comment]
I remembered this old issue but I will not be changing any more columns in this PR, just food for thought.

**Pull request merged**
