### PR TITLE
Serialize INTF description in json similar to xml

### PR DESCRIPTION
**Pull request by marcushoepfner**
in xml, method parameter description, event parameter description, ... are not serialized.
in json they are, but they cannot be deserialized.
hence remove serializtion in json case as well.
xml and json serialization behaves similar now

### CODE REVIEW

**Comment by larshp** [comment]
the descriptions are being added to the xml, https://github.com/abapGit/abapGit/pull/5575

so I dont think we need to remove it from json, we need to add it to xml

**Comment by mbtools** [comment]
keep it in draft. i will get back to #5575 next week

**Comment by mbtools** [comment]
@marcushoepfner The XML now includes all *shorttexts* with https://github.com/abapGit/abapGit/pull/5755. 

PS: https://github.com/abapGit/abapGit/pull/5575 is about *longtexts*

**Comment by marcushoepfner** [comment]
not needed anymore, xml and json now serialized and de-serialized correctly w.r.t. to sub components texts

**Pull request closed without merging**
