### PR TITLE
html event abstraction, phase 3 - query

### PR DESCRIPTION
**Pull request by sbcgua**
to #3602

query method in event class. + UTs

WIP for now. TODO: 
- [x] see how to integrate query in current usages of `mv_getdata`
- [X] lots of `some_command?repo_key` -> refactor into `some_command?key=repo_key` to reuse uniformely via query
- [ ] additional attention to `cl_http_utility=>unescape_url( escaped = lv_value )` - used in `get_field` but not used in `parse_fields` currently - may be a problem

UPD: see comment below

### CODE REVIEW

**Comment by mbtools** [comment]
missing escape for urls and html attributes in general is a problem indeed. instead of using string templates or concat, urls should be composed via string map where we could easily add the escaping. there's always another refactor ;-)

**Comment by sbcgua** [comment]
OK, this is ready to review and test. Could be a bit messy. Appeared to be a lot of small changes.
Main goal was: to remove usage of `ii_event->mv_getdata` and use `ii_event->query( )` instead

- `ii_event->query( )` returns string map with uppercased (by default) params from url (`k1=v1&k2=v2...`). Can be not uppercased too (not sure that it is needed but I implemented it too).
- Params can be retrieved by `ii_event->query( )->get( 'XXX' )` or `ii_event->query( )->to_abap( changing ... )`
- there was one place where I didn't refactor `ii_event->mv_getdata` - background pages. There is some complex logic of dynamic calling of class, received from param (!!! see `ZCL_ABAPGIT_GUI_PAGE_BKG->DECODE`) ... and I don't use this feature so I decided not to touch it or I'd break something :) BTW, dynamic call of a class, named by a received param look rather insecure ... :)
- rest of direct `mv_getdata` were eliminated, together with part of action utils
- also made all links that address a repo to uniformely address it via `?key=1234` instead of just `?1234`

This should be tested a bit ... I'm not sure that I found all occurances of repo key urls. Though repo overview, stage, commit, diff, palettes, dbutils work.

One more concern is url unescape. I removed some of `cl_http_utility=>unescape` on the way. But action utils use own and simplified `ZCL_ABAPGIT_HTML_ACTION_UTILS=>UNESCAPE` with a comment (and UT) that suggest not to use `cl_http_utility`. So ... might be some issues with that potentially. Solution is: either to improve own tool, or use `cl_http_utility` where it is needed specifically (I'm sure there are not so many cases where it will be really needed)

**Comment by sbcgua** [comment]
... and docs respectively

**Comment by larshp** [comment]
thanks 👍 merging

**Pull request merged**
