### PR TITLE
JavaScript lint/format

### PR DESCRIPTION
**Pull request by mbtools**
Formatting for consistency (no code changes):

- Brackets
- Spacing
- Alignment of assignments

It's one-time for the fun of it.

### CODE REVIEW

**Comment by larshp** [comment]
@sbcgua can you help reviewing this change?

**Comment by sbcgua** [comment]
Ok, I'll check.

**Review by sbcgua — COMMENTED** [review]
Nothing blocking, in fact just a nice formatting. But I have a couple of doubts

1) I find `function ()` (space after function) rather untypical. Also it is not consistent in code because this format is applied to nameless function only. I'd rather say it improves the readability in the given code but I wouldn't require that (as a linter rule or something)
2) removing the alignment of `=`. If there is a formatting option to keep it, maybe better keep it. This point is arguable, I can name at least one serious downside of `=` alignment. But readability is better. And this approach is used in abap in AG too.

Also to mention, it would be easier to review if formattings are in separate commits from code changes. :)

@mbtools, could you pls comment on 1 and 2.

**Comment by mbtools** [comment]
sorry, for the mix. it was the typical flow, you make changes and then press pretty... 

I noticed 1) and 2) as well and wasn't excited about it. I will check if there are better options (also to persist these lint/pretty settings).

**Comment by mbtools** [comment]
Splitting into separate PRs

**Comment by mbtools** [comment]
@sbcgua should be in good shape now

**Review by sbcgua — APPROVED** [review]
Yeap, looks good :+1:

**Pull request merged**
