### PR TITLE
Push tags to builds

### PR DESCRIPTION
**Pull request by sbcgua**
to #5784

This should work in theory ... though potentially may require a fix or two ...

### CODE REVIEW

**Comment by sbcgua** [comment]
@larshp would you mind if I merge it ? I'll be tracking the job logs for a while (especially after the next version) and will fix if it fails (it is difficult to recreate the test environment for this, in my own repo I just push the fixes until it starts working ...)

**Review by larshp — APPROVED** [review]
feel free to merge

**Comment by sbcgua** [comment]
OK, merging then.

**Comment by sbcgua** [comment]
didn't crash so far ... already good :)

**Pull request merged**
