### PR TITLE
Fix "Unexpected package naming" error

### LINKED ISSUE #5728: PREFIX: Unexpected package naming - can also be due to previously existing object
Just for information: I noticed this error can also occur when an object was previously manually created on the target system, with a different package.
Not sure how this can be nicely documented. I suppose you have already though about a generic section "problems & solutions" section  in the documentation.
Maybe make the check more specific, and issue a more specific message.

### PR DESCRIPTION
**Pull request by mbtools**
Before:

Previously, when an object existed in the repo and locally but was *not* included in the package hierarchy of the repository, you would get the following error (when opening the repo):

image

Test case in https://github.com/abapGit/abapGit/issues/5728

After:

With this PR, log messages will list all objects that are not included in the package hierarchy. 

image

When pulling, the popup will show these objects and ask for confirmation to overwrite. I added an icon and description to the "package overwrite" popup similar to the "object selection" popup.

image

After confirming, the existing object is overwritten with the remote version and assigned to the correct package:

image

Closes #5728

### CODE REVIEW

**Comment by larshp** [comment]
@vonglan can you help testing this change?

**Comment by vonglan** [comment]
currently on holiday (2 weeks), will look into it when I am back at work

**Comment by larshp** [comment]
@vonglan did you have time to test? 🍹

**Comment by vonglan** [comment]
Tested successfully!

**Pull request merged**
