### PR TITLE
Refactor serializer constructor

### PR DESCRIPTION
**Pull request by mbtools**
Cleaning up a few messy spots:

1. Remove `global friend` from `zcl_abapgit_objects_super`
2. Move `mo_files` from `zif_abapgit_object` to `zcl_abapgit_objects_super`
3. Move setting `mo_files` from serialize class to constructor
4. Simplify `zcl_abapgit_object->create_object`

This could break custom serialize classes (`zcl_abapgit_object_z...`) but adjusting is simple:

- If `constructor` is used, it needs to be replaced with 

```
    METHODS constructor
      IMPORTING
        !is_item        TYPE zif_abapgit_definitions=>ty_item
        !iv_language    TYPE spras
        !io_files       TYPE REF TO zcl_abapgit_objects_files OPTIONAL
        !io_i18n_params TYPE REF TO zcl_abapgit_i18n_params OPTIONAL
      RAISING
        zcx_abapgit_exception.
```

- If `super->constructor` is called it needs to be replaced with

```
    super->constructor(
      is_item        = is_item
      iv_language    = iv_language
      io_files       = io_files
      io_i18n_params = io_i18n_params ).
```

- If `zif_abapgit_objects~mo_files` is used, it needs to be replaced by just `mo_files`

### CODE REVIEW

**Comment by larshp** [comment]
on a general note, I'd like to move things from the superclass into the interface, not from interface into superclass. Ideally get rid of the superclass

composition over inheritance

**Comment by mbtools** [comment]
I can move `get_accessed_files` to the interface (and keep `mo_files` there) but it means touching all objects. ok?

**Comment by larshp** [comment]
> Can we merge this anyway?

yea, its not on the top of the priority list

**Review by larshp — APPROVED** [review]
pulled ok

**Pull request merged**
