### PR TITLE
use HEAD symref as default branch

### LINKED ISSUE #3974: "Branch master not found" when creating online repo
Github recently changed the default branch name to "main" (https://github.com/github/renaming). However, when you try to create a new online repo in abapGit, the default will be set to "master" leading to the following error:

image

Issue:

abapGit does not automatically detect the name of the default branch. The initial default branch is hardcoded to refs/heads/master (`zif_abapgit_definitions=>c_git_branch-master).

Workaround:

When creating a new online repo, enter "main" as the default branch:

image

### PR DESCRIPTION
**Pull request by larshp**
Instead of hardcoding "master" as default branch, abapGit will now take the HEAD symref

closes #3974

public repository https://github.com/larshp/head_branch_main can be used for testing

### CODE REVIEW

**Comment by sbcgua** [comment]
just a comment: UX-wise HEAD is a bit confusing. fewer people know what does HEAD mean. I mean the place holder. Maybe it is better to write `master or main` there. It does not impact the real value anyway.

**Comment by larshp** [comment]
how about "default branch"? "master or main" might be wrong

**Comment by sbcgua** [comment]
hmm, maybe even further ? `detect default branch automatically` ?

**Comment by sbcgua** [comment]
Or `autodetect default branch`

**Comment by larshp** [comment]
updated, https://github.com/abapGit/abapGit/pull/3983/commits/bcabdbfd97e006f172553763513c5fef35381119

**Comment by sbcgua** [comment]
image

Looks good imho :)

**Comment by larshp** [comment]
and btw, looks like GitHub has updated everyone's default to "main"

**Comment by larshp** [comment]
@sbcgua add a review approval, then its visible from the overview 😄 I'll merge it tomorrow

**Review by sbcgua — APPROVED** [review]
:+1:

**Pull request merged**
