### PR TITLE
replace `seoclskey` with `abap_classname`

### PR DESCRIPTION
**Pull request by larshp**
`seoclskey` is not released

UPDATE: changed to compatible approach

### CODE REVIEW

**Comment by mbtools** [comment]
Is this the only object related to exits? If there are more, we should do them all together.

**Comment by larshp** [comment]
true, also need to do something with `ssfapplssl`, but it will likely be a compatible change

**Comment by larshp** [comment]
changed to compatible approach, ready for review

**Review by mbtools — APPROVED** [review]
👍

**Pull request merged**
