### PR TITLE
ZCL_ABAPGIT_REPO_ONLINE: Rename get_sha1_remote to get_branch_hash_remote

### PR DESCRIPTION
**Pull request by mariusraht2**
Related to #3040

Rename `get_sha1_remote` to `get_branch_hash_remote` in `ZCL_ABAPGIT_REPO_ONLINE` to clarify its usage in contrast to new attribute `commit_hash` (s. PR #4024).

**Change Log:**
- Renamed `get_sha1_remote` to `get_branch_hash_remote`
- Updated related caller

### CODE REVIEW

**Comment by larshp** [comment]
what if its not referring to a branch? you are implementing pulling a commit so this will be the case?

**Review by larshp — CHANGES_REQUESTED** [review]
see comments above

**Comment by larshp** [comment]
The title "Rename sha1_remote in repo_online to branch_hash" does not reflect what is actually done?

there are multiple renames, where none of these is the one mentioned in the title

**Comment by mariusraht2** [comment]
> what if its not referring to a branch? you are implementing pulling a commit so this will be the case?
Yes, I want to implement a method to pull remote objects by a commit hash with the same methods - functionality/logic isn't needed to be changed for the methods in this PR. In PR #4024 I want to add a new pull method based on the hash is being a branch or commit hash.

> from branch hash its difficult to know if its the remote or the local
There are 2 branch hashes? One local and one remote? Either way I just rename it to what it is... Before it was named iv_branch, respectively mv_branch which wasn't its real purpose.

> "hash" or "sha1" most places is currently called sha1? which currently, is exactly what it is, not a generic hash but a sha1 hash/checksum
Yes, that's correct. I just try to reduce the redundancy of a technology (SHA1) that could change likely in the future without the need to create a really great PR with just the renaming of SHA1 to HASH. If you want I rename it to SHA1.

> The title "Rename sha1_remote in repo_online to branch_hash" does not reflect what is actually done?
get_sha1_remote method is being renamed to get_branch_hash_remote and iv_branch is being renamed to  iv_parent and rv_sha1 is being renamed to rv_hash (not mentioned in title, true)  and mv_branch is being renamed to mv_branch_hash and callers are updated related to these changes. You're free to change the title to a more fitting one if you want :).

**Review by larshp — CHANGES_REQUESTED** [review]
get_branch_hash_remote: 
I think the old name "get_sha1_remote" is a better name, as the state might not be the head of a branch, like the feature you are implementing where it can be a commit
A repository has a SHA1 remote status, which might be based on a branch, or a commit or something else.

**Comment by mariusraht2** [comment]
> get_branch_hash_remote:
> I think the old name "get_sha1_remote" is a better name, as the state might not be the head of a branch, like the feature you are implementing where it can be a commit
> A repository has a SHA1 remote status, which might be based on a branch, or a commit or something else.

Yes, I agree we you on that in principle. In this case we have to save the branch hash (root commit) and the current sha1 remote status separatly from eachother because the commits have to be determined on base of the branch hash to get always only the latest (youngest) one from the top of the commit hierarchy and be able to reset the sha1 remote status to the root commit (branch hash). Alternatively we would have to redetermine the branch hash always from remote which would lead - in my opinion - only to unnecessary remote calls because the branch hash doesn't change except the user changes the repo or branch.

Therefore I planned to add a new attribute (s. PR #4024) to separate the current remote sha1 status from the branch hash - the latter can also act as a fallback attribute if something goes wrong.

**Comment by larshp** [comment]
two scenarios:
A: user pulls branch "name", this points to SHA1 = "123abc"
=> branch name is updated to "name", remote hash is updated to "123abc"

B: user pulls commit "123abc"
=> branch name is set to "", remote has is updated to "123abc"

there is no need to separate the logic/fields, its basically the same, the first remote hash is no different than in scenario B

**Comment by mariusraht2** [comment]
👍 I thought about it a little bit more and tried some things and you're right - my error was that I thought that the branch hash don't change and thus we would always only redetermine an attribute already known from remote over and over again which wouldn't be necessary in that case. That's obviously wrong and thus can use get_sha1_remote.

**Pull request closed without merging**
