### PR TITLE
Refactor "Go Back"

### PR DESCRIPTION
**Pull request by mbtools**
"Go Back" action is now handled in the router (like "Go Home"). No need to process it `on_event`.

### CODE REVIEW

**Comment by larshp** [comment]
I'll have a look at the failing test tomorrow

**Comment by mbtools** [comment]
np. i'm done for today... off to halloween party 👻

**Comment by larshp** [comment]
fixed with https://github.com/open-abap/open-abap-core/pull/808

**Comment by larshp** [comment]
well, overall I'd rather keep things isolated, instead of a dependency into router that is not declared. Ie. its difficult to tell which events are handled where, its only possible if everything is handled in one place ie. the page, when the actions on the page changes, the page handler changes.

Not, when a page changes the router changes, that would lead to conflicts and having a god class.

**Review by larshp — APPROVED** [review]

**Pull request merged**
