### PR TITLE
Always use active version for DOCU CL

### LINKED ISSUE #5196: Support for Objecttype: LIMU/ DOCU  "Documentation"
Hey,

as most of know, we can extend custom classes and programs with a documentation (Transaction se61).

Unfortunately, this type of object is not (yet?) supported. Is there any specific reason why? Do you think it could technically be implemented?

I would love to git these objects as well.

Thanks,
fischmir

### PR DESCRIPTION
**Pull request by flaiker**
Currently the latest version is used to read class documentation and raw (saved but inactive) is used for saving. This change makes read and write access always use the active version.

SDOC_CONSTANTS:
image

Might fix #5196, pending feedback

I couldn't find a test case for this in abapGit-tests. I'll create one.

### CODE REVIEW

**Comment by flaiker** [comment]
https://github.com/abapGit-tests/CLAS_docu/pull/1

Seems like pull to delete local documentation doesn't work either here like #5202

Probably missed here

https://github.com/abapGit/abapGit/blob/3fa3323b2e21d9ef5c97ae98af6a682dce17303d/src/objects/zcl_abapgit_object_clas.clas.abap#L191

and here

https://github.com/abapGit/abapGit/blob/3fa3323b2e21d9ef5c97ae98af6a682dce17303d/src/objects/zcl_abapgit_object_intf.clas.abap#L90

zif_abapgit_oo_object_fnc needs a delete_documentation method calling DOCU_DEL I think for this

**Comment by mbtools** [comment]
FYI, we have methods in the superclass for the documentation. I'm not sure, why those aren't used for `clas/intf`:

```
ZCL_ABAPGIT_OBJECTS_SUPER
  SERIALIZE_LONGTEXTS
  DESERIALIZE_LONGTEXTS
  DELETE_LONGTEXTS
```

**Comment by flaiker** [comment]
Thanks! I saw there were other usages of the function module but didn't realize those were directly accessible. I'll refactor it.

**Comment by flaiker** [comment]
Hmm actually not sure. There's quite a bit more logic in ZCL_ABAPGIT_LONGTEXTS than the direct calls to DOCU_* and the formats in the serialized data are not identical. I think that's for a separate PR to solve.

**Review by mbtools — APPROVED** [review]
👍

**Pull request merged**
