### PR TITLE
check variant popup refactoring

### PR DESCRIPTION
**Pull request by larshp**
* class `zcl_abapgit_code_inspector`, method `validate_check_variant` moved to private section
* new package for popups, https://github.com/abapGit/abapGit/issues/6361
* new html popup class `zcl_abapgit_ui_pop_code_insp`
* settings local page, use the new popup

### CODE REVIEW

**Comment by mbtools** [comment]
It needs a bit of work in `zcl_abapgit_gui_picklist` @sbcgua:

- If "in-page" is false, then the options are side-by-side instead of one per line. Also, there's no border around the options 
- If "in-page" is true (preferred here), then we need a scrollbar if there are many options
- In either case, the width is too small. We should have a parameter to pass a style-class

image

image

@larshp Maybe rename `zcl_abapgit_ui_pop_code_insp` to `zcl_abapgit_popup_code_insp`

**Comment by larshp** [comment]
need a new control, like select from table, but it can always be done later, it kind of works for now. I'm focusing more on the refactoring than the UX

class renamed

**Comment by sbcgua** [comment]
> new package for popups, https://github.com/abapGit/abapGit/issues/6361

`...ui_popups`

**Comment by sbcgua** [comment]
new table control: yes, there was no intent in the first PR, just to introduce the technology itself. So table variant is waiting ahead. I might have a look after merging of this one

**Comment by larshp** [comment]
@sbcgua ok to merge?

**Review by sbcgua — APPROVED** [review]
Yeap

**Pull request merged**
