### PR TITLE
Make exceptions compatible with 702

### LINKED ISSUE #1273: Error: The class "ZCX_ABAPGIT_EXCEPTION" was not derived from either "CX_STATIC_CHECK" or "CX_DYNAMIC_CHECK".
Hi,

I was trying to setup ABAPGIT on one of our systems and when I try to pull the latest version on ZABAPGIT package, I get the error:
The class "ZCX_ABAPGIT_EXCEPTION" was not derived from either "CX_STATIC_CHECK" or "CX_DYNAMIC_CHECK".	

System Details:
image

What could be the problem?

There were other problems in 702 which I manually commented out. Do we have a fork/branch specifically for 702? 

P.S. I'm a novice to this, so pardon me if my questions are silly.

### PR DESCRIPTION
**Pull request by mbtools**
I finally solved the puzzle on how to make the developer version work on 702.

702 does not deserialize exception classes correctly that have a constructor in a super-class (see #1273). Adding an explicit constructor that calls the super-constructor, the issue is avoided.

Closes #1273

### CODE REVIEW

**Comment by mbtools** [comment]
@larshp not sure what broke the transpiler test

**Comment by larshp** [comment]
`check_syntax, Method importing parameter "TEXTID" does not exist, zcx_abapgit_not_found.clas.abap:23`

need to add TEXTID to the constructor in https://github.com/open-abap/open-abap/blob/main/src/exceptions/cx_static_check.clas.abap

**Comment by mbtools** [comment]
ok, i will update it

**Comment by larshp** [comment]
https://github.com/open-abap/open-abap/pull/205 merged

**Comment by larshp** [comment]
changes pulled without problems and without syntax errors

**Review by larshp — APPROVED** [review]

**Pull request merged**
