### PR TITLE
WAPA: Add file extension for UI5 related pages

### PR DESCRIPTION
**Pull request by mbtools**
Fiori UI5 related pages are defined without extension. However, when serializing them it's beneficial to add a corresponding extension. This allows for proper file detection as well as syntax highlighting in abapGit and the remote repository (GitHub, VSCode, etc).

This also enables shortening the lengthy filenames via exit (#5178).

### CODE REVIEW

**Comment by larshp** [comment]
hmm, so the filename is one thing in the system and a different when serialized?

**Comment by larshp** [comment]
yes, its a mess how SAP has made it

but, how do we know there are no PNG/GIF/JPG/YML/other files part of these files?

The filenames in https://github.com/abapGit-tests/WAPA_Fiori/blob/main/src/zempltest.wapa.ui5repositorypathmapping.xml will not match anymore

Plus I guess https://github.com/abapGit-tests/WAPA_Fiori/blob/main/src/zempltest.wapa.xml#L137 will also break


I dont think this is strictly something we need to fix in abapGit

**Comment by larshp** [comment]
perhaps suggest a user user exit, if the user wants different names than what it is in the system

**Comment by mbtools** [comment]
True, we don't know if other file formats are possible.

**Pull request closed without merging**
