### PR TITLE
VIEW: Add authorization group to serialize and deserialize

### PR DESCRIPTION
**Pull request by d-schaaf**

### CODE REVIEW

**Comment by mbtools** [comment]
Looks good. Can you please create a small test case for https://github.com/abapGit-tests/VIEW_Auth_Group? Thanks 🙏

**Comment by d-schaaf** [comment]
> Looks good. Can you please create a small test case for https://github.com/abapGit-tests/VIEW_Auth_Group? Thanks 🙏

I'll try to, never did before

**Comment by d-schaaf** [comment]
I had a look at some of the other tests. In most cases there's only an XML inside. Is this what you weant me to provide including the authorisazion group tags?

**Comment by mbtools** [comment]
Yes. Just like the TABL_Auth_Group repo

**Comment by d-schaaf** [comment]
Ok, done and pull request created

**Comment by mbtools** [comment]
Didn't have time to try it but looks good. Merge it

**Comment by larshp** [comment]
welcome to abapGit as a contributor 🎉

**Pull request merged**
