### PR TITLE
update Slack invitation link

### PR DESCRIPTION
**Pull request by larshp**
https://blog.heroku.com/next-chapter

### CODE REVIEW

**Comment by gepparta** [comment]
We get this error on using this new invitation method
image

**Comment by larshp** [comment]
hmm, I tried changing some settings, but it didnt work

lest try giving it some hours to see if it refreshes whatever token is bad

**Comment by larshp** [comment]
I've sent an email to them

**Comment by larshp** [comment]
@gepparta try again, https://communityinviter.com/apps/abapgit/abap

**Pull request merged**
