### PR TITLE
Fix pull errors related to files deleted remotely

### LINKED ISSUE #4277: Errors on pull for remotely deleted objects
image

This is after executing a pull to update abapGit. Not sure what happended here. I guess deletions aren't done on pull but only on reset local (right?) but then the error message doesn't make much sense. The objects are all still there.

Executing pull again resulted in the same behavior.

Reset local then was able to clean everything up. Which I expected it to and planned on doing anyways but the error messages in the log on pull don't seem right. If remotely deleted object are to be ignored on pull then no import should be attempted for them.

### PR DESCRIPTION
**Pull request by mbtools**
In case files are deleted remotely, the files are now ignored during a pull. In other words, "pull" will not touch objects that exist only locally and not remotely.

To delete such objects locally, use "reset local (forced pull)" which will show a popup for these objects and let you delete them.

Closes #4277

### CODE REVIEW

**Comment by larshp** [comment]
@flaiker can you help testing this change?

**Comment by flaiker** [comment]
Uhm, the abapmerge report created by CI isn't possibly saved as a build artifact somewhere right?

**Comment by mbtools** [comment]
A kept a few older versions. Anyone in particular?

**Comment by flaiker** [comment]
Oh the old ones are accessable somewhere in the build repo. I was talking about the one for this pr to repeat my test case of updating abapgit itself. I don't have an npm environment set up.

**Comment by larshp** [comment]
@flaiker the builds are now saved for each build, click details on the "build" step, 

image

**Comment by flaiker** [comment]
So my test case was:

- Downgrade the development version to a commit from 6 months ago
- Install the new standalone version from this PR build
- Upgrade development version using standalone version
- See if the messages appear again ("File not found. Import of object failed")

First of all after pull I got this (unrelated) error on activation:
image

I pressed activate anyway.

After activation finished I only got warning in the log. Surprisingly lots of warnings based on packages movements. Some were moved automatically on pull, some apparently were not.

<summary>
<details>
Changed package assignment for object CLAS ZCL_ABAPGIT_CTS_API 

Changed package assignment for object CLAS ZCL_ABAPGIT_DEFAULT_TRANSPORT 

Changed package assignment for object CLAS ZCL_ABAPGIT_LONGTEXTS 

Changed package assignment for object CLAS ZCL_ABAPGIT_OBJECT_ENHO_CLIF 

Changed package assignment for object CLAS ZCL_ABAPGIT_OO_BASE 

Changed package assignment for object CLAS ZCL_ABAPGIT_OO_CLASS 

Changed package assignment for object CLAS ZCL_ABAPGIT_OO_FACTORY 

Changed package assignment for object CLAS ZCL_ABAPGIT_OO_INTERFACE 

Changed package assignment for object CLAS ZCL_ABAPGIT_OO_SERIALIZER 

Changed package assignment for object CLAS ZCL_ABAPGIT_PR_ENUMERATOR 

Changed package assignment for object CLAS ZCL_ABAPGIT_PR_ENUM_GITHUB 

Changed package assignment for object CLAS ZCL_ABAPGIT_SOTR_HANDLER 

Changed package assignment for object CLAS ZCL_ABAPGIT_TRANSPORT 

Changed package assignment for object CLAS ZCL_ABAPGIT_TRANSPORT_2_BRANCH 

Changed package assignment for object CLAS ZCL_ABAPGIT_TRANSPORT_MASS 

Changed package assignment for object CLAS ZCL_ABAPGIT_TRANSPORT_OBJECTS 

Changed package assignment for object INTF ZIF_ABAPGIT_CTS_API 

Changed package assignment for object INTF ZIF_ABAPGIT_LONGTEXTS 

Changed package assignment for object INTF ZIF_ABAPGIT_OBJECT_ENHO 

Changed package assignment for object INTF ZIF_ABAPGIT_OBJECT_ENHS 

Changed package assignment for object INTF ZIF_ABAPGIT_OO_OBJECT_FNC 

Changed package assignment for object INTF ZIF_ABAPGIT_PR_ENUM_PROVIDER 

Files for object CLAS ZCL_ABAPGIT_LONGTEXTS are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_OBJECT_ENHO_BADI are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_OBJECT_ENHO_BADI are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_OBJECT_ENHO_CLASS are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_OBJECT_ENHO_CLASS are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_OBJECT_ENHO_CLIF are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_OBJECT_ENHO_FUGR are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_OBJECT_ENHO_FUGR are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_OBJECT_ENHO_HOOK are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_OBJECT_ENHO_HOOK are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_OBJECT_ENHO_INTF are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_OBJECT_ENHO_INTF are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_OBJECT_ENHO_WDYC are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_OBJECT_ENHO_WDYC are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_OBJECT_ENHO_WDYN are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_OBJECT_ENHO_WDYN are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_OBJECT_ENHS_BADI_D are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_OBJECT_ENHS_BADI_D are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_OBJECT_ENHS_HOOK_D are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_OBJECT_ENHS_HOOK_D are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_OO_BASE are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_OO_CLASS are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_OO_INTERFACE are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_OO_SERIALIZER are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_PR_ENUMERATOR are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_PR_ENUM_GITHUB are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_SOTR_HANDLER are not placed in the same folder 

Files for object CLAS ZCL_ABAPGIT_SOTR_HANDLER are not placed in the same folder 

Files for object INTF ZIF_ABAPGIT_LONGTEXTS are not placed in the same folder 

Files for object INTF ZIF_ABAPGIT_OBJECT_ENHO are not placed in the same folder 

Files for object INTF ZIF_ABAPGIT_OBJECT_ENHS are not placed in the same folder 

Files for object INTF ZIF_ABAPGIT_OO_OBJECT_FNC are not placed in the same folder 

Files for object INTF ZIF_ABAPGIT_PR_ENUM_PROVIDER are not placed in the same folder 

Package and path does not match for object, CLAS ZCL_ABAPGIT_LONGTEXTS 

Package and path does not match for object, CLAS ZCL_ABAPGIT_OBJECT_ENHO_BADI 

Package and path does not match for object, CLAS ZCL_ABAPGIT_OBJECT_ENHO_BADI 

Package and path does not match for object, CLAS ZCL_ABAPGIT_OBJECT_ENHO_CLASS 

Package and path does not match for object, CLAS ZCL_ABAPGIT_OBJECT_ENHO_CLASS 

Package and path does not match for object, CLAS ZCL_ABAPGIT_OBJECT_ENHO_CLIF 

Package and path does not match for object, CLAS ZCL_ABAPGIT_OBJECT_ENHO_FUGR 

Package and path does not match for object, CLAS ZCL_ABAPGIT_OBJECT_ENHO_FUGR 

Package and path does not match for object, CLAS ZCL_ABAPGIT_OBJECT_ENHO_HOOK 

Package and path does not match for object, CLAS ZCL_ABAPGIT_OBJECT_ENHO_HOOK 

Package and path does not match for object, CLAS ZCL_ABAPGIT_OBJECT_ENHO_INTF 

Package and path does not match for object, CLAS ZCL_ABAPGIT_OBJECT_ENHO_INTF 

Package and path does not match for object, CLAS ZCL_ABAPGIT_OBJECT_ENHO_WDYC 

Package and path does not match for object, CLAS ZCL_ABAPGIT_OBJECT_ENHO_WDYC 

Package and path does not match for object, CLAS ZCL_ABAPGIT_OBJECT_ENHO_WDYN 

Package and path does not match for object, CLAS ZCL_ABAPGIT_OBJECT_ENHO_WDYN 

Package and path does not match for object, CLAS ZCL_ABAPGIT_OBJECT_ENHS_BADI_D 

Package and path does not match for object, CLAS ZCL_ABAPGIT_OBJECT_ENHS_BADI_D 

Package and path does not match for object, CLAS ZCL_ABAPGIT_OBJECT_ENHS_HOOK_D 

Package and path does not match for object, CLAS ZCL_ABAPGIT_OBJECT_ENHS_HOOK_D 

Package and path does not match for object, CLAS ZCL_ABAPGIT_OO_BASE 

Package and path does not match for object, CLAS ZCL_ABAPGIT_OO_CLASS 

Package and path does not match for object, CLAS ZCL_ABAPGIT_OO_INTERFACE 

Package and path does not match for object, CLAS ZCL_ABAPGIT_OO_SERIALIZER 

Package and path does not match for object, CLAS ZCL_ABAPGIT_PR_ENUMERATOR 

Package and path does not match for object, CLAS ZCL_ABAPGIT_PR_ENUM_GITHUB 

Package and path does not match for object, CLAS ZCL_ABAPGIT_SOTR_HANDLER 

Package and path does not match for object, CLAS ZCL_ABAPGIT_SOTR_HANDLER 

Package and path does not match for object, INTF ZIF_ABAPGIT_LONGTEXTS 

Package and path does not match for object, INTF ZIF_ABAPGIT_OBJECT_ENHO 

Package and path does not match for object, INTF ZIF_ABAPGIT_OBJECT_ENHS 

Package and path does not match for object, INTF ZIF_ABAPGIT_OO_OBJECT_FNC 

Package and path does not match for object, INTF ZIF_ABAPGIT_PR_ENUM_PROVIDER 

Multiple files with same filename, zcl_abapgit_longtexts.clas.abap 

Multiple files with same filename, zcl_abapgit_object_enho_badi.clas.abap 

Multiple files with same filename, zcl_abapgit_object_enho_badi.clas.xml 

Multiple files with same filename, zcl_abapgit_object_enho_class.clas.abap 

Multiple files with same filename, zcl_abapgit_object_enho_class.clas.xml 

Multiple files with same filename, zcl_abapgit_object_enho_clif.clas.xml 

Multiple files with same filename, zcl_abapgit_object_enho_fugr.clas.abap 

Multiple files with same filename, zcl_abapgit_object_enho_fugr.clas.xml 

Multiple files with same filename, zcl_abapgit_object_enho_hook.clas.abap 

Multiple files with same filename, zcl_abapgit_object_enho_hook.clas.xml 

Multiple files with same filename, zcl_abapgit_object_enho_intf.clas.abap 

Multiple files with same filename, zcl_abapgit_object_enho_intf.clas.xml 

Multiple files with same filename, zcl_abapgit_object_enho_wdyc.clas.abap 

Multiple files with same filename, zcl_abapgit_object_enho_wdyc.clas.xml 

Multiple files with same filename, zcl_abapgit_object_enho_wdyn.clas.abap 

Multiple files with same filename, zcl_abapgit_object_enho_wdyn.clas.xml 

Multiple files with same filename, zcl_abapgit_object_enhs_badi_d.clas.abap 

Multiple files with same filename, zcl_abapgit_object_enhs_badi_d.clas.xml 

Multiple files with same filename, zcl_abapgit_object_enhs_hook_d.clas.abap 

Multiple files with same filename, zcl_abapgit_object_enhs_hook_d.clas.xml 

Multiple files with same filename, zcl_abapgit_oo_base.clas.abap 

Multiple files with same filename, zcl_abapgit_oo_class.clas.abap 

Multiple files with same filename, zcl_abapgit_oo_interface.clas.abap 

Multiple files with same filename, zcl_abapgit_oo_serializer.clas.abap 

Multiple files with same filename, zcl_abapgit_pr_enum_github.clas.abap 

Multiple files with same filename, zcl_abapgit_pr_enumerator.clas.abap 

Multiple files with same filename, zcl_abapgit_sotr_handler.clas.abap 

Multiple files with same filename, zcl_abapgit_sotr_handler.clas.testclasses.abap 

Multiple files with same filename, zif_abapgit_longtexts.intf.abap 

Multiple files with same filename, zif_abapgit_object_enho.intf.abap 

Multiple files with same filename, zif_abapgit_object_enhs.intf.abap 

Multiple files with same filename, zif_abapgit_oo_object_fnc.intf.abap 

Multiple files with same filename, zif_abapgit_pr_enum_provider.intf.abap 
</details>
</summary>

I don't know if this behavior is related to the change in this PR. I guess not since for moved objects after pull the old path appears locally deleted, not remotely deleted.

Example:

image

message_helper was correctly listed as deleted on the remote and neither deleted automatically locally nor was it tried to import the object again which this PR tries to solve. So that seems to work fine!

Some other movements are listed differently. I guess these are the ones where the message "Changed package assignment" was issued for.

image

Newly pulled packages didn't get their text for some reason:

image

image

After pressing refresh and pull again nothing happend. Reset local was able to clean everything up leaving no diffs or warnings at all.

Side note:
I tried using the checkout commit feature for the first time to downgrade and I was ready to paste a commit hash into a popup . I was surprised by an ALV to pick a commit from which only listed commits dating back like 1 or 2 months ago. So I went with preparing a branch at that commit instead and checking that out.

**Review by flaiker — APPROVED** [review]

**Pull request merged**
