### PR TITLE
LXE langs refactoring

### PR DESCRIPTION
**Pull request by sbcgua**
DRAFT yet.

Following some comments at #4470 

- remove `set/get_i18n_langs` from dotabap class and fix settings UI appropriately
- change language list to ISO codes (main change)
- refactorings in LXE class
  - in particular serialize intersection between repo langs and installed langs
  - remove exception from `convert_*`
  - added `detect_unsupported` to use for warnings, but haven't finished. Not sure where the warning should raise from. But most probably it is `ZCL_ABAPGIT_REPO->GET_FILES_LOCAL` - because it has clear access to the log

Might need some help with fresh head testing

### CODE REVIEW

**Comment by mbtools** [comment]
Looks to be on the right track. We should change the read-only "Main Language" in settings to the ISO code, too.

**Comment by mbtools** [comment]
maybe replace `zif_abapgit_definitions=>ty_languages` with DDIC `LAISO_TAB`

**Comment by sbcgua** [comment]
Actually this part is ready for review. Though has some further improvements - I added new comments in 4470. Sorry for long silence.

**Comment by sbcgua** [comment]
- "read-only "Main Language" in settings to the ISO code" - I think, yes, added to original issue
- "replace zif_abapgit_definitions=>ty_languages with DDIC LAISO_TAB" - good idea, I'll have a look

**Comment by mbtools** [comment]
I updated https://github.com/abapGit-tests/PROG_lxe and https://github.com/abapGit-tests/FUGR_lxe to use `<LAISO>DE</LAISO>` and tested the PR. works well in general. FUGR requires double-pull but that's a separate PR as you mentioned.

**Review by mbtools — APPROVED** [review]
👍

**Comment by sbcgua** [comment]
@larshp any opinions about "replace zif_abapgit_definitions=>ty_languages with DDIC LAISO_TAB" ? In the context of avoiding ddic types. LAISO_TAB is a part of SCP package (sap code pages) so looks very very standard ... I don't have preference. Probably `zif_abapgit_definitions=>ty_languages = LAISO_TAB` should be optimal

**Comment by larshp** [comment]
`LAISO_TAB` is not in the list of released objects to use in Steampunk, and I don't think its strictly needed to refer to it, we can just define it

`LAISO` I also cannot find, but we need it to express the semantics/usage of the field

**Comment by sbcgua** [comment]
Ok, let's leave it as it is then.

**Comment by larshp** [comment]
cool, merging 👍

**Pull request merged**
