### PR TITLE
Fix pull clasenh "file emxxx not found" #4515

### PR DESCRIPTION
**Pull request by sandraros**
Fix pull clasenh "file emxxx not found" #4515

### CODE REVIEW

**Comment by mbtools** [comment]
look good. could you please add a test case that has some enho includes to this repo?
https://github.com/abapGit-tests/ENHO-INCLUDES

**Comment by larshp** [comment]
https://github.com/abapGit-tests/ENHO-INCLUDES/pull/1 created by @sandraros

**Review by mbtools — APPROVED** [review]
Tested. Works. 👍

**Comment by larshp** [comment]
thanks 👍

**Pull request merged**
