### PR TITLE
Standalone exit proxy

### LINKED ISSUE #4727: User exit class is not applicable to standalone installation
Mainly because all definitions are missing. I attempted to implement the `pre_calculate_repo_status` in one of the clients and failed. But of course there are more examples. 

Ideas: the only idea that come to my mind is to have a separate (automatically updated) abapgit repository with relevant definitions only. So major interfaces (probably not all). Maybe potentially with some wrapper class that can create instances of some classes from abapgit_standalone.
Furthermore upon abapGit full package installation the code can check if such a package exists in the system and warn/block deployment.

### PR DESCRIPTION
**Pull request by pokrakam**
For #4727
Add a proxy that 'adds' an interface to an exit class `zcl_abapgit_standalone_exit` that implements the exit methods directly.
Can be implemented with relatively little effort. More importantly, it needs no further action for most abapGit updates, just paste the new version and go.

To implement a standalone exit we must de-interface the regular user exit:

- Create class `zcl_abapgit_standalone_exit`
- Copy/paste definition(s) you need from [zif_abapgit_exit](https://github.com/abapGit/abapGit/blob/3c51772175ff645e5f3e01e0e0e19b86cd8700fa/src/zif_abapgit_exit.intf.abap) into the public section
- Adapt or create any necessary abapGit-specifics (z-data types, `zcx_abapgit_exception`)
- Implement the method(s)

The proxy will forward any exceptions raised by the methods to `zcx_abapgit_exception` and parameter types must be compatible.

If the solution is agreeable I'll add it to the docs too.

### CODE REVIEW

**Comment by larshp** [comment]
why wont 

```abap
* create class ZCL_ABAPGIT_USER_EXIT implementing ZIF_ABAPGIT_EXIT in following include,
* if using the development version of abapGit create a global class instead
* place the object in a different package than ZABAPGIT
INCLUDE zabapgit_user_exit IF FOUND.
```

work? I'd suggest only having one approach for one thing

**Comment by mbtools** [comment]
I understand the pain of having to adjust the exit class since we added a few new methods to the exit interface in recent months. But generally, that doesn't happen often. 

I agree with Lars. We already have two approaches (include with local class/global class). The proxy would make it even more complicated. 

What if we had `zcl_abapgit_user_exit_super` with a default implementation (just `RETURN.` for all methods)? For the actual implementation in `zcl_abapgit_user_exit`, you could redefine only the exit methods you want to use.

**Comment by pokrakam** [comment]
Hmm, I misunderstood something and didn't realise the `INCLUDE` approach was already implemented because it continued to be debated in the issue. Nevermind, it was a fun challenge :)
We can drop this approach.

**Comment by pokrakam** [comment]
On a more general note, I think the whole exit concept would be cleaner with more of a BADI-like approach where each exit has its own class. It started off with a small number of exits and has now grown to 18 all lumped into one class and will likely grow further. 
Perhaps something like a fixed class name per exit that is addressed through dynamic programming, or a separate 'abapGit-exits' repo containing the interfaces. If they exist then any implementing classes are loaded and executed. Of course this raises a migration and compatibility questions too...

**Comment by mbtools** [comment]
It's the curse of standard software. One fits all... except for this switch or that switch and this exit or that exit ;-)

**Review by larshp — CHANGES_REQUESTED** [review]
we can discuss possible refactoring in an issue

**Comment by pokrakam** [comment]
Closed, let's discuss if there's a need to overhaul the exit concept in #4786

**Pull request closed without merging**
