### PR TITLE
Documentation  updates to the "contributing" section

### PR DESCRIPTION
**Pull request by PilotFlying**
Seeing the latest merge on the github pages, the paragraphs' numbering is not the same as in the preview:

image

This commit bypasses the issue

### CODE REVIEW

**Comment by larshp** [comment]
@PilotFlying check conflicts

**Comment by PilotFlying** [comment]
> @PilotFlying check conflicts

@larshp Done, sorry about that (I am learning git as I go :) )

**Comment by larshp** [comment]
no problem, sometimes there are real conflicts, this one looked like a missing rebase. After opening the PR, I recommend checking the "files changed" tab, to make sure everything looks as expected

**Comment by mbtools** [comment]
a little tip: in markdown you don't have to use sequential numbers. Just use 1., 1., 1., 1., etc. 
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#lists

**Comment by PilotFlying** [comment]
Thanks! 
What also got me was that in order to get the next list level you need to align directly below the start of the previous level text (where it starts after the number). Indentation is not enough

**Comment by larshp** [comment]
thanks 👍

**Pull request merged**
