### PR TITLE
Show diffs in case of trailing spaces

### PR DESCRIPTION
**Pull request by mbtools**
Fixes issue when overview is showing a diff

image

but the diff view is not

image

Now the diff properly shows trailing spaces

image

### CODE REVIEW

**Comment by larshp** [comment]
is it possible to add a unit test for this scenario?

**Comment by mbtools** [comment]
is this test failure related?

**Comment by larshp** [comment]
> is this test failure related?

hmm, I dont think its related, its a "unexpected pack header" in the v2 git stuff

**Comment by larshp** [comment]
fixed in #7067

**Review by larshp — APPROVED** [review]

**Pull request merged**
