### PR TITLE
Fix syntax error in `zcl_abapgit_file_deserialize`

### PR DESCRIPTION
**Pull request by mbtools**
The particular LOOP with secondary key is causing syntax error in 702. Moving the condition to the CHECK statement avoids the issue.

image

Ref #6313

### CODE REVIEW

**Comment by larshp** [comment]
this was a performance improvement via https://github.com/abapGit/abapGit/pull/6312, which will probably break

but anyhow, we need to fix the syntax first

**Review by larshp — APPROVED** [review]

**Comment by mbtools** [comment]
the particular loop is only executed for logging. shouldn't make much difference.

**Comment by christianguenter2** [comment]
Hm, what's wrong with the secondary key? Thought they are supported by NW 702?

**Comment by mbtools** [comment]
They are supported but I have no idea why this particular where clause causes an error.   It's not just me #6329

**Pull request merged**
