### PR TITLE
add page for running unit tests

### PR DESCRIPTION
**Pull request by larshp**
Under "Advanced" -> "Unit Test" will now run unit tests for the package(including objects in subpackage)

Lots of possible improvements, but for now just something simple that runs.

I dont know if it works on 702, lets see

ref #3935

image

image

### CODE REVIEW

**Comment by mbtools** [comment]
these do not exist in 702

1. New void type SABP_T_TADIR_KEYS used
2. New void type CL_SAUNIT_INTERNAL_RESULT used
3. New void type CL_AUCV_TEST_RUNNER_ABSTRACT used
4. New void type IF_SAUNIT_INTERNAL_RESULT used
5. New void type CL_AUCV_TEST_RUNNER_STANDARD used

might be easier to run ATC with variant `SWF_ABAP_UNIT` which does exist in 702 (same as we do for syntax check). you get results by class. if something fails, most likely you will have to edit the class anyway and run/debug unit tests there. no need for results by test method (although it's nice to see).

**Comment by larshp** [comment]
hmm, argh 😓

**Comment by larshp** [comment]
downported to dynamic calls, ready for review

**Comment by larshp** [comment]
merging

**Pull request merged**
