### PR TITLE
UI: Unify rendering of transport, user names - part 2

### LINKED ISSUE #4098: UI: Icons for online repo, user id, and transport
I'm not sure why our cloud icon has an arrow in it? Why not just
image

Add icons for user id:
image

Change icon for transport from:
image
to
image

https://fontawesome.com/icons/cloud?style=solid
https://fontawesome.com/icons/user?style=solid
https://fontawesome.com/icons/truck?style=solid

### PR DESCRIPTION
**Pull request by mbtools**
- Added icon for username
- Changed icon for transport to truck
- Adapted "staging" page 
- Renamed CSS-classes because of conflict with classes used on staging page
- Added hover info to item type icon (first column in repo view)

Closes #4098

image

image

### CODE REVIEW

**Review by sbcgua — APPROVED** [review]
Looks good for me. Nice improvements.

I think the colors could be improved and also I'm not sure about `-box` suffix - semantically unnecessary. But otherwise looks good.

**Comment by mbtools** [comment]
The stage page already used class=“user” and class=“transport” for table columns with JS depending on it. It was easier to change the span style. “-box” isn’t ideal. Open for suggestions

**Comment by sbcgua** [comment]
sure, but are they also `span`? Don't have an access to my system at the moment to check. I'm 100% that it can be solved with proper selectors. Semantically these banner are "transport", "user" and etc. Similarly columns in the table are also semantically "transport", "user" and etc. There is no contradiction.

**Comment by sbcgua** [comment]
on the other hand `span` might not be semantically most clear ... let me check when I'm by a system

**Comment by sbcgua** [comment]
maybe it should be not `span` but `label`. Though label is for forms, need to check what validation says about it. another option is to use double styling. `banner transport` and the selector  `.banner.transport`

**Comment by mbtools** [comment]
It's not about the CSS. it's already limited to the right element (i.e. the spans). The problem is the JS which is using, for example, class="transport" to filter the rows. The JS gets confused if there's another element with this class. So doubling won't help. 

https://github.com/abapGit/abapGit/blob/master/src/ui/zabapgit_js_common.w3mi.data.js#L345

https://github.com/abapGit/abapGit/blob/master/src/ui/zabapgit_js_common.w3mi.data.js#L509-L519

**Comment by sbcgua** [comment]
Yeah I know. It was me who wrote that JS in the first place :)) But this should not conflict with the tags outside of the table. At least it hadn't for quite a while. Or ?

**Comment by larshp** [comment]
Is it okay if I merge this PR?

**Pull request merged**
