### PR TITLE
Refactor "Object to Files" to html form

### LINKED ISSUE #4619: Convert Popup to HTML: Export Object (ZIP)

### PR DESCRIPTION
**Pull request by g-back**
closes #4619

requires #4626 for the search help to work correctly

goal is to get rid of `popup_object`, it's still used in `zcl_abapgit_services_basis->test_changed_by`, not quite sure how to approach it in scope of this PR.

### CODE REVIEW

**Comment by FreHu** [comment]
Test changed by is just this object selection and then you get a success message with the username, maybe it's not necessary? You can just look at the changed by in the repo.
image

**Comment by larshp** [comment]
@FreHu I'm not sure I understand the above comment, can you elaborate?

**Comment by FreHu** [comment]
> goal is to get rid of popup_object, it's still used in zcl_abapgit_services_basis->test_changed_by

test_changed_by is just this small popup i posted above, I think it wouldn't be missed much

**Comment by g-back** [comment]
Options:
 - remove test_changed_by functionality
 - make a new html page for test_changed_by (essentially a copy of this one)
 - try to make the tadir object selection page reusable and use it for export object and test_changed_by
 - ignore test_changed_by for now

**Comment by larshp** [comment]
suggest just removing the test_changed_by functionality

**Review by larshp — APPROVED** [review]
LGTM 👍

**Pull request merged**
