### PR TITLE
Checkout commit: Add menu entry and finish implementation

### LINKED ISSUE #3040: Revert to any single Commit
I didn't find this feature and need it so I suggest it: I think it would be useful to be able to revert to any single commit. For this it should be possible to select any existent commit and revert the repository to it.

Related to Issue #753.

### PR DESCRIPTION
**Pull request by mariusraht2**
Resolves #3040

**Change Log:**
- `ZCL_ABAPGIT_GUI_PAGE_REPO_VIEW`: Add menu entry for the user to be able to checkout commits on the repo page/view.
- `checkout_commit_build_list`: Use `io_repo` instead of `iv_url` and `iv_branch_name` as import parameters and changed related caller
- `checkout_commit_build_list`: Removed `ls_pull_result` because only commits-list is being used
- `checkout_commit_build_list`: Filter/delete `et_commits` by selected commit which could be a commit, tag or branch hash

### CODE REVIEW

**Comment by larshp** [comment]
@mariusraht2 the methods changed in this PR is currently not called from anywhere?

**Comment by mariusraht2** [comment]
It's being called in method checkout_commit in the same class (services_git)

**Comment by larshp** [comment]
is that method called from anywhere, where it can currently be triggered by the user?

**Comment by mariusraht2** [comment]
No, the menu entry for checkout_commit is to added with PR #4092.

**Comment by larshp** [comment]
okay, suggest adding the changes from #4092 into this PR, then its possible to do some testing before merging it

**Comment by mariusraht2** [comment]
Changed source branch

**Pull request closed without merging**
