### PR TITLE
Distinguish between "Global Settings" and "Repository Settings"

### PR DESCRIPTION
**Pull request by francisco-milan**
Pull request with 5 commits to address #6758

### CODE REVIEW

**Comment by larshp** [comment]
https://github.com/abapGit/abapGit/issues/6758#issuecomment-1901834858

**Comment by mbtools** [comment]
If there are no objections, we can merge

**Comment by larshp** [comment]
merging

**Comment by larshp** [comment]
welcome to abapGit as a contributor 🎉

**Comment by francisco-milan** [comment]
Thank you for the warm welcome! I'm excited to contribute to abapGit and look forward to being part of the community. If there are specific areas or tasks you recommend focusing on initially, please let me know. I'm eager to get started!

Best regards,

Francisco Milan.

**Pull request merged**
