### PR TITLE
Refactor password dialog

### PR DESCRIPTION
**Pull request by mbtools**
This is a replacement of the classic GUI popup dialog with an HTML form for entering username and password.

To best understand how it works, first look at `zcl_abapgit_http->create_by_url`. Instead of the password popup, it now jumps to the "Login Manager" and triggers a special exception in `zcl_abapgit_login_manager->login`. This exception is passed through to the general event handler in `zcl_abapgit_gui->handle_action`. Here it detects the special exception (`is_login`) and redirects to the new "Login Page" passing along the essential login details (URL, count, digest). 

The "Login Page" prompts for username and password via an HTML form. When the user clicks on "Login" or presses "Enter", username and password are set in the "Login Manager" (Digest authentification is now handled the same way). The "Login Page" then redirects back to the original page that triggered the login. 

We end up back in `zcl_abapgit_http->create_by_url` which can now load the credentials from the "Login Manager" (either username/password or the completed digest). If this results in a successful authentication (HTTP 200), the process continues as usual. If the username/password were incorrect, it will trigger the login process again. After 3 unsuccessful login attempts, the page will show the usual HTTP 401 error message. The login can be triggered again by refreshing the page. 

https://github.com/abapGit/abapGit/issues/783 contains a couple of screenshots.

I was able to verify basic authentication, but don't have any scenario with a proxy or requiring digest authentication. Please test thoroughly. 

Not included:
- Removal of old password popup

PS: The new solution integrates all login-related logic into `zcl_abapgit_login_manager` including the handing of digest and default users. This separates UI, HTTP, and Login nicely and is much cleaner than before.

### CODE REVIEW

**Comment by larshp** [comment]
Can we split this up into 2 or more changes? It looks like there are changes to the general login logic, and also refactoring of the password dialog, I'm guessing these can be separated.

This logic is quite central, so it needs a good review

**Comment by mbtools** [comment]
For easy testing, I kept it together since you will need all pieces. 

When we agree that this is the way to go, I can split it into several parts:

- Enhancement of HTML form 
- Enhancement of exception
- Enhancement to login manager
- New login page (up to here no impact)
- Changes to HTTP class and main GUI handler to activate new login
- Remove old login popup

**Comment by sbcgua** [comment]
I wonder if the exception should be caught at UI level. Maybe instead there should be some kind of `zif_credential_provider` which is passed into zcl_abapgit_http at creation time. Which should happen from factory. Which should be "loaded" with a proper implementation. E.g. https://github.com/abaplint/abaplint-sci-client/issues/221 may need another implementation - popup (which can be reimplemented in sci-client ui). Or e.g. if there is no UI (some rest abapgit api) - the implementation will differ completely.

BTW maybe show the password dialog in a separate popup with another control ? (just an idea)

**Comment by mbtools** [comment]
`zcl_abapgit_login_manager` basically functions as the credential provider. We can certainly change it to factory/interface/instances instead of a static class. 

SCI could inject a different provider class that shows the old popup (as you wrote, we would move the popup code to sci).

It would be great to show the form in an HTML popup without leaving the current page. However, I don't see how this would be possible esp. keeping it all HTML (and compatible with web version).  Open to suggestions...

**Comment by larshp** [comment]
@sbcgua will you be reviewing this PR? I cannot really keep track of the changes

**Comment by a-fas** [comment]
Sorry, i've been quite busy these days.

I certainly agree with the idea to split it into several pieces. Maybe keep this PR as a reference and submit smaller parts in the meantime.

@mbtools 
1) **Enhancement of HTML for**m - yes
2) **Exception** - I'd suggest reimagining this part. Is the exception needed? How will it be handled in e.g. rest api case ? Or background ? Maybe credential manager should be injected directly into http_client ? In case of UI: should it be handled on so high level ? I have a feeling that it should be closer to the specific operation. If this is an exception, I'd create an exception subclass. Maybe resumable. And/or maybe with additional data to carry with the error. This mechanism can be refactored without change in current UI. I'd suggest modelling it "on paper" first.

Maybe: there is **http_client and http_agent** - maybe we should unify them within this task. (or maybe not, but it the long term it is certainly the same essence)

**Compatibility with web version**: I would not worry about it at all at the moment. at least in terms of UI. The web version will probably have a 2-directional communication. And so it will make sense to add JS to override all kinds of old behaviour to whatever direction we'd like

**UI**: https://github.com/abapGit/abapGit/issues/783#issuecomment-713175502 - I think conceptually it is fine. Also needs experiments and tuning, but fine. Quick tuning ideas: I'd prefer that all the context information is close together. In particular where do I log in (github/...) and why (pull for repo xxx). Closer - means in the form. So probably it makes sense to add read-only feature to html_form at the step 1. But otherwise it is OK. 

**Popup page**: yep, no idea how to make without 2-directional communication. I idea to consider - open a popup window with own abapgit_gui instance and just the form. GUI support rendering one page. And will be kind of modal. Is it a good idea ? I don't know. needs studying and prototyping.

**Comment by sbcgua** [comment]
oops, wrong account. that was me, just in case :)

**Comment by mbtools** [comment]
There's more to it than what this PR is covering and I'm able to deliver at this time (like rewrite the login manager and how it interacts with HTTP clients, integrating client and agent). 

The suggestions are all good. However, I'm afraid such changes are hard to break into smaller pieces and will be rather disruptive (to the master branch). This should happen in a separate release branch. 
 
Anyway, we have this as a reference on what it could look like.

**Comment by larshp** [comment]
Suggest the following 3 PRs:
* refactoring logic in zcl_abapgit_login_manager, digest and acquiring login details
* refactoring the login handling with the exception can be a separate PR, while still keeping the old popup
* refactoring the old popup to new html

**Comment by mbtools** [comment]
Backup of changes: https://gist.github.com/mbtools/e9d67932622b8345417af8dba1aaafed

We can come back to it 2021

**Pull request closed without merging**
