### PR TITLE
Separate zif_abapgit_repo

### PR DESCRIPTION
**Pull request by sbcgua**
I think the code will benefit from separating repo interface. This PR intend to start it, quick and dirty separation of main repo function without much refactoring but to introduce the interface and enable further improvents. In particular unit tests for #5328.

Main approach and criteria: make zif_abapgit_repo_srv methods to use repo interface rather than repo class.

### CODE REVIEW

**Comment by larshp** [comment]
👍 suggest removing the ALIASES as next step

**Comment by sbcgua** [comment]
OK, ready for review. I tried to make as few changes as possible, just to make it through.
- added some methods to zif_repo, just those really necessary. The rest can be added if/when needed. (although `create_new_log` creeped in, which I find unnecessary ... well, ok)
- repo_srv cleaned more attentively, renaming variable to reflect that it became an interface (`li_`, `ri_`)
- the rest mostly ended up with `?=`
- a couple of se80 reorderings

Sidenote:
`zif_abapgit_repo_srv`: `get_repo_from_package` and `get_repo_from_url` have very weird semantics ? why ev_reason is needed ? Cannot it be done with exception ? From what I see the calling code does throw right after, the `ei_repo` is not really used ... strange code imho, though I didn't dive deep.

**Comment by sbcgua** [comment]
@larshp abaplint suggested some strange mistake ... :)

**Comment by larshp** [comment]
I'm on it...

**Comment by larshp** [comment]
false positive fixed, reruns triggered manually => success

**Comment by sbcgua** [comment]
:+1:
OK, then truly ready for review :)
Will wait for the merge to continue with checksums

**Comment by larshp** [comment]
this might break stuff in dependent repos, which is okay, but we should collect a list of dependent repos, then we can check the breakage in the PRs

**Comment by sbcgua** [comment]
OK, no prob. But is the code fine in general ? I'd like to rebase the checksums PR on it and continue there while I have some time

**Comment by larshp** [comment]
I've not looked through the changes in detail, yet. Just a quick run-through

**Comment by larshp** [comment]
change is not perfect, but necessary to move ahead 👍 I did not notice any change to `ty_item` stuff as mentioned above?

**Comment by larshp** [comment]
pulling ok, no syntax errors

**Comment by sbcgua** [comment]
> Marc: is it necessary to change ty_item this way? you added some comment about "signature being first" ...

> Lars: I did not notice any change to ty_item stuff as mentioned above?

Mmmm, yes, `ty_item` is split into signature and full item, similar to the file. It is needed for the checksums (not really needed, but makes them cleaner and less bug prone in case of future type enhancement). But ... it is not in this PR, it was in the checksums #5328. So let's better move this particular subject there.

**Comment by sbcgua** [comment]
"hack" -> "TODO" done

**Comment by larshp** [comment]
branch out of date, is the "allow edits from contributors" disabled?

**Comment by larshp** [comment]
branch out of date, is the "allow edits from contributors" disabled?

**Comment by larshp** [comment]
merging this today, in some whours

**Comment by larshp** [comment]
nice, looks like only https://github.com/abapGit/ADT_Backend/ will break with this change, merging

**Pull request merged**
