### PR TITLE
Package Structure - Part 2

### PR DESCRIPTION
**Pull request by mbtools**
$ABAPGIT_OBJECTS_TEXTS:

ZCL_ABAPGIT_LONGTEXTS
ZCL_ABAPGIT_SOTR_HANDLER
ZIF_ABAPGIT_LANG_DEFINITIONS
ZIF_ABAPGIT_LONGTEXTS

$ABAPGIT_OBJECTS_ENH:

ZCL_ABAPGIT_OBJECT_ENHO_BADI
ZCL_ABAPGIT_OBJECT_ENHO_CLASS
ZCL_ABAPGIT_OBJECT_ENHO_CLIF
ZCL_ABAPGIT_OBJECT_ENHO_FUGR
ZCL_ABAPGIT_OBJECT_ENHO_HOOK
ZCL_ABAPGIT_OBJECT_ENHO_INTF
ZCL_ABAPGIT_OBJECT_ENHO_WDYC
ZCL_ABAPGIT_OBJECT_ENHO_WDYN
ZCL_ABAPGIT_OBJECT_ENHS_BADI_D
ZCL_ABAPGIT_OBJECT_ENHS_HOOK_D
ZIF_ABAPGIT_OBJECT_ENHO ENHO
ZIF_ABAPGIT_OBJECT_ENHS ENHS

$ABAPGIT_TEST:

ZCL_ABAPGIT_OBJECTS_CI_TESTS
ZCL_ABAPGIT_PERFORMANCE_TEST

Deleted:

ZCL_ABAPGIT_TEST_SERIALIZE

#4253

### CODE REVIEW

**Review by larshp — CHANGES_REQUESTED** [review]
$ABAPGIT_OBJECTS_TEST:
ZCL_ABAPGIT_OBJECTS_CI_TESTS, I'd move this to top level /test/
ZCL_ABAPGIT_PERFORMANCE_TEST, I'd move this to top level /test/
ZCL_ABAPGIT_TEST_SERIALIZE, this class should really be deleted, its only used in one place, and does not carry any real logic

$ABAPGIT_GIT_PLATFORM:
I'd like to keep the git package independent of platforms, json parsing etc, so it is only related to the git protocol, platforms is not under the protocol, protocol is under the platform or alongside

**Comment by larshp** [comment]
@mbtools can you help updating the summary of changes?

**Comment by mbtools** [comment]
updated description

**Review by larshp — APPROVED** [review]
looks good

**Pull request merged**
