### PR TITLE
W3xx: Remove unnecessary metadata

### PR DESCRIPTION
**Pull request by mbtools**
`relid` and `objid` were already set properly during deserialize but not cleared during serialize.

Before:

image

After:

image

### CODE REVIEW

**Comment by larshp** [comment]
do we need to fix this as such? I guess it will impact multiple projects, and it will move to JSON _sometime_ anyhow

**Comment by mbtools** [comment]
The old mime objects aren't used much. I checked all repos on dotabap that were touched this year and only the 5 of 86 have a few w3xx objects:

https://github.com/abapGit/abapGit
https://github.com/sbcgua/mockup_loader
https://github.com/bizhuka/xtt
https://github.com/thedoginthewok/abapMermaid
https://github.com/DryDumbHead/easyHtmlEmail

**Comment by sbcgua** [comment]
Just my 5 cents, I think cleaning up structure is always good anyway. Even if there is a future change in format it helps accumulating knowledge of what is needed and what's not. Change in format is a complex shift in any case and combining it with structure cleaning will actually make things more complex. Just imho :)

**Comment by larshp** [comment]
ok, suggest bumping version when this is merged

**Comment by sbcgua** [comment]
> ok, suggest bumping version when this is merged

Let's fix #5784 before that then. To confirm tagging will work. I'm on it

**Comment by sbcgua** [comment]
the #5793 merged, so let's proceed with this one and the version change. I'll watch over the tagging scripts

**Pull request merged**
