### PR TITLE
LXE: Downport

### PR DESCRIPTION
**Pull request by christianguenter2**
Prevents this dump in systems <= 750  when experimental LXE is active
grafik

grafik
grafik

ERR_MSG doesn't exist for fm LXE_OBJ_TEXT_PAIR_READ and LXE_OBJ_TEXT_PAIR_WRITE.

### CODE REVIEW

**Comment by flaiker** [comment]
Maybe alternatively to exclusively raising the exception based on the release dependent err_msg raising might also be warranted if pstatus = cl_lxe_constants=>c_process_status_failure ('F') in _read and _write, assuming that exists on < 750?

**Comment by christianguenter2** [comment]
Good idea. Tried with test repo https://github.com/abapGit-tests/FUGR_lxe.git but import fails with `lv_pstatus = 'F'` while `err_msg` being empty. Hm...

grafik

grafik

Status 'F' is set here:
grafik
grafik

Same for read:
grafik

So while not knowing much about LXE it seems better to rely on `err_msg` and fail silently for other cases.

**Comment by flaiker** [comment]
> So while not knowing much about LXE it seems better to rely on err_msg and fail silently for other cases.

I agree for this PR. It should be analyzed separately though if it's even working correctly at all when the function modules are returning a failure status.

**Comment by flaiker** [comment]
I also added the change to raise an exception on pstatus = F. https://github.com/abapGit-tests/PROG_lxe worked just fine. For https://github.com/abapGit-tests/FUGR_lxe I get the same error.

**Comment by mbtools** [comment]
Our LXE approach is quite incomplete. Thanks for fixing the dump. 

For any further work on LXE, see also my comment in https://github.com/abapGit/abapGit/issues/4470#issuecomment-1027249544 (#2539 for the overall topic)

**Pull request merged**
