### PR TITLE
Fix ITAB_DUPLICATE_KEY dump during deserialize

### PR DESCRIPTION
**Pull request by mbtools**
Dumps when object is moved to different package

Regression #6093

### CODE REVIEW

**Comment by sbcgua** [comment]
Interestingly I didn't change this code, just moved it, literally from previous line - https://github.com/abapGit/abapGit/pull/6114/files#diff-7a848ddfe87ea2395b7a3bbf2beb14a8e2bb7bd32b1dafa69918d1b3c91f3bbbL596

But yeah, thanks for the fix. More UTs will save us :P

**Comment by mbtools** [comment]
Added screenshots. Looks like data in `lt_item` was not unique before ;-)

**Comment by sbcgua** [comment]
Yes, I noticed that too. Actually thats why that sort is there ... anyway, it ok, just strange

**Comment by sbcgua** [comment]
I guess fix is for good anyway, because we are looking for unique objects. Package was superfluous there.

**Pull request merged**
