### PR TITLE
Repo overview page, Polishing

### LINKED ISSUE #5846: Remove filter autofocus at repo overview
Having that repo overview is quite an interactive page with multiple keyboard shortcuts, table navigation and etc., forced filter field autofocus on first display is very inconvenient. Filtering is by far not the most probable action after AG start.
If no-one objects I'll remove the autofocus and add a key-combination to focus it intentionally.
As a final touch to #5781

### LINKED ISSUE #5848: UI - Repository List - Dark Theme broken in Version 1.118.0
The dark theme seems to be broken in Version 1.118.0.
The background of the table used to be grey but is now white.
This makes it rather hard to read the text.

OLD:
OLD

NEW:
NEW

To reproduce the issue, the dark mode must be activated under "Settings" -> "Personal" -> "User  Interface" -> "Theme".
Settings

### PR DESCRIPTION
**Pull request by sbcgua**
final tuning for #5781

1) Rework reset sorting order (follows #5840, #5839)
2) Better overflow in settings

normalized label separator is `comma+space`. Looks nicer + fixes overflow

before
2022-11-06_16h01_32

after
2022-11-06_17h01_08

3) Remove filter autofocus (fixes #5846)
4) And, just by the way, same for Stage page, couldn't pass by, it was also annoying
5) Fix dark there for overview (fixes #5848, @NeumannJoerg please check)

All fixes commit-by-commit for easier review

### CODE REVIEW

**Comment by mbtools** [comment]
@christianguenter2 you're the master of link hints ;-). `f` does make sense for the filter field. after this, `f` would not anymore as a link hint on the overview. Are you ok changing to another key? `L` ?

https://github.com/abapGit/abapGit/blob/bf8c3590a854911f8a77fbe426b4e1b183eb5990/src/zcl_abapgit_settings.clas.abap#L381-L383

**Comment by sbcgua** [comment]
Yeah, I was going to propose the same. F stands very well for Filter or Find ... Would be great if we could change the defaults for the link hints

**Comment by christianguenter2** [comment]
> @christianguenter2 you're the master of link hints ;-). `f` does make sense for the filter field. after this, `f` would not work anymore as a link hint on the overview. Are you ok changing to another key? `L` ?
> 
Sure go ahead.

**Comment by mbtools** [comment]
I changed the Vimium default to `t` since that must be working well :-)

**Pull request merged**
