### PR TITLE
HTTP connection check and improved error messages

### LINKED ISSUE #6772: Improve error messages when creating HTTP client
`zcl_abapgit_http->create_by_url` (https://github.com/abapGit/abapGit/pull/6771)

Add longtext and link to docs

### PR DESCRIPTION
**Pull request by mbtools**
One of the most common problems in abapGit is dealing with [connection issues](https://github.com/abapGit/abapGit/issues?q=is%3Aissue+ssl+is%3Aclosed).

This change introduces a connection check when working with online repositories. The connection is checked in the following situations:

- Creating a new online repo
- Changing the URL in remote settings of a repo
- Opening the repository view of a repo

Errors are now shown at the bottom of the current page. This allows viewing of the error longtext, which now provides details about the attempted HTTP connection (hostname, SSL ID, and proxy). It also includes links to the important transactions (rz10, strust), the global proxy settings, and the corresponding abapGit documentation (see last screenshot).

On the repo view, the header remains visible so that you can jump to the repo settings as well, for example, to correct the URL.

Before:

image

After:

image

image

image

Closes #6772

### CODE REVIEW

**Comment by fabianlupa** [comment]
This looks great!

There might be one side effect though. Currently often developers in development systems attempt to install abapGit and fail because of network issues. Then they get the basis team involved which understandably complains about the developer messing around in system settings and certificates they have no idea about or not adhering to company policies they didn't know about because it's not their area of expertise. Since developers often have SAP_ALL in dev boxes and are just restricted by policy to not change system settings no authorization checks prevent them from messing stuff up. These new detailed error messages will lessen the chance of the basis team getting involved at all and increasing the chance of developers just trial-by-erroring their way through... Maybe add a comment to get the basis / network team involved?

**Comment by mbtools** [comment]
True. Someone will go off, connect SAP to the world, and get covid into their system 😄 

I added a comment here and also to [docs](https://github.com/abapGit/docs.abapgit.org/pull/212).

**Review by larshp — CHANGES_REQUESTED** [review]
first test, I get the login popup for abapGit,

image

**Comment by mbtools** [comment]
i have a fix. needs some more testing

**Comment by larshp** [comment]
@mbtools is this PR ready for review again?

**Comment by mbtools** [comment]
yes

**Review by larshp — APPROVED** [review]
lgtm

**Comment by albertmink** [comment]
As of today, I get this error message when accessing any repository with ZABAPGIT. Could this be related to this PR? Just wondering, because yesterday it worked and today, something is broken?!  (The fork I am running contains the changes from this PR.)
Screenshot 2024-03-07 at 15 40 49

**Comment by fabianlupa** [comment]
> As of today, I get this error message when accessing any repository with ZABAPGIT. Could this be related to this PR? Just wondering, because yesterday it worked and today, something is broken?! (The fork I am running contains the changes from this PR.) Screenshot 2024-03-07 at 15 40 49

The certificate seems to have been renewed on GitHub's side today. You may need to trust it in your system.

image

**Comment by albertmink** [comment]
Thanks for the input 🙌

**Pull request merged**
