### PR TITLE
generic object handler: fix unit test

### PR DESCRIPTION
**Pull request by larshp**
some objects/systems have multiple primary tables(huh?), but anyhow, sort as per the database table to get the correct result

### CODE REVIEW

**Comment by mbtools** [comment]
It's bad modeling 🤷 . I'm fine with the change but there's no guarantee that it's identifying the best (primary) table.

image

For example, `IATU` has the main table `IACTU` on pos 5.

**Comment by larshp** [comment]
merging

**Comment by larshp** [comment]
hmm, yea, its the sequence of tables in the file that causes the diff?

**Comment by mbtools** [comment]
Yes

**Comment by larshp** [comment]
@mbtools do you have time to do the fix? you have the testcase already 😁

**Comment by mbtools** [comment]
np

**Pull request merged**
