### PR TITLE
fix sapevents for chromium based browser control

### LINKED ISSUE #4471: SAPGUI 7.70 Chromium based browser control - Hotkeys don't work anymore
With SAPGUI 7.70 and the Chromium based browser control shortcuts don't work anymore.
Maybe same root cause as #4468

### PR DESCRIPTION
**Pull request by christianguenter2**
fixes #4471 and #4468 

The chromium based browser control introduced with SAPGUI 7.70 uses other links for sapevents than the old IE control.

e.g.:
    Chromium  `file:///SAPEVENT:stage_refresh`
    IE `sapevent:stage_refresh`

With this commit we are able to handle both types for hotkeys and js triggered sapevents like patch.

It seems that the new control has some hard coded search and replace functionality which prefixes sapevent links with "file:///" automagically. That leads to some funny effects in abapGit diffs.

e.g. this is the same diff rendered in IE and chromium

IE
image
Chromium
image

Stage and commit works correct, so it's just visually confusing.

### CODE REVIEW

**Comment by mbtools** [comment]
Thanks for the fix! This should have been documented by SAP
2901278 - SAP GUI HTML Control based on Chromium Edge: Legacy HTML does not work (correctly) / present limitations
https://launchpad.support.sap.com/#/notes/0002901278

An SAP hack, probably for performance reasons since parsing the DOM to adjust only links was too slow.

**Comment by larshp** [comment]
@mbtools did you test this change? can it be merged?

**Comment by mbtools** [comment]
I don't have GUI770. I did test that it still works on GUI760 with IE control. I think we can merge

**Comment by larshp** [comment]
merging

**Pull request merged**
