### PR TITLE
add write protected icon in overview

### LINKED ISSUE #4528: show the BG and lock icons in the repo overview
image

show in repo list,
image

### PR DESCRIPTION
**Pull request by larshp**
closes #4528

adding a new column seems overkill?

image

### CODE REVIEW

**Comment by sbcgua** [comment]
Hmmm, what about shifting it after repo name (with m-em5-sides or a another `margin-left` style)
image

Or even superscripting it
image

**Comment by g-back** [comment]
Agreed, also keep in mind that "Background" mode can/should also be added in the same fashion at some point.

**Comment by larshp** [comment]
updated, 
image

**Review by sbcgua — APPROVED** [review]
Looks good.  :)

P.S. For more icons I would really suggest adding superscript @g-back

**Pull request merged**
