### PR TITLE
Unknown action error using Edge with GUI 7.70 PL02

### PR DESCRIPTION
**Pull request by jrodriguez-rc**
Using Edge browser control in the PL02 for GUI 7.70 the event is un uppercase:
image

Using Internet Explorer browser control:
image

But all constants are in lowercase:
image

### CODE REVIEW

**Comment by christianguenter2** [comment]
Works partially. I still get some 'Unknown action' errors while navigating through abapGit.
image

**Comment by christianguenter2** [comment]
abapGit_

**Comment by jrodriguez-rc** [comment]
I will check it tomorrow, maybe we need to report an incident to SAP

**Comment by christianguenter2** [comment]
Seems the whole navigation is messed up.  It has something todo with BACK-Navigation not working properly. First guess some issues here ZCL_ABAPGIT_GUI / BACK
image

**Comment by christianguenter2** [comment]
There's a different URL returned here:

https://github.com/abapGit/abapGit/blob/a9c40ea972c02307c0caa0dea34ee0a84ab1d1c3/src/ui/zcl_abapgit_html_viewer_gui.clas.abap#L89-L94

IE-Control:
image

Chromium
image

Which lead to different navigation here as it contains 'http'
https://github.com/abapGit/abapGit/blob/a9c40ea972c02307c0caa0dea34ee0a84ab1d1c3/src/ui/core/zcl_abapgit_gui.clas.abap#L119-L122

**Comment by christianguenter2** [comment]
Can you help reviewing #4842? It contains your fix more or less too.

**Comment by jrodriguez-rc** [comment]
I'll check it tomorrow. I'm going to close this PR

**Pull request closed without merging**
