### PR TITLE
Refactor: Repo uninstall

### PR DESCRIPTION
**Pull request by mbtools**
CI revealed issues with uninstalling repos. A key cause was dependencies between objects. The old routine tried to delete objects continuously until all dependencies where resolved. However, packages were included in this loop although they always must be deleted last.

`zcl_abapgit_objects->delete` now separates the object list into packages and others and processes them one after the other.

### CODE REVIEW

**Comment by larshp** [comment]
they must be deleted last => it sounds like it can be solved by fixing the sequencing? but is implemented by adding a special case?

**Comment by mbtools** [comment]
packages were last in the dependency order, but the old routine looped over all objects several times which disrupts the order. it tried to drop packages although other objects (which had dependencies) still existed. 

if - one day - each object can specify its full dependencies, we can revisit this to have a combined graph.

**Review by larshp — CHANGES_REQUESTED** [review]
see comments

**Comment by larshp** [comment]
well, that means there is a general problem, which will occur with more different objects than packages?

In that case I think this PR will make it more difficult to fix the original issue

**Comment by mbtools** [comment]
need to determine which object types cause the problem with uninstall

**Comment by mbtools** [comment]
looks like only `IOBJ` and `ODSO` are impacted due to dependencies between objects of the same type. Will try to find different solution.

**Pull request closed without merging**
