### PR TITLE
Serialise only main language for ENHS and ENHO objects

### PR DESCRIPTION
**Pull request by jan-jezek**
Can be easily extended to other objects that have SOTR usage.

### CODE REVIEW

**Comment by jan-jezek** [comment]
Sorry about the abaplint commits...
I am still learning the abaplint "syntax".

**Comment by larshp** [comment]
sometimes it can be quite strict, but I value having a consistent codebase

don't worry about the number of commits in a pull request, for abapGit we squash and merge all pull requests, https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#squash-and-merge-your-pull-request-commits

**Review by larshp — CHANGES_REQUESTED** [review]
I dont expected changes to `zif_abapgit_object` each serializer gets the language via the constructor, and typically stored in `mv_langauge`, can this be used instead of changing the interface?

**Comment by jan-jezek** [comment]
Sorry about that, I was confused about the call stack.

**Review by larshp — APPROVED** [review]
thanks, looks good to me

**Pull request merged**
