### PR TITLE
DSFI: CDS Scalar Function Implementation

### PR DESCRIPTION
**Pull request by fvalves**
Implemented DSFI Object Handler as specified in abapGit#6949

### CODE REVIEW

**Comment by larshp** [comment]
https://github.com/abapGit-tests/DSFI

**Comment by mbtools** [comment]
- [ ] AFF: https://github.com/SAP/abap-file-formats/pull/624
- [ ] Example: https://github.com/abapGit-tests/DSFI

**Comment by larshp** [comment]
@fvalves can you help providing a sample at https://github.com/abapGit-tests/DSFI ?

**Review by larshp — CHANGES_REQUESTED** [review]
see above

**Comment by fvalves** [comment]
> @fvalves can you help providing a sample at https://github.com/abapGit-tests/DSFI ?

Created https://github.com/abapGit-tests/DSFI/pull/1 with a sample

**Comment by mbtools** [comment]
This [dsfi file](https://github.com/abapGit-tests/DSFI/blob/2cfd3feb7898b5727657ba5e72bd1c1a0a8472c9/src/zdsfi_example_sql.dsfi.acds) has extension `acds` but the content looks like `json`. That's not correct

**Comment by fvalves** [comment]
Hi @mbtools , that is in fact how DSFI objects are represented in the corresponding metadata table.

**Comment by larshp** [comment]
also if there are additional files, they should be mentioned in https://github.com/SAP/abap-file-formats/tree/main/file-formats/dsfi

**Comment by mbtools** [comment]
actually, it makes more sense to embed [this json data](https://github.com/abapGit-tests/DSFI/blob/main/src/zdsfi_example_sql.dsfi.acds) into the [main json file](https://github.com/abapGit-tests/DSFI/blob/2cfd3feb7898b5727657ba5e72bd1c1a0a8472c9/src/zdsfi_example_sql.dsfi.json) so there's only one json file.

**Comment by fvalves** [comment]
> also if there are additional files, they should be mentioned in https://github.com/SAP/abap-file-formats/tree/main/file-formats/dsfi

Yes, there's a pull request there for this update as well

**Comment by fvalves** [comment]
@mbtools in fact both files contain the same information. I'll redesign the handlers so that only the json file is used.

**Comment by fvalves** [comment]
Created https://github.com/abapGit-tests/DSFI/pull/2 to update the test to the latest AFF as defined in https://github.com/SAP/abap-file-formats/pull/624

**Comment by larshp** [comment]
thanks, lets merge this PR after https://github.com/SAP/abap-file-formats/pull/624 is merged

**Comment by fvalves** [comment]
Hi @larshp , https://github.com/SAP/abap-file-formats/pull/624 has been merged, could we please proceed with this PR? Thank you!

**Comment by larshp** [comment]
thanks

**Review by larshp — APPROVED** [review]

**Comment by larshp** [comment]
supported list updated, https://github.com/abapGit/docs.abapgit.org/pull/242

**Pull request merged**
