### PR TITLE
New abapGit Handler for Object Type DTEB

### PR DESCRIPTION
**Pull request by BeckerWdf**

### CODE REVIEW

**Comment by BeckerWdf** [comment]
> please check [abapGit/docs.abapgit.org#202](https://github.com/abapGit/docs.abapgit.org/pull/202), [abapGit/docs.abapgit.org#203](https://github.com/abapGit/docs.abapgit.org/pull/203)

Sure. What's wrong in the current state of the PR?

**Comment by mbtools** [comment]
- `.abap` file needs a newline after `endclass.`. 
- `.xml` should have `<DESCRIPT>abapGit - DTEB  - CDS Entity Buffer</DESCRIPT>`

**Comment by BeckerWdf** [comment]
> * `.abap` file needs a newline after `endclass.`.
> * `.xml` should have `<DESCRIPT>abapGit - DTEB  - CDS Entity Buffer</DESCRIPT>`

Done

**Review by mbtools — APPROVED** [review]
👍

**Comment by mbtools** [comment]
Any more? Just needs an update to https://docs.abapgit.org/user-guide/reference/supported.html when done

**Pull request merged**
