### PR TITLE
Auto login in background mode

### PR DESCRIPTION
**Pull request by gepparta**
If we have different git projects on same server
and created BOT users + access tokens per project (for example in gitlab) 
to be able to auto commit in abapGit background mode, 

current logic in zcl_abapgit_login_manager prohibits correct login via different bot-users as it uses zcl_abapgit_url=>host() as tablekey for repositories. 
This way it always picks the first auth found for all different projects. Login fails then for further projects.

In given fix, use of zcl_abapgit_url=>host() has been deleted.
A corresponding testmethod has been added, see auto_login_background_mode.
Obsolete test method "same_server" has been deleted.

### CODE REVIEW

**Comment by mbtools** [comment]
Are your "bot users" not running their own jobs for the repos linked to their git user?

**Comment by mbtools** [comment]
Here's a clean and secure way to handle your scenario (without changing AG):

- For each combination of bot user + token, create an RFC destination
- Implement the `CREATE_HTTP_CLIENT` exit and map the repositories to their corresponding RFC destinations (https://docs.abapgit.org/ref-exits.html#create_http_client)

**Comment by gepparta** [comment]
I'm following a defined way described here
https://docs.abapgit.org/settings-background-mode.html

As abapGit offers a background mode for some time now where you can store your user+password per repository, 
in the past, it took this info for authentication against the configured repository.

Now creating rfc destinations and implementing exits here on top seems like a workaround for me.

Actually, our background jobs have been working like this for some time, 
till the change with zcl_abapgit_url=>host() broke it.

Now I had the time to check whats wrong and saw this behavior.


Besides, Marc, are you sure that my change will force Users outside of background mode to login for each repo separately?

**Comment by mbtools** [comment]
I don't see any related change to the login manager. Accoding to blame `zcl_abapgit_url=>host()` existed for 4 years and we don't want to change it unnecessarily:
https://github.com/abapGit/abapGit/blame/main/src/utils/zcl_abapgit_login_manager.clas.abap

The solution to the issue is to clear the buffer in `zcl_abapgit_background` after processing each repo:

```abap
method run.
...
          li_background->run(
            io_repo     = lo_repo
            ii_log      = li_log
            it_settings = <ls_list>-settings ).

*>>>INSERT
          " Purge auth buffer to allow different user/password per repo    
          zcl_abapgit_login_manager=>clear( ).
*<<<INSERT
         
        CATCH zcx_abapgit_exception INTO lx_error.
          li_log->add_exception( lx_error ).
      ENDTRY.
```

Can you give this a try, please?

**Comment by gepparta** [comment]
Thanks, I will give it a try.

**Comment by mbtools** [comment]
just close this and open a new one with the suggested change

**Comment by larshp** [comment]
close?

**Comment by gepparta** [comment]
I will open a new request with suggested solution

**Pull request closed without merging**
