### PR TITLE
UI repo over view page refactoring

### PR DESCRIPTION
**Pull request by sbcgua**
to #5781, after #5788

**No function changes**, just better code structure:
1. Re-use new `td` features (#5788) (remove unnecessary `column`) and thus fix html alignment issues
2. Move a couple of generic-like methods to chunks (render repo url, timestamp, text input ...)
3. Add `zcl_abapgit_gui_component->register_hotkeys` - a nice shortcut method to register own hotkeys (check the usage in main and repo_over - looks cleaner)
4. Move the repo-over related code from main to repo-over (event handling, hotkeys).
5. Better internal code structure

P.S. main page kind of still lives ... but contain only the top menu ... I guess it can be removed completely at some next iteration. I just thought that the main menu is not a part of repo overview specifically so I didn't touch it

### CODE REVIEW

**Comment by larshp** [comment]
is this PR ready for review? just add skips to https://github.com/sbcgua/abapGit/blob/hf/repo-over-refactoring/test/abap_transpile.json, then I'll have a look sometime

**Comment by sbcgua** [comment]
Yes, but I'd review it after #5788. I'll rebase it to remove superfluous changes (zcl_html related).

**Comment by sbcgua** [comment]
This one is ready for review then. I think no need to rebase as the main has been merged. 
Just to emphasize: this is just refactoring, no functional changes yet

**Review by mbtools — APPROVED** [review]
Tested. LGTM 👍 

Nice code improvements. Much clearer

**Pull request merged**
