### PR TITLE
New abapGit Handler for Object Type DRTY

### PR DESCRIPTION
**Pull request by BeckerWdf**
See: https://github.com/abapGit/abapGit/issues/5912#issuecomment-1545349139

### CODE REVIEW

**Comment by BeckerWdf** [comment]
Why does the linter say: "Statement does not exist in ABAPv702(or a parser error), "CALL" . This seems to be wrong.

**Comment by larshp** [comment]
> Why does the linter say: "Statement does not exist in ABAPv702(or a parser error), "CALL" . This seems to be wrong.

its the CONV part that makes it non 702 compatible

**Comment by larshp** [comment]
does `CL_DRTY_AFF_OBJECT_HANDLER` work on all versions supporting `DRTY`?

**Comment by BeckerWdf** [comment]
> does `CL_DRTY_AFF_OBJECT_HANDLER` work on all versions supporting `DRTY`?

With versions you mean releases of the ABAP server?
This AFF handler was initially delivered with the cloud release 2305. So in the onPrem world it arrived with AS ABAP 7.58.
So I would say yes to your question.

**Comment by larshp** [comment]
yea, so the AFF handler was part of the same release that introduced object type DRTY

**Comment by BeckerWdf** [comment]
> yea, so the AFF handler was part of the same release that introduced object type DRTY

Yes.

**Review by larshp — APPROVED** [review]
lgtm 👍

**Comment by mbtools** [comment]
please create a test case in https://github.com/abapGit-tests/DRTY. Thanks

**Comment by BeckerWdf** [comment]
> please create a test case in https://github.com/abapGit-tests/DRTY. Thanks

See: https://github.com/abapGit-tests/DRTY/pull/1

**Comment by BeckerWdf** [comment]
can this be merged?

**Review by mbtools — APPROVED** [review]
👍

**Pull request merged**
