### PR TITLE
Gui component: Simplify handlers registration

### PR DESCRIPTION
**Pull request by sbcgua**
To #6049
Not that I'm super excited but definitely less code to call. Complete automation seems not possible to me, unless there is a gui helper method to render components

So instead
```abap
  ii_html->add( <div> )
  ii_html->add( some_component->render( ) )
```

It should be
```abap
  ii_html->add( <div> )
  ii_html->add( gui_services->render_component( some_component ) )
```

Then `render_component` will call all the automatic stuff. But seems like one clutter for another (maybe I'm wrong here)

Welcome to review.

### CODE REVIEW

**Comment by sbcgua** [comment]
And by the way html_form became a gui_component which is a good precedent. :)

**Comment by sbcgua** [comment]
@mbtools Could you pls have a look ? What do you think ?

**Comment by larshp** [comment]
Marc is off for vacation at the moment, will leave it for some days, and I'll do a review by then

**Comment by sbcgua** [comment]
Sure, no rush then :)

**Comment by larshp** [comment]
🚢

**Comment by mbtools** [comment]
Nice! Thanks.

For me, it make more sense to register the events in the constructor but it works like this too :-)

**Comment by sbcgua** [comment]
Problem is there is this page stack, so first pages do not go away and thus won't unregister. And I also faintly remember there was some issue with sequence of object creation, so that something was not available until first render ... (but really don't remember).

Full automation would be very nice of course.

**Pull request merged**
