### PR TITLE
Prevent staging of duplicate files

### PR DESCRIPTION
**Pull request by mbtools**
Since objects cannot exist in multiple packages, the staging page is now checking the selected files to prevent the resulting repo from containing an object multiple times.

If an object is moved to another SAP package and the corresponding files are selected to be added to the repo (for the new package), then the files must also be removed from the repo (from the old package). If not, an error is raised.

Also fixes status calculation for the old object (from "match" to "deleted")

Before (missing icon for old files, no error when staging just new files):

image

image

After:

image

image

### CODE REVIEW

**Comment by larshp** [comment]
@sbcgua can you help testing this change? #4393

**Comment by sbcgua** [comment]
OK, so this is certainly an improvement. AGBUG repo is at least showing the "D" files. The logic described is OK. Let me review the code with a fresh head tomorrow.

In the long run I think it should not be A+D, but in fact it should try detecting a rename (which is not even a status at the moment). But can be done later, no prob.

**Comment by larshp** [comment]
@sbcgua

**Comment by sbcgua** [comment]
Will check today-tomorrow, sorry for a pause

**Review by sbcgua — APPROVED** [review]
:+1: looks good. Certainly an improvement !

**Comment by larshp** [comment]
thanks 👍

**Pull request merged**
