### PR TITLE
DTEL: REF TO DATA for DDIC element support

### PR DESCRIPTION
**Pull request by raaleksandr**
When trying to import a project with data element of type 'REF TO DATA' contained in a DDIC structure we got error.
This is fix for the issue.
See issue #5347 for details.

### CODE REVIEW

**Review by mbtools — APPROVED** [review]
LGTM 👍

**Comment by larshp** [comment]
welcome to abapGit as a contributor 🎉

**Comment by sandraros** [comment]
I think the PR is not complete in this scenario:
- [Repository](https://github.com/sandraros/test-abapgit/tree/issue-5365-class1-dtel-class2) (branch `issue-5365-class1-dtel-class2`) containing:
  - Class `zcl_5365_attribute` with attribute `number`
  - Data element as `type ref to zcl_5365_attribute`
  - Class with code `varTypedAsDataElement->number`
- When you pull it, the data element doesn't activate because the class doesn't exist yet and the whole activation fails:
  image

Proposed solution: #5370 (not very clean, suggestions welcome!)

**Comment by sandraros** [comment]
I just realized that the OP issue could have been solved differently. So I just updated my PR, it's smarter, cleaner and works for the two test repositories.

Here the [repository](https://github.com/sandraros/test-abapgit/tree/issue-5365-class1-strucomp-ref-to-data) for the OP issue (branch `issue-5365-class1-strucomp-ref-to-data`).

**Pull request merged**
