### PR TITLE
no chained assignment

### PR DESCRIPTION
**Pull request by larshp**
rule https://rules.abaplint.org/no_chained_assignment/ enabled

https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#dont-chain-assignments

this will also help automatic inlining variables the [upport](https://github.com/abapGit/upport)

### CODE REVIEW

**Comment by mbtools** [comment]
I think it needs to be resolved differently. 

V1 = V2 = V3.

V2 = V3. 
V1 = V2. (Not V1 = V3)

Otherwise casting might lead to different results. Need a system to try...

**Comment by larshp** [comment]
I did not pay attention to that :) But quickly looking at the code I dont think it will be a problem in these changes?

**Comment by larshp** [comment]
one bug fixed, nice find 👍

**Comment by larshp** [comment]
@mbtools any additional comments?

**Review by mbtools — APPROVED** [review]
go for it 👍

**Pull request merged**
