### PR TITLE
Support Ukraine

### PR DESCRIPTION
**Pull request by mbtools**
Adds a Ukraine heart-shaped flag with link to Ukraine Red Cross.

image

### CODE REVIEW

**Comment by flaiker** [comment]
Here's an adjusted svg of the logo, the png looks a bit pixelated around the corners.

logo_ukr

**Comment by mbtools** [comment]
Thanks for the beautiful SVG work @flaiker. Lars and I decided to keep it simple :-)

**Comment by mbtools** [comment]
@sbcgua Alexander, please do us the honor to merge this PR. Peace!

**Comment by sbcgua** [comment]
With pleasure! Thank you for your support and involvement ! :+1:

**Pull request merged**
