### PR TITLE
[AFF] Add the type for INTF (manually)

### PR DESCRIPTION
**Pull request by albertmink**
This is the basis for providing the ABAP file format for the object type INTERFACE, see #4861.

### CODE REVIEW

**Comment by mbtools** [comment]
hmmm, I don't think `intf` is a good object type to switch over to AFF. It would immediately lead to a mix of xml and json for pretty much all existing repos. Diffs everywhere. 

We should agree on a strategy on how we introduce AFF to existing object types (esp. for the common objects like DDIC or containing ABAP). Maybe we need a switch in the repo settings.

**Comment by mbtools** [comment]
Sounds like a plan. We still have to support deserializing the xml format to be backward compatible. Significant work is required to support such mix of xml and json for the same object. Right now it's either or.

**Comment by larshp** [comment]
yea, it must be backwards compatible, still possible to read old xml files

**Comment by albertmink** [comment]
Just reverted the AJSON parts, so that the PR contains only the AFF types defined in the interfaces.

Concerning:

> D: need to setup mirroring of https://github.com/abapGit/aff_mirror into main abapGit repo

What about enrich the abap sources by a dummy xml, such that abapGit can work with the objects?

**Comment by larshp** [comment]
two things:
* copy the corresponding XMLs from the aff_mirror repo, so we get the same descriptions
* adjust the linter configuration so to ignore the unused for this folder

**Review by larshp — APPROVED** [review]

**Comment by mbtools** [comment]
can we move these to `/src/objects/aff` or a sub-package of it?

**Comment by albertmink** [comment]
So what is the recommendation?

The folder AFF is actually used for the AFF object handler. NOT for its types.

**Pull request merged**
