### PR TITLE
Enhance "Debug Info"

### PR DESCRIPTION
**Pull request by mbtools**
Based on idea https://github.com/abapGit/abapGit/issues/4722#issuecomment-827551624

- Switch `zcl_abapgit_page_debuginfo` to `zcl_abapgit_page_component`
- Differentiate output between Developer and Standalone versions (see below)
- Add link to contribution guidelines
- Add output of sap basis release and support package
- Add listing of user exits with implementation status (based on include for standalone, class for developer version)
- Add feature to save debug info output as HTML page which can be used for attaching to Github issues

Developer version:

image

Standalone version: 

image

### CODE REVIEW

**Comment by mbtools** [comment]
After #4766

**Review by larshp — APPROVED** [review]
LGTM 👍

**Comment by larshp** [comment]
@mbtools ok to merge?

**Comment by mbtools** [comment]
yes, you can merge

**Pull request merged**
