### PR TITLE
Fix typos and adjust comments within the codebase (Cont'd)

### PR DESCRIPTION
**Pull request by francisco-milan**
Addressing outstanding items in #6777.

### CODE REVIEW

**Comment by larshp** [comment]
just one file changed?

**Comment by francisco-milan** [comment]
Hi Lars,

    I'm still working on this. it is going to take me a few hours.

Best regards,

Francisco.
________________________________

**Comment by larshp** [comment]
okay, I'll convert the PR to draft, https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request

set to ready when done

**Comment by francisco-milan** [comment]
Sure, I will do.

Thanks Lars!
________________________________

**Comment by francisco-milan** [comment]
Closes #6777

**Review by mbtools — APPROVED** [review]
Shocking how many things you found! Thanks for spending the time

**Comment by francisco-milan** [comment]
> Shocking how many things you found! Thanks for spending the time

Thank you so much! I'm glad to hear that the findings were helpful, and it was a valuable opportunity for me to learn from the team. I truly appreciate your guidance throughout the process. If there's anything else you'd like assistance with, feel free to let me know. I'm here to help!

**Comment by francisco-milan** [comment]
In the future, maybe we can explore the integration of a spell checker. This could help prevent typos in the source code and ensure high quality.

**Comment by mbtools** [comment]
an automated solution would need to understand abap syntax (literals) and SAP terms (typical abbreviations). don't think this exists, but happy to check one out if you find it. 

we're usually pretty good checking new PRs. most of your fixes were in (very) old code so it was good to get this cleaned.

**Pull request merged**
