### PR TITLE
Ensure open in main language opens same abapGit version

### LINKED ISSUE #4276: Open in main language in standalone opens development version
Scenario:

- You want to update abapGit and have installed the development version
- You don't use the development version for the upgrade since you last upgraded half a year ago and assume it will fail to upgrade such a large difference
- You download the current standalone version
- You execute the standalone version, open the abapGit repo, press pull
- You cannot pull as you are logged on in german while the main language is english
- The error message tells you you can press the Advanced -> Open in main language button
- You press the button. A new window is opened with logon language EN.
- The new window opened the old abapGit development version instead of the standalone report which you were trying to avoid in the first place. This is not easily identifyable as they look mostly identical except for the version number at the bottom.

### PR DESCRIPTION
**Pull request by flaiker**
Fixes #4276

### CODE REVIEW

**Review by mbtools — APPROVED** [review]
Thank you 👍

**Comment by larshp** [comment]
can `sy-tcode` be used? it assumes the report was started via transaction code, but that will also probably be the case?

**Comment by flaiker** [comment]
Oh yea, that seems much more sensible... The simple solution is the most difficult to think of.

**Comment by flaiker** [comment]
Though you still need to check where it points to right? I. e. SA38, SA39 etc. will be in sy-tcode as well which won't work.

**Comment by larshp** [comment]
yea, might introduce some bugs, merging

**Pull request merged**
