### PR TITLE
`uccp()`, cloud compatibility

### PR DESCRIPTION
**Pull request by larshp**
https://github.com/heliconialabs/steampunkification?tab=readme-ov-file#cl_abap_conv_in_ceuccp

### CODE REVIEW

**Comment by albertmink** [comment]
Double checked and the CL_ABAP_CONV_CODEPAGE is released, https://sap.github.io/abap-atc-cr-cv-s4hc/?q=CL_ABAP_CONV_CODEPAGE

I just wonder if the returning type `char1` in abapGit is correct, as the legacy version returns kind of `char2` and the ABAP Cloud version `cl_abap_conv_codepage=>create_in( )->convert( )` returns type `string`.
image

**Comment by larshp** [comment]
> Double checked and the CL_ABAP_CONV_CODEPAGE is released, https://sap.github.io/abap-atc-cr-cv-s4hc/?q=CL_ABAP_CONV_CODEPAGE

yaya, but we cannot really use the information provided by SAP for anything, https://abapedia.org/steampunk-2305-api/cl_abap_conv_codepage.clas.html tells it doesnt exist on 702

**Comment by larshp** [comment]
type updated

**Review by albertmink — APPROVED** [review]
LGTM

**Pull request merged**
